### ISSUE TITLE
No separation incidents while locked on ILS

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#101]
While on the ILS planes should not cause a separation incident, e.g. same height on parallel runways

**Comment by avdg** [comment]
I'm sure it depends on specialized technology that the airports are using to make these things possible, for example: http://www.airservicesaustralia.com/precision-runway-monitor/a-pilots-guide-to-ils-prm-approaches/.

Though I personally know nothing about how this is done in practice.

**Comment by harp71** [comment]
The vertical separation should be 1000 feed, the horizontal 3NM in minimum
at approach heights. But if on ILS that rule does not or cannot apply. E.g.
on Munich Airport the two parallel runways are less than 1NM apart and
there are planes landing simultaneously. So my suggestion is: no separation
incidents while on (different, parallel) ILS.

2015-05-12 18:55 GMT+02:00 Anthony Van de Gejuchte <notifications@github.com

**Comment by avdg** [comment]
Yes, though safety is still a concern.

Simply disabling it and then being in a situation that a plane is flying into another plane is simply undesired. It's way more complicated than just disabling the rules.

So the question now is, what procedures should one follow.

**Comment by harp71** [comment]
As i said: as long as two planes ILS locked on two parallel strips there is
no separation incident

2015-05-12 19:36 GMT+02:00 Anthony Van de Gejuchte <notifications@github.com

**Comment by zlsa** [comment]
According to the answer [here](http://aviation.stackexchange.com/questions/12931/what-is-the-minimum-distance-allowed-between-two-parallel-runways), the minimum _runway centerline separation_ for IFR is 750 feet; I seem to recall that you cannot land wingtip-to-wingtip in those conditions (IFR), though.

**Comment by avdg** [comment]
Since this is a simulation and there are [so many factors](http://www.skybrary.aero/index.php/Parallel_Runway_Operation#Safety-Related_Issues_Affecting_Independent_Approaches_to_Closely-Spaced_Parallel_Instrument_Runways) that can influence the possibility of a parallel approach . Maybe we should reduce the use case to 'perfect condition' for now (good weather, no technical issues, etc... ). These things can always be added later separately and it will simplify the implementation for now.

(uh I should have read the title while thinking of a separation strategy)

We might take the rule that separation of airplanes is lowered when planes are locked to ILS and reduce the distance before having a separation incident event. Since there are multiple standards (thanks for the link!) maybe it should be configurable by map.

Though given [some information about safety related issues (yeah, I'm using that link again :-))](http://www.skybrary.aero/index.php/Parallel_Runway_Operation#Safety-Related_Issues_Affecting_Independent_Approaches_to_Closely-Spaced_Parallel_Instrument_Runways), a serious separation incident should be happening at 150 meters (about 492.1 foot?).

**Comment by avdg** [comment]
It's actually good to gather and read the information, its so easy to find and there are a lot of details to be considered...
