### ISSUE TITLE
Error makes it impossible for planes to takeoff

### ISSUE THREAD

**Issue by oslego** [zlsa/atc#105]
![screen shot 2015-05-26 at 3 35 26 pm](https://cloud.githubusercontent.com/assets/63899/7814964/7198e3d8-03bd-11e5-91e2-24a7f9a260f4.jpg)

Two planes on the runway (though the UI doesn't show them anymore). 
Commands to takeoff are ignored. Looks like a JS error. Perhaps #19 could fix this.

**Comment by tedrek** [comment]
My understanding of the issue here is that there are two aircraft which were told to wait on a given runway.  At least one of them became visible on the runway and then disappeared again, the takeoff command is not followed for either aircraft.  After waiting at least 60 seconds no aircraft appears on the runway ready to take off.

I am unable to figure out a way in which aircraft can become 'stuck' waiting to takeoff such that no aircraft shows up.  More information is necessary for me to make any progress.

The javascript error shown relates to telling the last aircraft in line to takeoff when there are aircraft waiting in front of it.  There is a pull request with a fix for this.

**Comment by harp71** [comment]
i maybe have a clue: you can replicate the symptom by 
1. let an aircraft wait on a runway for takeoff
2. let a arriving aircraft crash into it. Both disappear (as expected)
3. try to let the next aircraft wait on the same runway. It will say "... number 1 behind ..." and the flightnumber of the first, destroyed aircraft
