### ISSUE TITLE
Suggestion: Unexpected events - aircraft faults / pilot error

### ISSUE THREAD

**Issue by ajillingworth** [zlsa/atc#12]
This is a lot of fun! (I used to play bsdgames atc all the time as well.)

A suggestion for an enhancement: A set of random events that make it a bit less predictable:
- Pilot error in landing causing a wave-off.
- Engine faults requiring emergency landing
- Planes coming in with low fuel because there was a back up at another airport.
- more?

**Comment by zlsa** [comment]
These are all on my radar, so to speak.

**Comment by daviessm** [comment]
I'm interested in working on this. @zlsa would you like to make any suggestions as to how it should be implemented?

I'm thinking:
- Spawning arrivals may declare a fuel emergency. Thoughts:
  - In real life the radar blips are highlighted/flash if the plane squawks 7700.
  - Would there be a timeout or something before the plane crashes?
  - More points for an expedient landing?
- Departures may declare an engine failure after takeoff (at around 1000ft) and require routing back around as an arrival.
  - Pilot might request to land on a specific runway and would have to be honoured
- Go-around
  - Go-arounds are fairly common, due to either pilot or tower decision
  - Plane would simply return to being an arrival
- Technical issue
  - On approach a plane might have a gear warning or other system failure requiring a hold until the pilots are happy
  - After departure a plane might have a system failure requiring them to inform the controller that they're stopping their climb and levelling off, unable to go higher. After a period of time they would either return as arrival or continue having solved the problem.

In any case, emergencies should be toggle-able through the UI, probably with a frequency setting (off/realistic (hardly any)/medium/high/very high) which would alter the probability of an event occurring.

**Comment by zlsa** [comment]
All of those sound very good.

I'd add an object in the `Aircraft` class (`assets/scripts/aircraft.js`) named `emergency` and just semi-randomly set some emergencies to `true` in the `init` function (where aircraft are spawned).

Go-arounds are already possible, but only if you drastically mismanage approaches and they can't descend fast enough.

**Comment by Diastro** [comment]
@daviessm I'd love to work with you on that one!

**Comment by daviessm** [comment]
Thanks @zlsa, @Diastro that sounds good. What would you like to do?

**Comment by Diastro** [comment]
@daviessm I think we should work on the UI first (highlight planes in emergency situation on the map and on the rigth panel with info, maybe the emergency type). 

Once this would be done it would be easy to simply implement an emergency class like @zlsa said and the logic to trigger these emergency.

I'm currently working on an airport/waypoint calculator i'll be able to jump in tomorow probably. Do you want to start with the UI part? I'm thinking about something like a red highlight on the right panel and emergency type instead of the waypoint. What do you think? What were you thinking about (UI wise)?

**Comment by daviessm** [comment]
Well, I only have a couple of hours today and tomorrow then I'm away for ten days so I'll try to get something done.

There is already an empty type in aircraft.js for emergency, for now I'll add one element to that: type, which will be null or one of a few types. I'll start with "fuel".

```
  this.emergency = {
    type: "fuel" //null, "fuel"
  };
```

For the UI, what about making the red approach indicator bar on the left hand side flash both on the radar and the strips?

**Comment by daviessm** [comment]
https://github.com/daviessm/atc/commit/a5e4650600dafec017270d231ff10a32776a6f01

There's some UI, feel free to have a look. I would like to make the strip on the canvas flash too but I can't figure out where it's drawn.

Thinking about it (and this isn't just an excuse for not doing it) in real life the type of emergency wouldn't be shown - it would be up to the controller to remember. So I would vote for not showing it on the strips.

**Comment by zlsa** [comment]
I'd vote for having a framework formultiple emergencies; i.e. `emergency.fuel`, `emergency.engine_out`. Re: displaying the emergency on radar, ideally, it would display the squawk (so 7700); in lieu of that, I'd add a red ring around the aircraft dot or something (i.e. in `canvas.js`, draw an arc if `aircraft.isEmergency()` or something similar).

**Comment by Diastro** [comment]
@daviessm Good point.

@zlsa Im good with that.

**Comment by daviessm** [comment]
In terms of ATC, what do they need to do differently to handle different emergencies? As far as I'm aware, they need to either a) get the plane to the runway as fast as possible or b) give it space away from other traffic to fix its own problems. I'm not sure what else we'd need to really capture so a whole framework might be overkill (at this point). All I can think of at the moment is that there should be some kind of countdown in which time the plane needs to land, in case a). Case b) isn't an emergency at all really ("pan pan") - but might be upgraded to one.

**Comment by daviessm** [comment]
https://github.com/daviessm/atc/commit/747997adfe214744701385ea3e02948ca29038a9

Now the aircraft on the canvas turn red when in an emergency state. That's me done for this evening so feel free to change anything you like and I might get time to work on it some more tomorrow. :smiley:

**Comment by daviessm** [comment]
@Diastro I'm back - are you still interested?

**Comment by Diastro** [comment]
Hey! Yeah I haven't push in a couple of week either! Yeah, let's do it!

**Comment by daviessm** [comment]
@diastro excellent! Do you want to take a look at my branch and think about how to put planes in an emergency state?

I'm thinking we need a configurable probability of emergencies because in reality they're quite rare but people might want to have a lot in the sim. Then planes will, at random, request either a) immediate landing or b) a place to hold away from other traffic.

In case a), points could be awarded for landing quicker than normal and for b) the aircraft would hold for a random period from 5-30 minutes then either change to situation a) or revert to a normal arrival/departure at random.

What do you think?

**Comment by sixeyeco** [comment]
I love this!!!!  may I add 2 cents? 

equipment failures might require ATC vectoring a craft to a runway without using waypoints. diverting emergencies to alternate airports does happen, perhaps a craft could request it? though we'd have no idea how to vector them.  

IRL ATC's request the nature of the emergency. They inquire about the number of souls on board and the fuel remaining in pounds. sometimes ATC's don't get an immediate reply, forgetting to ask before a certain point docks points. ATC's ask crew if they want equipment standing by.

certain failures require a fuel dump (over water? [FAA doc re: fuel dumping).](https://www.faa.gov/air_traffic/publications/ATpubs/ATC/atc0904.html) set (if able) specific location/speed/altitude to dump? when a craft reaches the proper location/speed/altitude he requests the dump. if the craft is not given authorization to dump then the ATC has wasted precious time and should be docked. 

if a craft (with a qualifying failure) lands without dumping first it crashes and closes the airport and all other craft need to be diverted to their alternate. 

perhaps a craft will request a low altitude flyover so ground crew can check gear? 

i am very excited to start having more to do! After the initial takeoffs and landings the game gets really slow. 

New syntax? **state** emergency (fuel/souls/alternate/equipment), **dump** authorized (denied), etc.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
