### ISSUE TITLE
Bugs in arrival and departure frequency handling

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#140]
In airport.js, the implementation of frequency for departures and arrivals is broken. You can confirm this for example by changing all of the arrival frequencies in `kdbg.json` to [1, 1], and seeing that arrivals actually occur more often than before. This is because frequency is not converted correctly into timeout periods.

Looking at `ksfo.json` and adding up all of the arrival frequencies gives [25, 43]. I am guessing the intent is for that to generate between 25 and 43 arrivals _per hour_ in total (correct me if this is wrong).

Part of the issue is here I think; the current code schedules an arrival timeout using:

```
arrival.timeout = game_timeout(this.addAircraftArrival, crange(0, Math.random(), 1, arrival.frequency[0] / prop.game.frequency, arrival.frequency[1] / prop.game.frequency), this, [arrival, null, true]);
```

The second argument to `game_timeout()` is a delay (presumably in seconds), but this code appears to be using frequency without converting it to delay.

If the intent is to translate `x` cycles per hour into delay periods measured in seconds, that requires `3600 / x`. (e.g. for 20 cycles per hour, 3600/20 = 180 seconds = 3 minutes).

Summary:
- assuming .json files specify [min, max] frequency per hour
- the frequencies should not be multiplied by 60 in `parse`
- `game_timeout()` should be called with a timeout in seconds of `3600 / x`, where x is in the range specified in .json

Does this make sense?

**Comment by zlsa** [comment]
That sounds right. It's been so long since I wrote it that I really don't remember much about how it worked.

**Comment by tedrek** [comment]
This all makes sense, but the assumption that frequencies are in aircraft per hour is incorrect.

As currently written the frequency is specifying the minimum and maximum delay in minutes between aircraft being generated.  A frequency of [1, 1] would generate 1 aircraft every 60 seconds.  In other words it's minutes/aircraft instead of aircraft/hour.

KSFO for example has departure frequency as [4, 7].  This translates to one departure every 5.5 minutes on average or 10.9 aircraft/hour.  Arrivals can be calculated by dividing 1 by the average frequency of an arrival stanza and adding those together to get the number of aircraft per minute.  For KSFO this should be about 1.8 aircraft/minute or 109 aircraft/hour currently.

Since we are on the topic of aircraft frequency.  I have been playing with ideas for varying the load and composition over the course of the game.  The current system results in a relatively constant stream of aircraft both arriving and departing.  I was thinking of making three different ways of generating aircraft:
- the current 'constant frequency' method
- a 'cyclic' method
- and a 'wave' method

Both of the methods would be better specified in terms of aircraft/hour instead of minutes/aircraft.

The cyclic method would gradually change the frequency of generation such that over an hour the specified number of aircraft would be generated but they would be concentrated within half of the chosen period.  A phase type option would allow departures to be similiarly specified but in such a way that departure high periods didn't coincide with arrival high periods (unless that was intended).

The wave method would be similiar but with the guarantee that during the high period of the cycle aircraft are spawned with the minimum spacing between them (as appropriate to speed, etc.).

I'm not sure what the best period would be to use as it depends on how long the average person plays.

**Comment by glangford** [comment]
Ah, ok. When I saw frequency, I assumed that meant operations per hour, not delay. Thanks for the clarification.

> Arrivals can be calculated by dividing 1 by the average frequency of an arrival stanza and adding those together to get the number of aircraft per minute. For KSFO this should be about 1.8 aircraft/minute or 109 aircraft/hour currently.

Note that 109/hour is above the capacity of the actual KSFO airport (and way beyond what is playable by me anyway!), which is what lead me to think the "frequencies" were messed up in some way. "rate 0.5" is my friend.

> I'm not sure what the best period would be to use as it depends on how long the average person plays.

I have never played for an entire hour at one go. I would probably go longer if there was a logic to the stream of arrival aircraft ; right now for KSFO there is a harsh mix of general aviation and jets, and inevitable conflicts even before they are in radar range. Once the troubleshooting starts at long range, even the best plans go awry. This is frustrating for most users I think, since aircraft are often in conflict even before they have been given any directions.

My recommendation would be to look at tuning the existing arrival rates and directions, before adding new ways of generating aircraft.
