### ISSUE TITLE
Wind based scoring

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#146]
The current wind scoring doesn't differentiate between crosswind and headwind, resulting in headwind takeoffs at too great of an angle giving the surprising message of 'xxx taking off with a tailwind'.

The solution I was going to follow would be to score based on crosswind and headwind/tailwind separately.  Any tailwind over 1 knot (or some other value) would count as a windy movement, this allows some slight leeway in both the math and a crosswind at nearly 90 degrees to the runway.

For crosswind I'd ignore anything under 5 knots, from 5-15 knots would score as a moderate crosswind and over 15 knots would score as an extreme crosswind.  The values given are rough guesses and I would appreciate any input on what real life considers moderate/high/extreme crosswinds.

Eventually I'd like to see variable winds and to have aircraft reject landings and take offs where there was too much crosswind.

**Comment by glangford** [comment]
I would definitely like to see a change here sooner rather than later; the "taking off with a tailwind" message when there is clearly a headwind is a bug.

> For crosswind I'd ignore anything under 5 knots, from 5-15 knots would score as a moderate crosswind and over 15 knots would score as an extreme crosswind. The values given are rough guesses and I would appreciate any input on what real life considers moderate/high/extreme crosswinds.

"Aircraft manufacturers publish a tailwind component limit for both takeoff and landing in the AFM. In most cases, it is in the order of 10 knots but may be as high as 15 knots."

http://www.skybrary.aero/index.php/Tailwind_Operations

Some commentary here on crosswind limits:
http://www.airliners.net/aviation-forums/tech_ops/read.main/133443/
