### ISSUE TITLE
Proposal to use standard terminal arrival routes (STARs)

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#147]
This is an enhancement proposal for introducing standard terminal arrival routes (STARs). All feedback is welcome.
### Basic feature

Currently, multiple fixes can be provided in a single command to instruct aircraft to follow a particular path. Often, the same sequence of fixes are typed for aircraft to follow before clearance for landing on an assigned runway.

Rather than typing “ {aircraft id} FIX {fix1} {fix2} {fix3} ...”, common sequences based on a subset of published STARs for each airport can be used.

For example, to mimic the “Modesto Five” arrival at KSFO, we could currently type the sequence of required fixes:

<aircraft id> FIX GROAN CEDES ARCHI MEHTA

Or, we could record this STAR in ksfo.json as an array of fix names, and the user could type:

<aircraft id> STAR MODESTO

(dropping the version number “five” for simplicity). This would result in the same behaviour as navigating the sequence of fixes, and usually reduce the amount of typing. The aircraft navmode would be “fix” when the STAR is assigned, as if all the fix names were entered.

Entering the STAR will not always be shorter to type; for example, the Golden Gate Six arrival consists of just the fixes PYE and DUXBY. A more compact STAR name could be used (eg. “GGATE”).
### Additional supporting features
- KSFO can be used as a test airport as it already has the required fixes; additional fix points can be added for other airports, as required
- supported STARs for an airport could be drawn on the canvas as thin solid or dashed lines connecting the fixes, so there is a visual reminder
- the flight strip could reflect the current STAR, as well as the current fix. In the above example, “MODESTO asterisk GROAN” could be displayed in the strip after the STAR command is entered (rather than just “GROAN”. Later, “MODESTO asterisk CEDES”, etc.
- for spacing traffic in the real world, shortcuts are often provided which deviate from the published routes. An additional command called “DIRECT” could be added to provide a shortcut, while maintaining the list of fixes. For example, “DIRECT ARCHI” would delete any intervening fixes, but retain ARCHI and MEHTA on the Modesto Five STAR. This is the same command ATC would give.
- to get a reminder at selected fixes, a controller can ask for an aircraft to report at selected waypoints/fixes. An additional command called “REPORT” could be added. For example, “REPORT ARCHI” would cause a message to be displayed when that fix is reached.

**Comment by akymakr** [comment]
Great enhancement.
Few suggestions listed here: https://github.com/zlsa/atc/issues/128

Keep on good work!

**Comment by tedrek** [comment]
I had been thinking of STARs as something which an aircraft is already on at the time it spawns as my understanding was a STAR would be assigned by the relevant center instead of a TRACON.  Therefore the aircraft would note which STAR it was on when it made initial contact and continue on that lateral path until told otherwise, our job as controller would be to just authorize altitude changes within our airspace and then final vectors and landing authorization.  This way a new command isn't required.

For technical implementation all that is necessary is being able to specify a set of fixes (preferably with a final heading after the last fix) to follow when spawning an arriving aircraft.  Preferably a target altitude and speed can also be specified to allow spawning aircraft which are descending in a realistic fashion.

The additional features look great, I like the idea of showing a subtle route for a given STAR.  Note the 'direct' command is already present as an alternative to 'fix'.

**Comment by glangford** [comment]
> I had been thinking of STARs as something which an aircraft is already on at the time it spawns as my understanding was a STAR would be assigned by the relevant center instead of a TRACON.

In the real world, an aircraft may have already filed for a STAR in their flight plan, or ATC can add a STAR as it nears the airport. From a game play/simulation standpoint it might be boring to have the STAR automatically assigned, so I was thinking more along the lines of using a command. In this sense, it requires some problem solving and the game play is similar to today.

> Note the 'direct' command is already present as an alternative to 'fix'.

I am proposing a change to the behaviour of "direct". Rather than just being a synonym for "fix", "direct" would adjust the current set of fixes, not overwrite them. For example, if the current fix list is A,B,C,D, using the new "DIRECT C" would result in C,D as the fix list. Today "DIRECT C" I think would just result in the fix C replacing the original list. I think this new behaviour is consistent with the ATC instruction to go direct to a fix when on a STAR.

**Comment by glangford** [comment]
@akymakr On #128 - not everything is addressed, but have a look at the new KSFO. It has some new fixes and should be accurate.

**Comment by glangford** [comment]
Here is an image of the updated KJFK, with some of the defined STARs overlaid; note that the routes begin well away from the actual airport, so the idea to attach a STAR at spawn time makes sense.

![new kjfk](https://cloud.githubusercontent.com/assets/3035114/9445977/083b667c-4a5d-11e5-875c-58b3a1f5bc14.png)

**Comment by Maverick283** [comment]
In real life, following STARs the pilots will usually continue flying a so called **"Transition"**. This brings them from the ending waypoint of the STAR onto the Approach in use (this doesn't mean one approach per STAR, as STARs are usually used to bundle aircrafts descending to an airport from one direction. It rather means after a STAR, any transition beginning at the ending fix of the STAR can be used). 
Of course any of those STARs as well as transitions can be exited anytime by giving the pilot a different heading or waypoint. 

The transitions are _"hidden"_ in the approaches. A typical call to an aircraft would be something like: "Cleared for the PAWLING2 Arrival, expect ILS runway 22 left". This would obviously be done before the pilot enters the STAR, thus it is kinda unusable for this simulation as the user should pick the runway in use. But he could still assign these transitions to the aircrafts when they pop up on his scope. 

This picture shows the chart of the ILS 22R at KJFK. Note how on the right border it says _(IAF) 117.7 DPK_ meaning that DPK is the initial approach fix. Thus the PAWLING2 Arrival (which ends with the DPK VOR) could be used to get an aircraft on the ILS 22R approach.
![KJFK ILS 22R APPROACH](https://cloud.githubusercontent.com/assets/12700191/9762918/e35c838e-5706-11e5-84cd-4f4a5ad888ee.jpg)

In the US, if a pilot is given a STAR, but not a transition or other clearance, he will usually request that transition (won't happen often, because ATC usually don't forget that). 
But in case of a radio failure, the pilot will follow certain procedures eventually bringing him to the airport without contacting ATC. 
I guess it is quite likely that a user might forget to pick up aircrafts arriving on STARs (No matter if transitions are implemented or not). Thus I'd suggest to make aircrafts hold on the last waypoint of the STAR if they have not been given any instructions, and send a radio message quite like the "ready for takeoff" message eventually repeating this message if it is not being reacted to. 

For the purpose of this comment I broke "full approaches" down into transitions and approaches. In charts they are usually depicted as one. The reason of my comment is to bring in some experience that might help you to improve.

**Comment by glangford** [comment]
Thanks @Maverick283 , very much appreciate the comments -

I was aware of the STAR+transition, but was hoping (perhaps incorrectly) that for simulation purposes we could start with a simplified version:
- no version number in the STAR (eg. PAWLING instead of PAWLING2)
- a STAR is defined initially anyway as an ordered set of fixes, without the notion of transition (eg. PAWLING2 ends at DPK)

Perhaps a new command could be added to help with this, to schedule what should happen. For example: 

**AT {fix} HEADING {heading} LAND {runway}**
(the 'LAND' portion would be optional).

So a user seeing an aircraft somewhere on PAWLING2 before DPK could provide the 'glue'.

> Thus I'd suggest to make aircrafts hold on the last waypoint of the STAR if they have not been given any instructions, and send a radio message quite like the "ready for takeoff" message eventually repeating this message if it is not being reacted to.

Interesting point - or perhaps they change color and/or continue off in the same direction until attended to?

**Comment by Maverick283** [comment]
Yeah, the version number of the STAR is certainly not necessary. 

The command line sounds awesome,  though it'd be hard to get the airplane on a interception heading from for example the ROBER STAR. This is obviously where the LAND command could not be included (I don't like that STAR anyway, no idea why they created that one^^). 

Color sounds great, but wouldn't having them fly the same direction eventually cause interference with other planes? Then again, if there is another plane on the STAR, they would get quite close as well. Sounds like a loose loose situation ^^...

**Comment by glangford** [comment]
> Color sounds great, but wouldn't having them fly the same direction eventually cause interference with other planes?

Yes, that's the point (since it is a simulation)  :-).  I don't know if this is necessarily the best approach, but the current behaviour is that after a fix is reached, the aircraft continues on.

**Comment by Maverick283** [comment]
It is, though I personally (personally is the important word here!) find it rather confusing as when I forget about one plane and it flies straight I cannot re identify it with the plane I sent to that fix. 
I guess for simplicity and as you say as it is "just" a simulation that will work ;)

**Comment by nielsvdweide** [comment]
> AT {fix} HEADING {heading} LAND {runway}
> (the 'LAND' portion would be optional).

This is something that needs to be added as soon as possible! It makes much more sense to give these clearances!

**Comment by glangford** [comment]
This is now generally complete so I will mark this issue as closed. Two additional commands could be added in future if desired (separate issues can be opened to track these):
- REPORT at a waypoint
- scheduling a future command with AT {fix}

#187
#222
#224 
#228 
#265
