### ISSUE TITLE
"Leaving radar coverage" bug when navigating to a fix

### ISSUE THREAD

**Issue by glangford** [zlsa/atc#185]
The message "leaving radar coverage outside departure window" was given for UPS 624 pictured below; it is supposed to fly to LOCKE as the dashed line indicates, but it suddenly changed direction (uncommanded) as the message was generated.

This is likely triggered by UPS 624 reaching 10,000 feet.

It looks like a bug in aircraft.js `crossBoundary`; departing aircraft are automatically switched to "heading" mode.

![ups 624](https://cloud.githubusercontent.com/assets/3035114/10049607/3c324b12-61e6-11e5-8ba1-dc78a5a95b3f.png)

**Comment by tedrek** [comment]
That is expected and intentional behaviour for the code as written.  I'm not saying it's the correct behaviour for the game.

The intent with the radar coverage change was to reduce the controlled area to a defined cylindrical volume of air space with a ceiling.  The relevant change here is that you can clear an aircraft to 11,000 as an implicit handoff to the sector above you.  Once an aircraft leaves your sector the next sector vectors it directly away from the airport and climbs to 20,000 (at which point it should generally be removed from the simulation).  This is realistic in that the next sector will issue commands relevant to it's situation regardless of what you had issued.  The only way I saw to get around this is to have an explicit hand-off command which you would have to enter for every departure at the appropriate time, that doesn't sound like fun to me.

I have ran aircraft at 10,000 without them leaving control, so I suspect you cleared UPS624 to 11,000 or higher (not necessarily intentionally).  My best suggestion as a fix would be to disallow climbs out of the airspace, reverting to the original vertical behaviour.  When the option dialog gets implemented, then have a switch which allows climbing out of the airspace to leave the sector.

The reason for switching to a heading mode after leaving coverage was to avoid conflicts with arrivals.  By flying a radial directly away it guarantees lateral separation from arrivals if it leaves within the departure arc as all arrivals and departures are configured to be separate.  It also is a guaranteed mode to remove the aircraft from the game once it is out of the players control, leaving in fix or hold mode could result in an aircraft circling indefinitely.

**Comment by glangford** [comment]
> My best suggestion as a fix would be to disallow climbs out of the airspace, reverting to the original vertical behaviour.

Alternately - it sounds like we can just clear them to 10,000 until they leave the horizontal airspace, and this issue wouldn't occur?

**Comment by tedrek** [comment]
That is correct, clearing to only 10,000 will keep them within the controlled area.

The issue I'm suggesting needs fixing here is that allowing aircraft to depart via climb is not likely to be intuitive and will be surprising to a number of players if it hasn't been brought explicitly to their attention.

**Comment by Maverick283** [comment]
What if, as soon as an aircraft is above 10,000 the altitude and speed are not displayed anymore but instead a text saying "leaving control zone" or "handed off" or whatever comes to mind (it's late here, can't think of a proper english phrase right now). 

This way the player would know what is going on, and why the airplane is not doing what he told him to do (and maybe even doesn't respond to any commands anymore?).

**Comment by tedrek** [comment]
I'm considering it from the point of view where a player either doesn't know about it or accidentally assigns a higher altitude.  In both cases by the time they realize something is wrong there isn't anything they can do and there is no real warning before hand.  Updating the data block to show what has happened is a good way of explaining what has happened though.

**Comment by glangford** [comment]
Here is another interesting wrinkle: if an arriving aircraft spawns with the controlled area, yet leaves to navigate to a fix which is just outside the control area, the aircraft loses the fix and flies away.

I think the fix for this is to never have aircraft spawn directly within the control area.

**Comment by Maverick283** [comment]
@glangford When you say spawns in the control area, do you mean comes down from the sector above? Or do they just pop up at lets say 5000ft?

If they are descending from the sector above, a more complex fix might be considerable as some STARs in the future might have a steep descent into the control zone from above 10,000. Not sure about the code, and how easy it is to put a exception for STARs in, but this is just something to keep in mind.

**Comment by glangford** [comment]
> When you say spawns in the control area, do you mean comes down from the sector above? Or do they just pop up at lets say 5000ft?

@Maverick283 I mean they just pop up in the control area at between 8-10K feet. It doesn't happen often but it is possible. I am guessing it is a simple matter of changing the random generation so that arrivals always appear initially outside the control region.

**Comment by tedrek** [comment]
What is happening is when the game initially loads it tries to spawn a number of arrivals closer than default so you have something to play with, these can sometimes spawn within the terminal area.  They can also do so with a significant delay after starting.  It should be relatively simple to change so arrivals are always outside.

The somewhat difficult wrinkle to it is that aircraft spawned closer than a given fix should have that fix removed as they have already flown over it.

**Comment by glangford** [comment]
> The somewhat difficult wrinkle to it is that aircraft spawned closer than a given fix should have that fix removed as they have already flown over it.

True - I first came across the issue for KSFO and the fix MOVDD, which is the first fix in a STAR that lies just outside the control area. For KJFK, there are many fixes outside the control area that are in a STAR. Agreed also that you want to have something to actually play with on startup!  :smile:
