### ISSUE TITLE
Warning horizontal separation 1500 feet

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#225]
Why is there a warning, if aircrafts are not separated more than 1500 feet (white circle)? There is no need for that as there is no warning in real atc, as far a i know! It´s 1000 feet separation below FL290, that´s it.

**Comment by glangford** [comment]
I think the logic of the white circle is to point out a potential future problem - in other words, 1500 feet is ok for now but if it went to 1000 then it would turn red. There is no calculation of closest point of approach, or range tau (like TCAS does), it is simply based on the two positions.

I last updated the separation minima in #159 and #160.

**Comment by harp71** [comment]
Ok. I know the 1000 feet rule and the atc-warning as well as TCAS in
general. My question would be: where does the 1500 feet warning come from?
Is there a pre-warning like that in real ATC?

2015-11-09 17:08 GMT+01:00 Glenn Langford notifications@github.com:

**Comment by glangford** [comment]
> My question would be: where does the 1500 feet warning come from? Is there a pre-warning like that in real ATC?

Good question, I don't know the answer.

**Comment by Maverick283** [comment]
When communicating with ATC you sometimes here a warning sound in the background. My instructor, who went to college to study for becoming an ATC (I guess he knows his stuff ;) ) told me that this is the separation and/or CFIT warning. So yeah, there is a warning when aircraft come too close. I don't know at what point it engages though... But it happens rather often, so I'm pretty sure it is going off before the aircraft fly closer then minimum separation.

**Comment by erikquinn** [comment]
Though my brain is overloaded with multiple sets of acronyms, I don't believe CFIT has anything to do with the alarm you might hear going off. CFIT (colloquially "see-fit") would be for controlled-flight-into-terrain. We do have low altitude alarms when a _tracked_ aircraft goes under MOCA (or one of the minimum altitudes - MSA/MVA/MIA/MEA/MOCA - who knows anyway...), that appears with "LA" above the target, which prompts the controller to give a low altitude alert.

Similarly, there's a "CA" for conflict alert when two aircraft are merging and projected to lose separation. If I had to guess, I'd say it'll trigger when they are about 30 seconds from losing separation in terminal radar, and 60 seconds from losing sep in en route.

In TRACON, they both make the same super-annoying, super-loud "beep beep beep beep beep beep beep beep beep beep beep beep beep beep beep beep" that you would hear over the radio occasionally. Though they represent serious stuff, @Maverick283 is right, they happen all the time, and controllers will often chuckle at them going off when there's nothing wrong. Nicknames for said alarm include "lalacaca" and "the snitch", and if you get enough of them, by nature of the red and green, people start whistling christmas songs to mock you. haha good stuff!

Anywho, the point of this was to address @harp71's comment on the 1500' warning. It's not a thing in FAA ATC (I can't speak for ICAO ATC, navcanada or eurocontrol systems). Since aircraft are always descending and climbing at each other and stopping right at the bare minimum, it just doesn't offer any alarms until they actually pass through, which is why vertical separation is such a "make-a-mistake-and-you're-toast" situation. You get a heads-up with time to fix lateral separation issues, but with vertical, once you know about it, you've probably already had a deal. We should probably remove the 1500' warning (white) to reflect that, unless it's only the US's ARTS/STARS terminal radar systems that do it that way.

**Comment by erikquinn** [comment]
To clarify the last paragraph, in en route, the controller actually inputs all altitude changes into the computer as a record of what altitude each aircraft is cleared to, since they separate vertically way more than horizontally due to the nature of the traffic. Thus, if they enter altitudes that will conflict with aircraft ahead, that will trigger a conflict alert for them. But TRACON (what we're simulating), nah.

That said, I would LOVE to one day see this thing evolve into an either approach control OR en route radar simulator. Working stringent miles-in-trail restrictions to major airports could be equally as satisfying as this (plus you look cooler because you have even more airplanes)!

**Comment by Maverick283** [comment]
Thanks for the explanation @erikquinn, it's always good to learn something new :D

As it was suggested earlier I think we should introduce a option window rather then the bar at the bottom (but keep the bar for the most important settings). With wind on/off, altitude depending airspeed and all the other "plus realistic" stuff, there could be some presets (beginner, advanced, expert, and so on, but also customable) in settings, that represent different reality settings. This "prewarning" should be one of them and toggable, so beginners can get a heads up before they actually get points deducted!
