### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#232]
Another idea for an enhancement:

Based on Google Analytics or other means, users could get the explanations and other in game information in their own language. The ATC would obviously stay english. 

That way more users might start playing.

This again can wait, and just adds to the collection of ideas for later implementation.

**Comment by MaicomMR** [comment]
I can help to make a Braziliam Portuguease(PT-BR) translation, call me at need :smile:  :+1:

**Comment by Maverick283** [comment]
I'd be down for German and Spanish...

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
