### ISSUE TITLE
Magnetic north turns objects when it should not

### ISSUE THREAD

**Issue by culebron** [zlsa/atc#244]
**EDIT**: Is the map turned to magnetic heading intentionally? (I guess, it's turned so that vectors were in magnetic heading.)

Here's a screenshot of Domodedovo from OSM:
![selection_049](https://cloud.githubusercontent.com/assets/119675/11170551/80ee0c40-8bf9-11e5-946a-b42e7bb6f945.png)

And this is in the sim. I took real RWY coordinates from OSM and created two fixes from them, XXX and YYY, to check if I had a map consistent with real life, not distorted intentionally. As you see, they stand exactly at the ends of the runway.
 ![selection_051](https://cloud.githubusercontent.com/assets/119675/11170552/82500f20-8bf9-11e5-8a1a-22ea4180db0c.png)

**Comment by tedrek** [comment]
Yes, the behavior of magnetic_north causing objects to 'rotate' is intentional.  It is specifically so that runway headings would be in the expected orientation, runway 36 or 27 looked wrong without the rotation.  My feeling at the time was that drawing with true north as up instead of magnetic north as up would have been generally confusing for most players and not added anything substantial to the game (especially for the amount of work).

**Comment by culebron** [comment]
@tedrek agree.
