### ISSUE TITLE
Parallel Approach

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#261]
I was playing at KSFO the other day, and had a huge wave (lots of fun, thanks! :+1: ) coming in. 

As they were coming in from two sides, with their separation being minimum already, I wanted them two land at two runways simultaneously. As traffic got closer to the extended center line, the white circles started popping up, but as I cleared them on the approach (will be creating a new issue about that as well), they would disappear (great job!)

Here is the thing though:
When having two airplanes on a parallel approach (one for 28R and the other one for 28L), you still get the red circles and some points deducted.
KFSO (and many other large airports) allow for a parallel  approach. [(Page 12 for more detail)](http://www.faa.gov/documentLibrary/media/Notice/N8260_73.pdf)
This means that two aircraft can fly almost side by side as long as they are on the ILS and the later traffic has the one in front in side. 

For simulation purposes I think we could skip over the "in sight" rule, but it'd be great if you could have two planes land parallel, as it gives you the opportunity to get traffic in faster, and handle even more traffic!

**Comment by glangford** [comment]
Good stuff. I set up the arrivals for KSFO so that both 28L and 28R are needed for landings at peak.

There are no special rules in the simulation for SOIA or SCP, however it is possible to play with the current KSFO  arrival rate without point deductions. What you need to do is vector the aircraft for landing slightly staggered. This sometimes means sending some of the BIGSUR2 arrivals straight north, and joining the flow with a timely vector to PONKE, for example. Then you can interleave the two major sources of traffic.

**Comment by culebron** [comment]
Just keep one altitude, say 4K for one side and another one, 3K, for the other side. This way there's little risk of colliding them if you forget to give a vector on time.

**Comment by Maverick283** [comment]
@glangford Yeah, thats what I did after I figured out that I would get less points for separation violation. 
What I want to achieve here is that when a plane is on the approach (a.k.a. cleared to land in this simulation, check out #262 ) another plane can join the parallel approach without violating the separation minimums. 

If there is a higher rate of arrivals so that you more or less have to use parallel approaches (which I would welcome!!) then this should not result in a lower score.

@culebron That would work for the initial approach phase, but as soon as both planes start to descent with the glide slope, the same problem will occur.

**Comment by culebron** [comment]
I played SFO again, and indeed, on short final they shine red if going one next to another on different runways.

**Comment by culebron** [comment]
I created a pull request with a penalty for close calls (#267), and will need to take this into account.

**Comment by tedrek** [comment]
The situation at KSFO in reality is significantly more complex than side by side, which is why the code doesn't handle it well.  The existing system allows aircraft to get horizontally within 3000 feet of each during ILS landing, this simulates simultaneous approaches at airports like KJFK and KLAX where approaches can be flown independently and the runways are relatively far apart.

At KSFO it's not just a case of them being allowed to land side by side, rather they _have_ to land nearly side by side.  The aircraft landing on 28L flies a straight in approach, the aircraft landing on 28R must do all of the following:
- Be behind the other aircraft
- See the other aircraft
- Be close enough that wake turbulence will not be an issue
- Make a relatively late turn into the runway centerline after visually acquiring both the runway and the 28L aircraft.

Given the above, ATC's job at KSFO is more difficult because aircraft must be lined up as pairs.  The simple solution which either reduces or removes the horizontal distance check fails to capture the interesting things at KSFO while removing real penalties at other airports.  A proper simulation will require a fair amount of work (which I'm not interested in right now, perhaps at a later date).

The features I can think of which are probably necessary before this can be simulated properly are:
- Curved or segmented approaches
- Stateful separation warning checks (Particularly needed for simultaneous departures)
