### ISSUE TITLE
How to generate terrain GeoJSON files?

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#278]
Hi, can somebody tell me how to make a geojson for an airport? I tried to get it from the SBGL files and pull requests, but i didn´t. The files seem to be generated and not written by hand, just looking at the complexity. Where do i get the data for my area and how to i convert it into a geojson-file for my airport?

**Comment by zlsa** [comment]
I think @culebron is working on this ATM.

**Comment by harp71** [comment]
@culebron can you explain how to create a terrain map for ATC please :)

**Comment by culebron** [comment]
@harp71 I'm stuck with writing it.

If you like to play with GIS software, I can explain briefly: use QGIS. Take DEM files (SRTM3 - 3 arcsecond is enough), get contours with 305 m steps (or 1000 ft) preserving elevations in contours. Transform contours to polygons, then simplify them. Some use Ramer-Douglas algorithm (there are such plugins), but it makes very sharp ugly lines. I just expanded polygons (buffer) and then contracted them by 350 meters. Also remove small polygons. After that, I saved this file as GeoJSON, reducing digits to save disk space.

Technically speaking, you need QGIS with some plugins, and save it as GeoJSON in the end.

I've written a half of the long recipe already, give me some time please.

**Comment by harp71** [comment]
@culebron thanks for the short version, i´ll try to figure it out with the new infos.

**Comment by erikquinn** [comment]
It probably won't be as accurate as 3-arc-second data, but we could always just use Google's elevation data (as shown in Google Maps), which you can pull to google sketchup, and from there it's pretty easy to get it into autocad, where exporting to csv is "easy-peasy-lemon-squeezy" via the `dataextraction` function... An example of this technique on getting the data and drawing the lines is [here](https://www.youtube.com/watch?v=bav_t8qw2Mc).

Still plenty of tedious work, but it is manageable.

**Comment by MaicomMR** [comment]
I try to follow the @culebron steps but I'm stuck, I download the topo images from earthexplorer.usgs.gov, but dont know go ahead, we need a tutorial for this :stuck_out_tongue_winking_eye:

**Comment by headphase** [comment]
Hey guys I've made a simple terrain overlay for kjfk (no buildings yet) but something is messed up with the coordinates; it is sitting too far to the East and a tad bit North of where it should be.  When I check it against a geojson validator website it sits perfectly where it should. Any ideas @culebron ?  Which CRS projection method should I be using?

Also if someone could explain how to get the terrain key and colors that are currently used on the KSFO map that would be great!

![capture](https://cloud.githubusercontent.com/assets/6735197/14355322/7fabf3e4-fcae-11e5-928b-be8cb039e268.JPG)

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
