### ISSUE TITLE
Saving & Resuming Gameplay

### ISSUE THREAD

**Issue by ghost** [zlsa/atc#283]
I'm not too great at HTML or JS for that case, but I have an idea that I think would be quite nice for the project... Somehow, a way to save. Maybe you could sign-in with GitHub or Google or maybe just an old-fashion game save pin code, but I'd like to be able to save my game for when I go out instead of having to leave my computer on just to keep my game saved. Any possible way or anyone looking to contribute?

Thanks.

Also, on an unrelated note, how come the "too close circles" appear even if the two planes are 500 feet in altitude difference? Kind of annoyed me when I thought they were going to crash, but they were perfectly spaced as I had them.

**Comment by Maverick283** [comment]
The idea of saving has been sparking up a lot lately, I think this will be one of the next huge things that will be implemented... 

Red circles don't mean you're about to get a collision. They mark planes that are flying closer then the minimum separation rules allow them to, which deducts points of your score. White circles warn you that the minimum speration  is about to be reached, yet don't deduct points. 

Minimum speration is 1000ft above an below and in a 3 mile radius.

**Comment by ghost** [comment]
Ah, thanks @Maverick283. I'm kinda new to the game, hah. This again is a little off topic, but how high can the planes fly, is there even a limit?

**Comment by Maverick283** [comment]
They _can_ fly pretty high, i'm not aware of any limit, but they will leave the radar coverage once they are above FL100. I believe they disappear from the scope at FL110, but I'm not sure, I'd have to try. Or maybe @glangford can tell you more.

**Comment by glangford** [comment]
As @Maverick283 says - they will leave radar coverage once they are above FL100. Outside of the control area, the simulation will have departing aircraft climb higher than that.

You can clear a departure higher than FL100, but I don't recommend it! See #185.

(The game save idea is a good one, but I don't have time to contribute to it. Perhaps another approach would be to add bounds to a game session so that it isn't infinite in length and ends after a set period of time - like a controller shift change).

**Comment by Maverick283** [comment]
Let's discuss the idea of saving though, so someone has an base to build a program on:

What has to be saved?
- Of course: The score!
- The positions of the aircraft (Altitude, Coordinates, Heading, Speed, Destination)
- Clearances given to the aircraft (fix list, altitude assigned, speed assigned, departure clearances)
- Waiting departures
- Current wind ( + at some point maybe the weather)

How can it be saved?
I'm no good when it comes to cookies, but it could be either saved that way, or by dumping a downloadable file to the user, that then can be reopened next time he plays.
If that is done, a player might be able to hack/overload etc the whole thing by modifying the save file, maybe there is something that can be done to prevent this.

How can it be reloaded?
Well, from my point of view it'd be a "spawn all aircrafts, then reassign the clearances and let the code do the magic" kind of thing, i believe this should be no huge deal.

**Comment by avdg** [comment]
For saving we have options like:
- Cookies: limited storage (4k?), everything has to be stored in a string complying the format (should not contain cookie separators and stuff), very wide support though the content is send on every request.
- Server side: not an option as the server is currently serving static only (maybe 3rd party but who wants that? What will be used? etc...)
- Localstorage: stores like an object, wide support though its newer technology than cookies. Bigger storage (5MB?). Data is not send to server on every request in contrary to cookies.

**Comment by avdg** [comment]
Also there is the url anchor (#) storage method, easy to share progress with other players.

**Comment by glangford** [comment]
Localstorage would (I think) be the main option to consider. It is already used in the current code to store the last used airport, whether speech is enabled, etc.

**Comment by tedrek** [comment]
A rough calculation suggests save files would be in the 20-100kB range assuming a straight forward JSON representation.  With that size I think LocalStorage is the only real option at this point.

The other thing which needs to be saved is the state of the arrival and departure generators.

**Comment by culebron** [comment]
I actually tried a naive saving, just `JSON.stringify(prop.aicraft.list)`, but no, objects are not serializeable.  :) Need to make a list of properties.

**Comment by zlsa** [comment]
I usually use a recursive structure (i.e. `localStorage['state'] = game.save()` where `game.save()` serializes its data in a way that it can be recovered entirely with `game.restore()`; any objects to be saved will have similar functions.

**Comment by erikquinn** [comment]
As suggested by @culebron in #239, it would be good to:

> share saved data (I guess, get the saved state from local storage and encode in a URL over bit.ly)

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
