### ISSUE TITLE
Departing aircraft should have a preferred departure heading

### ISSUE THREAD

**Issue by zlsa** [zlsa/atc#29]
Departing aircraft have a direction they want to depart in; if you're more than 30 degrees off (for example) when they exit the screen, you lose score.

**Comment by z-adams** [comment]
where does it say this heading?

**Comment by zlsa** [comment]
It doesn't, this should be clarified; it's an enhancement.

**Comment by dominiks** [comment]
Would it make more sense to give them a specific heading to leave e.g. 180° and allow some leeway or just specify that they must be south or southeast from the airport when they leave the radar? I'd work in an implementation of such a system.

Also are there altitude requirements when leaving? I remember an ATC game I played on my Palm years ago where each leaving direction had a fixed height attached to it that aircrafts had to have when leaving. No idea of how realistic that is, though.

**Comment by zlsa** [comment]
Yeah, that would be fine. It's just to avoid people like me from having every departure fly north for the simplicity.

**Comment by daviessm** [comment]
atc-sim seems to implement this with aircraft having a required fix to head to after departure. I think that's a fairly sensible way of implementing it; after this point the aircraft could follow its own navigation to its destination - which in our case could be implemented as turning to a heading within 60° of the angle between the airport and the fix and climbing toward the aircraft's maximum altitude.

This could be done with a new command "(r)esume own navigation" with departure score points added for issuing this near the correct fix.

ATC could give the flight new commands afterward if it was heading towards other craft.

It's difficult for this because the sim (@zlsa what is it called? :-) has you perform the tasks of tower, approach and departure (or even more!) which would be different people at a busy airport.

**Comment by daviessm** [comment]
I think this guide from the flightgear flight sim is a pretty good idea of a realish sequence of events:

http://wiki.flightgear.org/ATC_Tutorial#Lining_up_and_taking_off

**Comment by AlexMcArrow** [comment]
I think it would be correct to do the following.
Make a point of several types (waypoint, point of rotation, the point of entry and exit)
- waypoint - just for travel
- point of rotation- just for travel, and, if the list is the latest way the plane, the plane begins to spin around her
- point of entry and exit - the point where the planes arrive and where it should fly for the correct care of the control zone. (in order list, departure planes just have name of point) + degrees heading on enter this point

Also, it will give a very simple way to generate arriving aircraft. And the ability to create a third type of aircraft - transit.

Sorry for my english.

**Comment by Maverick283** [comment]
@zlsa I think this can be closed?

**Comment by zlsa** [comment]
Yep, thanks @Maverick283
