### ISSUE TITLE
Real life airport layouts

### ISSUE THREAD

**Issue by zlsa** [zlsa/atc#3]
There's only a demo airport layout included; it would be nice to include multiple real-life airports. The format is a bit arcane, though.

**Comment by pcrumm** [comment]
Curious about your thoughts on this. I started playing around with SFO:
https://github.com/pcrumm/atc/blob/add-sfo/assets/airports/ksfo.json

I added the ILS/LOC approach 28L and 28R. There are no designated radio-assisted approaches for the other runways, so we'll need to make up fixes if we want a more symmetrical layout. You've spent more time thinking about the game than I have--better to leave it as is (and see operation like SFO really does), or to add some fixes on the other sides of the airport to make things easier? I'll probably work out the math for a few other local fix positions before I PR, but there won't be anywhere near as many, obviously.

**Comment by psycho202** [comment]
Currently working on JFK Intl airport.
Adding the fixes atm.

https://github.com/psycho202/atc/blob/kjfk/assets/airports/kjfk.json

**Comment by stijnsanders** [comment]
is there an online repository of waypoints? I checked http://www.faa.gov/ and http://www.eurocontrol.int/ but I guess a search from the homepage won't hand them to me
(but with just a little scratching: https://nfdc.faa.gov/xwiki/bin/view/NFDC/Browse+Aeronautical+Data )

**Comment by psycho202** [comment]
Dear Stijn: For the US airports, both me (who made KJFK) and arithmetric (who made KMSP) used the airport diagrams found on Flightaware.com.

Using KMSP as example: http://nl.flightaware.com/resources/airport/KMSP/IAP/ILS+RWY+30L%28CAT+II%29

There you can find all the waypoints in the Approach and Depart procedures.

**Comment by pcrumm** [comment]
These are also available from airnav:
http://www.airnav.com/airport/KSFO

In particular, you'll want to look for ILS/LOC approaches and VOR approaches, and scan over departure procedures, though you'll generally find that departure fixes are far enough away from the airport that they aren't really includable here without some fudging.

**Comment by stijnsanders** [comment]
ooh look what I found! would this make an interesting layout?
http://www.belgocontrol.be/website/eaip/eAIP_Main/html/eAIP/EB-AD-2.EBBR-en-GB.html

**Comment by tomasfg** [comment]
If you want some info about spanish airports you can have a look at this page:

http://www.enaire.es/csee/Satellite/navegacion-aerea/en/Page/1078418725163/?other=1083158950596#ancla3

There're lots of info but finding the one about waypoints can be a little bit trickier.

**Comment by psycho202** [comment]
@stijnsanders: Zaventem would indeed be interesting to see :)

**Comment by stijnsanders** [comment]
I'd like a go at it myself, but is there a guide or something? What does `runways.ils[]` do? How do I convert feet to `runways.length`? Is `runways.position` to the center of the lane, and what factor should I use to convert lat-long diffs from the ARP's? And then there's the `departures` and `arrivals` bit...

**Comment by stijnsanders** [comment]
With a bit of fiddling around with the numbers, and trying to convert lat-long to projected offsets, this is what I get so far: https://gist.github.com/stijnsanders/f9abfe9ee909d9d0babd 

Oddly enough the waypoints are way off onto Belgian territory, 'ANT' looks like Antwerp, the big city to the north, and 'KOK' is presumably Koksijde on the coastline!

**Comment by stijnsanders** [comment]
I've taken the time to do a proper pull request:
https://github.com/zlsa/atc/pull/66
also the calculations I did on the lat/long are here: https://drive.google.com/file/d/0B78PfaNlYkBsWHlzOGJpY2hRTGc/view?usp=sharing

**Comment by pcrumm** [comment]
Good work! I've been thinking of creating a little online map-making tool for this.

**Comment by Diastro** [comment]
Sweet. A little python tool would be awesome!

On Sat, Dec 20, 2014 at 1:46 PM, Phillip Crumm notifications@github.com
wrote:

> Good work! I've been thinking of creating a little online map-making tool
> for this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zlsa/atc/issues/3#issuecomment-67745543.

## 

_David Albertson_
_Senateur du comité étudiant en Génie logiciel_
_Administrateur du STEP, Serveurs télématiques_
_École Polytechnique de Montréal_

**Comment by larsen0815** [comment]
@Diastro : Wow, you´re quick. I just thought that something went wrong when I didn´t see my pull request any longer just two minutes after having added it. Thanks for accepting.

**Comment by ufkes** [comment]
I've added a PR for adding Amsterdam Schiphol. The scale and coordinates should be pretty accurate.
#95

**Comment by harp71** [comment]
Hi, can i add an airport? I created EDDM but have no exp. with github or any other colaborate project, for that matter.
![image](https://cloud.githubusercontent.com/assets/11310456/7254477/ab6478ce-e843-11e4-845b-37f52960b5be.png)

**Comment by larsen0815** [comment]
Yes, it is quite simple:
- Fork this project and checkout from your accont to your local machine
- Add the files
- You will have to change one file so EDDM gets included. Don´t recall exactly which one - just search for any other airport, e.g. EDDH
- Commit all your changes to your local repository and push it to your github repo
- Create a merge request on Github so it can be added to the main project

Some details might be missing in my explanation, but you should be able to start with this.

edit: see https://github.com/ufkes/atc/commit/644afa6fcb7ab30ebe5b8c0ac810071d722f7b77

**Comment by zlsa** [comment]
The file is assets/scripts/airports.js - just search for "airport_load("
and add "EDDM" (it should be obvious). Thanks @harp71!

**Comment by ufkes** [comment]
I've updated EHAM with better coordinates, new arrivals/departures (including KLM, woot!). Please review. #96

**Comment by glangford** [comment]
Just as a status update on this issue: I have updated KSFO, KJFK and KMSP with precise lat/long for all runways and fixes including key points for STAR routes. See #143, #148, and #168.

Here are the most useful resources I used in case others would like to add new airports:
- airnav.com for runway endpoint lat/long and layout - e.g. https://www.airnav.com/airport/KSFO
- flightaware.com for airport layout, ILS and STAR routes and fix names - e.g. http://flightaware.com/resources/airport/KSFO/procedures
- opennav.com for lat/long of fixes: e.g. http://opennav.com/navaid/US/SFO/SAN+FRANCISCO

Are there suggestions for new airports?

**Comment by stijnsanders** [comment]
I'm not sure if they would make a good fit for this game, but the thing with airports like [SXM](https://en.wikipedia.org/wiki/Princess_Juliana_International_Airport) and [HKG](https://en.wikipedia.org/wiki/Kai_Tak_Airport) is that take-off and landing parameters are to be taken pretty serious as to not slam into the mountain and things..

**Comment by glangford** [comment]
> I'm not sure if they would make a good fit for this game, but the thing with airports like SXM and HKG is that take-off and landing parameters are to be taken pretty serious as to not slam into the mountain and things..

Indeed, the climbout at SXM better include a right turn.  :) Not sure we are at that point for simulation purposes yet!

**Comment by harp71** [comment]
Is EDDM going to be merged in the main project?

**Comment by glangford** [comment]
@harp71 Have you sent a pull request with EDDM?

**Comment by harp71** [comment]
I did now (again), i thought i did then!?

2015-10-23 13:53 GMT+02:00 Glenn Langford notifications@github.com:

**Comment by zlsa** [comment]
Merged, thanks @harp71.

**Comment by sixeyeco** [comment]
I want to mess around making missions using airport json files on my fork. I copied `ksfo.json`, renamed it to "msfo" and added "msfo" to the list in `airport.js`but the game stops loading on msfo.json. Can anyone help?

**Comment by Fechulo** [comment]
@sixeyeco There is a mising comma after the MOLEN SID. That's probably why it doesn't work.

**Comment by harp71** [comment]
Did you change the data inside rhe Jason as well? It needs to be the new
airport icao there too.
Am 31.01.2016 16:52 schrieb "Chris" notifications@github.com:

**Comment by psycho202** [comment]
@sixeyeco
The file name isn't the only thing that needs to be changed. Go into the file, and change the tags inside.
The one I remember that you definitely need to change is the icao tag.
The way I remember how it worked is that it uses the filename to load the data and uses the ICAO tag to reference to the loaded data.

**Comment by sixeyeco** [comment]
@psycho202  Thank you for the quick reply. 

I forgot to mention that I edited the ksfo.json to
`"name": "Mission 1 (KSFO)",
  "level": "hard",
  "radio": "msfo",
  "icao": "MSFO",
  "iata": "msfo",`

I also copied the geo json and added one for msfo.
Can anyone think of anything else I've not done or have done incorrectly? 

And I'm emptying the cache to ensure I'm loading new stuff. </del>

**Comment by harp71** [comment]
If the filename AND ICAO have the same name I'm clueless at the moment
Am 31.01.2016 17:03 schrieb "Chris" notifications@github.com:

**Comment by harp71** [comment]
What is a mission?
Am 31.01.2016 17:50 schrieb "harP" emailanharp@gmail.com:

**Comment by sixeyeco** [comment]
@harp71 Yeah, I'm really scratching my head. Thanks though. I'm looking at using the airport files to create scenarios. By hard coding some variables to "heinous" I get a real workout. I know I could simply use time warp but I'd rather experience nightmare workloads in "real time". The advantage of using an airport file for this is that it would be immediately available as a preset, rather than having to wait until we see options for difficulty. 

It's down and dirty, I know, but I'm anxious for some variation. For now, all I've really done it so vastly increase the departures, making the early part of the game much more challenging. I think there's more arrivals but it's hard to tell. [I play this version of KFSO on my fork](http://sixeyeco.github.io/atc/), I just wanted to revert that file back to stock and create a separate file for the "mission". Maybe give it a go?

**Comment by sixeyeco** [comment]
Sorry I missed your comment @Fechulo , that was it. Thanks!!!!

**Comment by MikePapaSierra** [comment]
Hi all!

I already prepared one of the Polish airports, Warsaw Chopin Airport (EPWA). Because that's my first airport I decided to announce that before sending pull request. I'd like invite you to perform some functional tests, because I'm not expertise in development. 
That's first version/release of that airport so many things is missing, like:
- TMA boundary
- Restricted zones
- Military traffic
- SAR traffic

Currently primary issue that I have with that airport is fact that by default game is setting arrivals to use the best runway according to wind condition which is constants. EPWA is using system of preferred runways for arrivals and departures and I don't know how to achieve that.
New airport is available here: https://github.com/kamikazestar/atc
All ideas, comments and advice will be appropriated.

**Comment by Fechulo** [comment]
@kamikazestar The airport looks really good so far! For further discussion regarding EPWA I would advise opening a [new issue](https://github.com/zlsa/atc/issues/new). At the moment, there's no way of telling the game what the preferential runway system is. The best way to do this is by changing the winds, so that the game chooses the correct one. For example, if runway 33 was used for arrivals, I would suggest setting the winds to 330° or something similar.
I hope this helps!

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
