### ISSUE TITLE
Mission/Scenario/Timed mode

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#306]
Hi Folks,

There have been a number of suggestions for a limited or timed mode of some sort (#239 for example).  Let's get a rough consensus on how this feature should look in order to start with the implementation.

The general gist I have gotten is to have a relatively clear objective which can be completed in a relatively clear time frame.  Objectives are likely to be achieving high score within given constraints, or perhaps lowest time to achieve all goals.

I can think of three methods for controlling the time frame, please add any others you think may be relevant:
- Absolute time cut-off - The scenario ends and is scored exactly 30 minutes (or whatever) after it starts.
- Spawn time cut-off - Aircraft stop spawning after some time (20 minutes) and the scenario ends when all aircraft have landed or departed.
- Aircraft count - Race to depart/land some number of aircraft in total

Thoughts for scenarios:
- Overload - Major disruption causing many diversions to this airport (I can't remember who suggested this)
- Deteriorating weather - Weather dropping below minimums so arrivals which were incoming based on two runways operating are now needing to be fit into one runway.
- Poor weather - Operating in a lower capacity configuration than normal

This leads to a fairly obvious component of a scenario being the weather.  Overload at one airport could be normal operation at the same airport with the wind blowing a different direction.  Weather also dictates which runways should be in operation and therefore what STARs and approaches should be active.  Given all these things are currently specified in the airport files, I'm lead to the conclusion existing airports should really be looked at as a scenario and players should always select a scenario to play.

My implementation thought is to do a straight timed mode first.  It would consist of a load/welcome screen where the player selects an airport (and later scenario) and a play length (30 minutes, 1 hour, 2 hours, unlimited)?.  On the same screen would be information about the scenario such as a name and descriptoin (This would be a good place to talk briefly about landing procedures in operation during the scenario such as SOIA at KSFO or point merge at ENGM).  After clicking a 'Play' button the scenario loads and play continues as per the existing game.  After the specified length of play has passed the game engine is paused and a score screen is displayed showing the scenario played, final score, and any other statistics which are deemed relevant (miles flown? average time in the air?).

After the above, we would want to re-factor the scenario aspects out from the airport itself and allow multiple scenarios at an airport.  Weather, approaches/runways enabled, arrivals enabled, departures enabled.  There will end up with quite a few pieces which need to be developed to give the control necessary.

At some point completely dynamic weather could supported under this scheme but it could be done in a way which didn't break the airports which weren't yet configured for it.

Anyway, thoughts? Both on implementation details and things which you would like to be done as a scenario.

**Comment by Maverick283** [comment]
If there is a statistic and a huge new feature is implemented (like this one ;) ) then we should also have a global statistic going, meaning that there should be a high score list where one can enter themselves and compete with others. 

This would probably require a data  bank. Not sure if this can be done via github, but if not, heroku for example offers a (limited, but not too small) free Postgresql database...

**Comment by sixeyeco** [comment]
<a href="http://sixeyeco.github.io/atc" target="_blank"><img border="0" align="right" alt="Jon Ross' ATC" src="https://cloud.githubusercontent.com/assets/179496/12736911/24ead1a6-c909-11e5-8456-dbb5a82b49bc.png" ></a>I'm really looking forward to the day this comes about. 

I've edited airport files to create [scenarios on my fork](http://sixeyeco.github.io/atc). They're quite limited, certainly down and dirty... but it's working. 

At this time I have two; log jammed departures due to terrorist hoax, and closed airspace due to police activity. They are listed on the airport selection menu if anyone would like to check them out.

**Comment by erikquinn** [comment]
neat, @sixeyeco! PS I _really_ like the look of the dark theme you've made.

I was also thinking that at some point it would be good to present the user with a way to control the traffic flow rates in regular scenarios... ideally with sliders for each arrival fix and departure fix. And then people can customize the traffic to their liking, while also giving us an easy way to quickly create various scenarios to choose from at each airport. How does that sound?

**Comment by sixeyeco** [comment]
I love your idea. Here's my two cents:

Departures should be relatively easy because there is only one parameter. But a schedules option for arrivals opens up a host of questions. The good news is that there is a single parameter (frequency) common to each of the arrival traffic scheduling types (default, cyclic, wave, random) so a single slider globally adjusting the frequency (as a %) across all airports would seem to be the easiest method. 

Going a step further, [we could have a separate schedule controls for each airport](http://sixeyeco.github.io/atc/options-loader4b.html).  With this method the number of sliders should be dynamic to accommodate adding new airports. 
<a href="http://sixeyeco.github.io/atc/options-loader4b.html" target="_blank">
<img border="0" alt="ATC by Jon Ross" src="https://cloud.githubusercontent.com/assets/179496/12794624/ccafdf64-ca6a-11e5-9741-729b580ba639.png" width="700">
</a>

Diving deep, we could allow the player to dictate schedule type (default, cyclic, wave, random). And (as you suggested) a setting for each radial. Each schedule type has its own parameters (upper and lower bounds, periods, offsets, etc.) so there'd have to be a slider for each one. That would be amazing, but I can't even imagine how much work that would be. And not all airports have the same number of radials. For example, EGLC has thee arrival radials whereas KSFO has four. So, the label for, and quantity of, the sliders would have to dynamic and airport-specific. 

As far as the difficulty settings are concerned, I would vote for "normal"  being somewhere between min and max (and not necessarily at 50%, perhaps at 30%). This would provide for the beginners  and those with more experience. But it would also give the game an insane mode to entertain the sadistic among us.  
<a href="https://cloud.githubusercontent.com/assets/179496/12795409/cb02549a-ca6e-11e5-8c0a-33f62b9b7c1a.gif" target="_blank"><img border="0" alt="ATC by Jon Ross" src="https://cloud.githubusercontent.com/assets/179496/12795409/cb02549a-ca6e-11e5-8c0a-33f62b9b7c1a.gif" width="355"  align="right"></a>As far as a wish list is concerned, I'd love to see airspace closures. At some point in the game a message appears like "The police department has closed the airspace at [gps location] in a 3 mile radius to traffic below 3000' until further notice. The game would then populate a restricted area. Aircraft within the restricted area would need to vacate immediately and approaching flights would have to be diverted or ensure their altitude exceeds 3k'.   

If I can help let me know. I can do images, and spit out some cross-browser pure css knobs, sliders, toggles etc. but someone with real js skill would need make all the connections.

**Comment by erikquinn** [comment]
^ I have lots of thoughts to share, to the point that I created a new issue to get into it, so I don't hijack this issue with my own agenda. haha

To be continued on #374.

**Comment by erikquinn** [comment]
As suggested by @culebron in #239, if this is implemented, it would be nice to have some way to share your results of completing a mission or challenge.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
