### ISSUE TITLE
Further supported behaviors for waypoints

### ISSUE THREAD

**Issue by tedrek** [zlsa/atc#315]
From @erikquinn  in #313: Can we assign crossing restrictions for a fix/waypoint.  (eg. "descend at pilots discretion, cross BERRA at and maintain 1-1 thousand at 2-5-0 knots")? this is common in enroute and STARs, and would be both cool and helpful to emulate.

**Comment by tedrek** [comment]
After #313 is merged, it should certainly be easier and is one of the things I had envisioned when writing the feature.

Right now, the system supports setting an altitude and speed until a given waypoint followed by a different altitude and speed until the next waypoint.  To do crossing restrictions we'll need to add an altitude/speed by the given waypoint and the associated projection to start the descent/deceleration.

Another thing which needs to be implemented is exposing this functionality to the controller so you can assign some clearance in relation to a waypoint.  I had been thinking something like adding three verbs: 'until', 'by', and 'after'.  Example uses would be 'BAW831 by SENZY speed 180 altitude 2000', 'BAW831 until WAMMY speed 210 altitude 8000', 'BAW831 after WAMMY speed 250 altitude 10000'.

The question I have is, what happens when an aircraft is on a route where speed and altitude are assigned for multiple waypoints and the controller assigns a plain speed or altitude.  My expectation is that speed and altitude will be followed through subsequent waypoints unless the controller amends it but I would really like to hear what some other folks would expect.

**Comment by tedrek** [comment]
The other feature which I wanted to implement using this base was holding patterns followed by automatic holds on STARs if aircraft have not been cleared to further fixes.

**Comment by Maverick283** [comment]
If I get you right, you're asking what happens when a aircraft was told "descent altitude 5000 by ANYFX " (I believe this is the actual syntax @ericquinn?) and is told "maintain altitude 7000" before it reaches ANYFX or 5000 or 7000?
In this case the pilot would ignore the altitude part of the first instruction, and maintain 7000 but keep flying to the fix. Basically if one instruction overrides another, the more current one will be executed...

**Comment by erikquinn** [comment]
@tedrek in place of until/by/after, could I suggest until/cross/depart? that would be more in line with phraseology of the commands:

> > "AAL482, maintain 190 knots to FINKA"
> > "UAL3185, cross LENDY at Flight Level 190 at 250 knots"
> > "KAP515, depart BOWAN heading 360, vector for visual runway 28 approach"

As for changing stuff while descending via a STAR, if a speed/altitude instruction is given, it would cancel whatever is charted (they would continue with other one though, eg assigning a speed means they keep descending as charted but remain at the speed they were told). If the change was temporary, the controller would cancel it with either "cancel speed restriction" or something about "descend via the XXXXX# arrival" (I don't know the phraseology for the latter). Just like @Maverick283 said in his last sentence.

**Comment by Maverick283** [comment]
NOTE: All three links lead to the same PDF document!

@erikquinn is right, the actual phraseology for FAA countries is "descent via the ANYAR arrival" ([As mentioned in 4-7-1](https://www.faa.gov/documentLibrary/media/Order/ATC.pdf)).
[Page 194](https://www.faa.gov/documentLibrary/media/Order/ATC.pdf) gives further information about the correct phraseology for conditional altitude instructions. According to this document, it would be:

> CLIMB/DESCEND TO REACH (altitude) AT (fix, waypoint)

I heard the above mentioned "DESCENT (altitude) BY (fix)" on actual radio, yet I can't find it in the document. What I can find is the following though:

> CROSS (fix, waypoint) AT (altitude).
> CROSS (fix, waypoint) AT OR ABOVE/BELOW (altitude)

I think[ this document ](https://www.faa.gov/documentLibrary/media/Order/ATC.pdf)(even though it consists of about 700 pages) can give a good reference for future phraseology questions and other questions, as I've found the 15° Rule @erikquinn mentioned in another thread explained in detail there as well!

**Comment by tedrek** [comment]
until/cross/depart makes perfect sense to me. The expected syntax at this point would be `cross wammy altitude 8000` or shortened `cross wammy a 8`.  Supporting an altitude range could be done using `at or [above|below]` but I doubt it will be used frequently enough (especially given length) to justify.

We seem to all be in agreement about altitude/speed restrictions in regards to future waypoints, an unqualified restriction should override all future restrictions until modified.  The one addition is it would be convenient if the restriction could be canceled and the assigned future ones would be used again.

There isn't currently a user exposed concept of arrivals so I'd prefer not to refer to them by name as in `altitude via bayview`.  Instead how about `[climb|descend|altitude] [charted|discretion]` and the related `speed [charted|discretion]`, currently both charted and discretion would do the same thing.

**Comment by erikquinn** [comment]
@Maverick283 Yup, that's where all the good stuff comes from, the "7110.65". We also call it our "bible", as it is the singular document that defines all of the rules for FAA air traffic controllers. It's long, yes, but covers absolutely everything.

@tedrek If the length is an issue, maybe shortkeys would come in handy (assuming #311 gets merged)? Then some commonly used notations could be applied such as "X" for cross, "/" for until, "@" for at. They are used in strip notation, like "**X**TEZLA↥50" (**cross** TEZLA intersection at or above 5k), "CFR**/**1530" (call-for-release programs in effect **until** 1530 zulu), "XTEZLA**@**45" (cross TEZLA intersection **at** 4,500'). It wouldn't be as intuitive, but it would be faster, and may be worth providing as an additioonal option... not yet sure whether I like it, but it is an option to do it like "XWAMMY@8" or "XWAMMY@8+".

And personally, I think I actually _would_ prefer `altitude via bayview` over `altitude via charted`. Only issue for me would be knowing which STAR/SID they were using. To that point, if we could maybe show the flight plan in the strip, then we could see the sid/star they wanted to use, and then it wouldn't be an issue, and we could have the more realistic behavior of telling them to climb/descend in accordance with a specific SID or STAR.
![untitled_sm](https://cloud.githubusercontent.com/assets/5103735/12080567/b39a4768-b22c-11e5-9ea7-31e08755eab4.png)

**Comment by tedrek** [comment]
@erikquinn, #311 has been merged.

The length comment was contrasting the phrase `cross wammy altitude 8000` with `cross wammy altitude at or above 8000`.  My suspicion is that very few players would type `at or above` instead being content with specifying the exact altitude.  The solution I jumped to was the same as you did, make the second phrase be `cross wammy altitude 8000+`,  in other words suffix the number with a `+` for at or above and a `-` for at or below.  From a parsing perspective `@` isn't needed in any of the above examples, what about inputting `cross wammy altitude at or above 8000` as `xwammy a@+8`?

I have been assuming short keys would be implemented in addition to the full length command names. `x` for cross and `/` for until make sense, does `\` for depart/after make sense?

I would prefer implementing `altitude via charted` as the simpler exercise when coding.  There is no reason not to extend it to `altitude via bayview` later once the basic framework is there to justify the re-work of airports and UI required for it.

**Comment by erikquinn** [comment]
@tedrek Gotcha. The suggestion for '@' was meant as a modifier for 'at/below' vs 'at' vs 'at/above' with regards to altitudes. Sidebar:
- 'Until' is almost exclusively used with speeds
- 'Cross' is almost exclusively used with altitudes
- 'Depart' is almost exclusively used with headings

^ Somewhat convenient, actually...

Thus, I was actually suggesting not `xwammy a@8`, but rather `xwammy@8`, as 'cross' is usually just about altitudes, and it wouldn't be crazy to omit the fact that you're referencing altitude in particular. Also sometimes it can be an altitude with a speed, in which case maybe `xwammy@8s250`, though that is rather ugly at that point. I dunno.

`x` makes sense for 'cross'. `/` makes sense for 'until', although it makes more sense as a suffix to than a prefix to instructions, eg `speed 190 /FINKA`. I don't know what would make sense for depart-- I am not aware of any flight strip notation for it, and `\` would work just as good as anything else, though it may be confusing because it's close to the forward slash.... maybe `d` instead? There's a lot of ways to go, and I'm not sure what is best to be honest.

And fair enough on the last part... works for me!

**Comment by erikquinn** [comment]
A marginally related thought: It is seeming more and more like the way we deal with parsing the instructions may need to evolve, with so many instances of different numbers of spaces for different commands that take different numbers of arguments. It will get pretty unwieldy to find what goes with which in something like `fix jelmi berra jan` vs `cross berra altitude 11 speed 250` vs `t 270` vs `t l 270` vs `takeoff`... at some point it may be easier and more effective to read through the whole input string and mark where each new command begins, and pass all the following arguments to that function instead of having super complex logic that determines how to split up the input string piece by piece before it knows what the next piece is. That was the one thing that gave me the most trouble and was the most prone to leaving bugs behind when it came to the changes to aircraft.js in PR #311. Sooooo many edge cases there...

**Comment by sixeyeco** [comment]
@tedrek 

> Right now, the system supports setting an altitude and speed until a given waypoint followed by a different altitude and speed until the next waypoint.

How do I accomplish that? I would like to be able to issue a command that would do this: 
c 4 f cedes frely c 3 f archi c 2 f wetor wesla

Is that possible?

**Comment by tedrek** [comment]
@sixeyeco, it's not yet accessible as a command, it's only accessible right now from the airport file when creating arrivals.  This issue is discussing how best to expose the functionality to the player and the details of how it should work.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
