### ISSUE TITLE
Hidden fixes disappeared

### ISSUE THREAD

**Issue by culebron** [zlsa/atc#316]
Hi, guys,
has someone removed hidden fixes and changed UUDD airport? They were very useful, but in the recent near-christmas revision, I see they're gone after some merges. Was that intentional?

**Comment by tedrek** [comment]
@culebron, I am not aware of any intentional change which would break hidden fixes.

UUDD appears to have hidden fixes still in the file: [https://github.com/zlsa/atc/blame/gh-pages/assets/airports/uudd.json].  I don't see any merges which should have touched UUDD in the last month.  The last two commits I see which touched the airport are '755d47f991dc10' by myself and '1dbcf2b00fc7327' by you.  What behaviour are you seeing?

**Comment by culebron** [comment]
@tedrek I see. These fixes were intended to be used later, for arrival transitions. There were others, which were used in SIDs, and they were deleted.

**Comment by culebron** [comment]
wow. I can't find where these fixes were added at all. Did I make the pull request?

**Comment by tedrek** [comment]
It looks to me like you didn't include the UUDD fixes in the pull request you did make.  #265 created the virtual fixes, but it happened the day before you made this commit:
https://github.com/culebron/atc/commit/c994b6052146ffb7b39101d9c0a97d6f62ed0538#diff-4c242ac753441fd8c389e899babd8c0b

I'm going to guess there's another pull request in the making?

**Comment by culebron** [comment]
I guess I made one but pulled it only locally. Still I have doubts, it seemed that it was deployed in zlsa.github.io. I'll make a pull request for this.
