### ISSUE TITLE
Different keyboard layouts

### ISSUE THREAD

**Issue by Maverick283** [zlsa/atc#336]
#330 brought to attention that clearing an aircraft for an ILS approach using "*" did not work.

@erikquinn soon found out it might be because of users using a different keyboard layout then the QWERTY Layout. 

Since the key-code is used rather then the symbol that has been pressed, the different layouts lead to confusion. In this example, on a QWERTZ Keyboard you need to press [Shift] AND [+(not Numpad)] to get a "*" symbol. This key has the code 187, making it [shift + code 187] which is mapped to zooming in. 

So there are a couple solutions that come to my mind:
- 1. Detect the symbol on the key pressed rather then the key code
- 2. Detect the keyboard layout and change the mapping accordingly for each user
- 3. Make an option where the user can adjust his keyboard layout

None of the above are perfect, here is why:
- 1. Apparently Chrome has an issue detecting the symbols (though there got to be some proper way). More about that can be found [here](http://stackoverflow.com/questions/8892238/detect-keyboard-layout-with-javascript/12825956#12825956) 
- 2. Since there is no proper standard for QWERTZ/QWERTY/AZERTY and so on Layouts, it is hard to properly detect the layout of a keyboard. (Yes, there are actually ISO standards, yet they are not necessarily applied!). Also, what happens if two keyboards (potentially with different layouts) are connected? Which one is used?
- 3. Gives another option... The only neat way to add that is to add translations as suggested in #232. Yet this would again only give an approximation of where keys are. Most German speaking users use the QWERTZ Layout, but the common layout in america (QWERTY - ANSI) is different to the one in great Britain (QWERTY - ISO mechanical), yet both speak the same language.  

Note: The same issues will appear if the symbols from #315 are implemented.

Any thoughts, ideas?

**Comment by tedrek** [comment]
The fourth option is to overhaul the command parser so it can take a string of relevant symbols directly.  Specifically, so it can take commands which are not space separated.

Option 1's issues with chrome can be worked around fairly easy and is likely the simplest approach.

Option 2 probably won't work well because it needs some server side intelligence to assist in the guessing and even then it doesn't have enough information.

Option 3 would consist of choosing the keyboard layout specifically.  There would also be a likely language choice, but the layout and language are not tied directly together and can't be for the reasons you mentioned.

My preference would be to avoid including keyboard layouts and instead focus acting based on the symbol entered.  For some layouts, I think there would be a good argument to be made for accepting some localized synonyms where the key used under US-ANSI isn't easily present on the keyboard.

**Comment by Maverick283** [comment]
Getting rid of the space would help a lot i think. Of course, some kind of separator is still needed for fix assigning, but the command "LH283 h180c5" should do.

I don't know much about the chrome issue, it just seemed hard to me, but hey... If it works, it works :D

**Comment by tedrek** [comment]
For reference, http://codeflow.org/entries/2013/jan/30/keyboard-events-in-javascript-are-broken/ 

Handling of key-press events in javascript appears to be horribly broken :disappointed:.

**Comment by erikquinn** [comment]
So crazy that we 21st century humans can make space rockets that [land themselves](http://www.scientificamerican.com/article/spacex-to-attempt-another-rocket-landing-sunday/), and yet we can't make javascript properly deal with multiple keyboard layouts...

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
