### ISSUE TITLE
No points deducted for separation violations

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#345]
I noticed this during a game at SFO. I happened to be recording it so I marked it up and posted it. 

[First video](https://www.youtube.com/watch?v=4ADLmAYjozQ)

Then I decided to record egregious violations in order to verify and document it. What I actually came up with was quite surprising. 

[Second video](https://www.youtube.com/watch?v=3kUh67oIfe8)

It appears that there are issues with deducting points for separation violations. This isn't as it's supposed to be, is it?

**Comment by Maverick283** [comment]
Have you tried the same thing after you actually gained some points?

**Comment by sixeyeco** [comment]
@Maverick283 Yes. That's shown in the first video, although those craft were on arrival. Here's another video reproducing the issue with points already on the board and then subsequent separation violations for departures.

[Video of issue occurring with points already on the board](https://www.youtube.com/watch?v=-uki2KwftZ4)

**Comment by sixeyeco** [comment]
This video shows two departing craft directed to the same place at nearly the same time with only 200 feet vertical separation. No warning or penalty. 

Is it possible that recent changes that were designed to allow parallel takeoffs removed the possibility of being penalizing at all on takeoff?

https://www.youtube.com/watch?v=mh_MzNgQXYE

**Comment by erikquinn** [comment]
![](http://i.imgur.com/VmW5xiWh.jpg)

Greetings from Terminal A in the single busiest airport on planet earth: Atlanta-Heartsfield! :smiley:

I had a look at the second video and can explain. Recently, the separation logic was expanded upon, and one of the changes was to reflect a paragraph in the 7110.65 regarding diverging headings with simultaneous takeoffs, and it says that they must be established on those diverging headings "within one minute of takeoff". That's why they are invincible briefly after takeoff. 

Obviously, the video you showed would have to be a violation somehow. This 1min invincibility isn't intended to be permanent, as there are other layers of rules for the tower (the 1 minute more applies to a radar facility releasing departures off of uncontrolled fields), its just that adding that 60s invincibility period was a quick fix to parallel departures always generating a conflict when that is totally legal. 

Also, as for the points: I have no clue. As for the second video, it is working correctly, according to section 5-5-7 in the 7110, " Passing or Diverging". The examples in the video are actually considered to have positive separation.

**Comment by sixeyeco** [comment]
@erikquinn 

> ...adding that 60s invincibility period was a quick fix to parallel departures always generating a conflict when that is totally legal.

That's what I imagined. It certainly makes sense to allow legal parallel departures. 

> As for the second video, it is working correctly, according to section 5-5-7 in the 7110, " Passing or Diverging". The examples in the video are actually considered to have positive separation.

Okay, I understand the code is giving them some time to get off the ground but I simply can't grasp how the second video reflects two craft with positive separation. That's as near of a miss as I've ever seen; two commercial jets flying in the same space, at the same time with only 200 feet vertical separation? 

As far as the game goes, I'm going to start incorporating that into my game play. I've been waiting entirely too long to clear them for takeoff. As far as IRL, I'm never flying again!

Regardless, by referring to it as a quick fix you guys appear to already be on top of it. 

Thanks!

**Comment by erikquinn** [comment]
@sixeyeco 

> > As for the second video, it is working correctly, according to section 5-5-7 in the 7110, " Passing or Diverging". The examples in the video are actually considered to have positive separation.
> 
> Okay, I understand the code is giving them some time to get off the ground but I simply can't grasp how the second video reflects two craft with positive separation. That's as near of a miss as I've ever seen; two commercial jets flying in the same space, at the same time with only 200 feet vertical separation?

I feel that, but yes: in the terminal environment, as long as two aircraft are assigned headings that diverge by 15 degrees or more, and either aircraft has passed the projected path of the other, they are considered to be separated, as a collision is no longer possible. Now the way you fishtailed the one plane behind the other... yes, that would be rather "egregious"... after all, standard radar separation must be maintained until the conditions for passing/diverging are met. So a loss of separation IS recorded when they fly next to each other, and when put on diverging headings, that loss is resolved. 

But this type of separation is much more likely to be used as a way to discontinue vertical separation earlier than normal, eg 2 a/c are on crossing paths, one @5k ft who needs desperately to climb out of icing and the other @6k ft who needs to descend toward the airport: once either airplane passes the others projected track, the targets are considered diverging and ATC could allow those pilots to climb/descend through each others altitudes, because even if they are separated by 2.65nm at that point, they are only getting farther away from each other anyway.

I'll say this though: it makes me really nervous to apply this paragraph! I would definitely prefer to use visual separation instead if visibility permits.

**Comment by sixeyeco** [comment]
> I'll say this though: it makes me really nervous to apply this paragraph! I would definitely prefer to use visual separation instead if visibility permits.

It sounds like you're actually a pilot or a controller? Nice. I have no actual flying nor controller experience and I'm sure that's the reason that I just can't get it. I wrote a long reply but erased it as I was digressing from the purpose of this arena. This is not the place for me learn the rules of flying (despite being quite interested). I also don't want to take up your valuable time.  

One of the most appealing aspects of this game (and others like it) is how much focus it requires. A big part of the challenge of the game is exhibiting effective time management skills (get departing flights out as quickly as possible while safely and efficiently landing others). To realize that I could actually make two planes collide and not incur as much as a warning is both discouraging and tempting. I can now clear them a lot easier knowing that as long as they don't collide I'm free to direct them without fear of any penalty whatsoever. 

[Short video of crash shortly after takeoff that doesn't even incur a penalty.](https://www.youtube.com/watch?v=pAAUlmOjMsc)

The commitment and incredible work involved in making this game as real as possible is laudable. But the invincibility that was designed to allow legal, concurrent takeoffs on parallel runways, also allows (if not encourages) play that should clearly be considered a violation.  

Would it be a quick fix to establish additional criterion for invincibility? Say, approved takeoff vectoring for each runway? E.g. Assuming that runways 28L and 28R are oriented at 284° then :
- craft departing 28R at SFO vectored to greater than 284° but less than 103°
  or 
- craft departing 28L at SFO vectored to less than 284° but greater than 105°

...would be invincible for a predetermined time. 

<i>The reason for the 103° and 105° is so that craft on 28R won't turn left, and vice versa. </i>

If a flight departs 28R and is granted invincibility then any turn toward the left would immediately incur warning circles. If the flight crosses an imaginary center line between runways then the red violation circles appear and a penalty is assessed. Once the flights have achieved regular minimum separation then normal rules would apply. 

By the way, a "minimum horizontal separation" circle that appears any time a flight is selected would be hugely beneficial.

**Comment by erikquinn** [comment]
@sixeyeco I currently am neither controller nor pilot, though I am an aspiring air traffic controller. The application process is complex and lengthy, so in the meantime I work at an aviation software company (not much coding though) and instruct in and oversee all of the air traffic control lab courses at the university where I graduated from (Kent State). Also, I have worked a lot with the software company that created the ATC simulation software we use in that lab... and I'll say it again: _this_ sim isn't far off from being an equal training tool to the software my university paid millions for. So I have many people around here to thank for that, and I fully intend to recommend this sim to all of my TRACON students for practice, since its so great. So definitely kudos to Jon and all who contribute here. It's an honor for me to be involved.

So though I'm mostly a self-trained JavaScript junkie, I can bring to this community thousands of hours of my own training time on the simulators, hundreds of hours of teaching ATC, and the expertise of countless current and retired controllers that I either work with or know personally, which I am happy to do. :smile:

So anyway, as to the quote-- it was in relation to the simulations I have run in my training; none of which was with real airplanes. But one day soon....... :smiley:
