### ISSUE TITLE
 Manual handoff of departing aircrafts

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#358]
I like to suggest an alternate end for departing airplanes. 
First of all i don´t see the sense in keeping flight-strips in the rack which are - by actual procedures - not under my control, e.g. above FL100 or out of 80 miles. 
Secondly the real-live-procedure for this is to handoff to the next ATC-Center. 
So in zlsa-atc it would mean, if an aircraft is near his exit point or FL-level you have to hand it off. 
This could look like: "DHL486 ho" with the radio-response "Lufthansa four eight six, contact xxxx-control, good bye!"

**Comment by erikquinn** [comment]
:smiley: This would be awesome!

**Comment by sixeyeco** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by tedrek** [comment]
Flight strips are not currently displayed for aircraft outside of the control range (50 miles/0-10,000 feet).  When we implemented that change the consensus at the time was a manual hand-off didn't add much to the game.  With SIDs I often give departures two total commands and ignore them after takeoff so requiring a hand-off seems like a better thing to me now.

A manual hand-off shouldn't be too hard to implement, how accurate would it need to be?  Within 10 miles of it's departure location?

**Comment by erikquinn** [comment]
Really, it would be irrespective of position-- eg. as soon as the aircraft is definitely separated from all other traffic, and given a climb to the airspace ceiling, and cleared onto their route, we can hand them off to center. For example, it's not that uncommon for departure control to tell an aircraft to contact center when they're passing through around 4,000 feet, even if the airspace ceiling is 10,000+.

**Comment by Maverick283** [comment]
Yeah, I once took of with tower control, was told to switch to my departure frequency at 1000ft, said "Jacksonville Departure, N149FA with you" and heard "N149FA Jack Departure, switch to Center 126.350" and there I was, with Center at 1500ft... 

This proves @erikquinn s point, it seems like there really is no limit (altitude wise). 

But what if (in game) I tell an aircraft to switch to center but then get it into a conflict? This should get extra points deducted (like 3x normal conflict deduction) so that one will carefully avoid doing it!

**Comment by harp71** [comment]
I think for sim-purposes there should be a limitation for hand-off, either
height or distance to the airport.

2016-01-27 10:05 GMT+01:00 Maverick notifications@github.com:

**Comment by erikquinn** [comment]
@harp71 I'm curious, why do you want a limitation?

**Comment by harp71** [comment]
@erikquinn i think it would be to easy if you have none: so it would be taxi, takeoff, hand-off. It takes a little bit out of the experience, i think. The above mentioned example with hand-off at 1500 feet is not the usual way it´s gonna go probably. So if you can hand-off right after takeoff there is no challenge, other then maybe routing all other planes i have control of around that one i don´t.
After all were trying to create a game with certain obstacles. And if you taxi, takeoff, hand-off you don´t have to have a second thought about that aircraft and that makes it to easy in my opinion. On the other hand, if you taxi, takeoff and have to wait and keep that departure in mind for the hand-off it´s more challenging.

**Comment by erikquinn** [comment]
@harp71 Okay, I see where you're coming from. I would contend, however, that a controller's choice to hand off _all of their airplanes_ to center so soon after takeoff is risky and unwise, rather than easy.

After all, once it's handed off, we wouldn't be able to change anything about what it's doing. So if I'm pumping out departures and handing them off immediately, and there's two of them on the same SID at different speeds, after carelessly handing them off without paying attention, I would be forced to watch as the two airplanes I can no longer control get closer and closer, until they lose separation, _or maybe even_ collide. And that would be written into the code that _WE_ would lose points for handing aircraft to center that aren't "5 miles, constant or increasing".

I see why you say it's more challenging to be forced to keep the airplane longer, but from my perspective, I can't see what it really adds to the experience. If I have no arrivals yet, and my first departure is an F18 or something (climb rate of maybe 15,000fpm), I see no reason not to be able to hand them off to center very quickly if I so choose; it's just that I would have to have the foresight to know that I am prepared for and okay with any of the consequences that come with that choice.

**Comment by harp71** [comment]
@erikquinn with you an all but one thing: the handed-off planes would not crash in reality for many reasons, so that should be avoided. And who "simulates" the next controller after hand-off? Aircraft not under my control are still under another ATCs control and should do something, at least not fly into each other. As long as i see them they should act as if under intelligent control, in the cockpit and regarding the higher ATC.

**Comment by erikquinn** [comment]
@harp71 True, they would be separated by center, who would fix it before they ever actually did collide. And you've found the problem with trying to make that happen:

> And who "simulates" the next controller after hand-off?

Nobody. And it might be kind of tough to make a virtual center controller have enough intelligence to actually recognize the conflict and do something about it.

> As long as i see them they should act as if under intelligent control, in the cockpit and regarding the higher ATC.

This is the goal, but may be tough to implement.

---

If there's a general consensus that it's not worth adding handoffs until we can have computerized controllers that can do stuff, then maybe this can be put on hold until then. Thoughts?

**Comment by harp71** [comment]
@erikquinn That´s the problem exactly. That´s why i suggested a hand-off limit relating to height or distance from airport, so you can´t do it right away and the aircraft presents a problem to the whole airspace. But first i think we have to address the climb rates, because any given aircraft has at least be able to climb out to 10000 feet in time. See #339

**Comment by erikquinn** [comment]
@harp71 Climb performance as mentioned in #339 is addressed in PR #356.

---

> [...] a hand-off limit relating to height or distance from airport [...]

^ ... is just an idea I fundamentally disagree with. As I see it, since real controllers have to deal with the potential consequences of handing off right away, I don't see why it shouldn't be the same for us. Doing so _should_ "present a problem to the whole airspace", and after a few times, controllers would surely learn not to hand off so early. But implementing a restriction where I'm not even allowed to give an early handoff would confuse and annoy me as a user, since it would be my right to make that decision in real life. Even if it's a mistake to hand off right away, it would be my mistake to make.

**Comment by harp71** [comment]
@erikquinn sure! As i said: it was just a "work-around" because of the lack of a center controller, who will the aircraft tell what to do.

**Comment by harp71** [comment]
> @harp71 Climb performance as mentioned in #339 is addressed in PR #356.

I know, i just can´t wait to see it happen :)

As mentioned a long time ago: i´m not fit in the most things you guys do with javascript etc. I´m just HTML/CSS, a little javascript and i understand the purpose and structure of a json-file. So if you need a foot-soldier for adaptions of the JSONs in the aircraft-folder, i offer my assistance gladly ... i might not have the knowledge but a text-editor ;)

**Comment by sixeyeco** [comment]
Just a thought, but the net effect we want is to free up rack space, right? Could we just add an "x" on the strip to remove it? Again, leave it up to the player to decide if he's done with it since that's effectively how it would be IRL.

It wouldn't bother me a bit if the craft remained on the radar. You could even keep the craft clickable to get it back on the rack. It's not really handing it off, it just brings about the desired result without what I assume would be a heavy code rewrite. 

Only strips that have taken off would have the "x".  

![image](https://cloud.githubusercontent.com/assets/179496/12657519/7efa57a6-c5b8-11e5-8fb4-410c7c8b59d7.png)

**Comment by harp71** [comment]
@sixeyeco i think, the strips should remain until the aircraft is under your control and just freeing up rack space is not the primary goal of the hand-off.

@erikquinn i think we have to consider (i thought about this morning while watching some cockpit videos), that we do a multiple ATC-job here. We manage ground (taxi), tower (take-off clearance and initial climb) and approach (climb-out off immediate  airport region)! So i can see how tower hands-off at 1500 feet to approach on departing airplanes, but approach would not hand-off to center at that height.

**Comment by erikquinn** [comment]
@harp71 right, that's what makes it tough; it would be nice if we could just focus on one discipline at a time, eg. I do NOT want to have to deal with SIDs and takeoff clearances when I'm vectoring arrivals because its the jobs of approach and tower, and it feels weird to do both. But that's another topic for another day I suppose...

And realistically the tower hands off to departure around the time they cross the departure end of the runway on climb out. And then departure will switch them to center as early as the next 5 miles (2min) or as late as the next 20 miles if there's some reason they need to keep control. Also, regardless of location, departure will hand off to center as the aircraft vets within about 2,000 feet of the top of departure's airspace, so that center can give the aircraft a clearance to a higher altitude to avoid making them level off at the ceiling of the TRACON's airspace.

It may be hard to believe, but I can definitely say with 100% confidence that handoffs from departure to center can and do happen within a few miles of the airport, at altitudes as low as +2,000 feet.

**Comment by harp71** [comment]
@erikquinn that all would depend on the airport-size, too. 
I listened to some liveatc.net in combination with flightradar24.com. At JFK tower hand-off to departure is right after takeoff at about 1500-2000 feet. Departure hand-off to center is between 6000-8000 feet. On less frequented airports it´s all a little later. With usual climb-rates right from take-off of 3500 ft/min i doubt very much, that there is a hand-off from tower to departure to center within 2000ft!

Nevertheless in our simulation ...
1. we have still climb-rates that are way off reality. In a radius of 80 nm EVERY jet-engine plane is near cruise altitude, or at least FL200 or above, not barely at FL100.
2. we have to do multiple jobs, otherwise the whole concept would have to change. There is no one controller anywhere for this kind of area we simulate here.

After all it´s just a game :) and anyones effort to make it more realistic may be ill advised. 

So, no regulations for hand-off regarding minimum altitude or distance from airport is fine with me. Main thing is to have the function itself implemented.

**Comment by erikquinn** [comment]
@harp71  liveatc and flightradar24: my favorite combination! :wink: Those figures sound right, and normal, my point was only that they _could_ hand off aircraft within the first few minutes, and for example, an underpowered GA aircraft could be low and close to the airport, and still get handed off to center and I wouldn't want the sim to prevent it. But you are absolutely right that it's much more often somewhere around halfway to two-thirds of the way up through the vertical limits that they are handed off, rather than crazy soon after takeoff.

I too am looking forward to the day when this is implemented. I'm starting to really like this game, almost too much! :stuck_out_tongue: 

(Edited tag. Oops!)

**Comment by harp71** [comment]
@erikquinn  Let´s do it then ... by which i mean you have to do it :bowtie:

**Comment by harp71** [comment]
With new updates (dynamic climb rate etc.) it seems you can´t assign an altitude over 10000 now. In consequence departing aircrafts are now flying more than half the way from take off to there destination on FL100.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
