### ISSUE TITLE
Multiplayer mode (suggestion)

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#359]
This would surely have to be a back burner project but how fun it would be to have a multi player mode? In addition to the role that we all know in ATC would be something like:
- En Route
- Approach
- Ground(?)
- Departures

...or something like that. Each controller would have a different radar depending on their role. They guide their flights through their airspace and pass them off to another controller. The players could collaborate in real time using Ventrillo or Teamspeak.   

![multiplayer-mode](https://cloud.githubusercontent.com/assets/179496/12590762/6467448a-c419-11e5-8687-2f22799de803.png)

Regarding ground control, perhaps the existing code could be altered enough to make this feasible. 

![multiplayer-mode-ground](https://cloud.githubusercontent.com/assets/179496/12591348/353c8cb2-c41c-11e5-9367-58a767295eec.png)

**Comment by erikquinn** [comment]
Man after my own heart.... haha

This has been similar to my vision ever since I came across this sim. Being able to choose between Tower/TRACON/Center has been "on my radar", so to speak, for a while now. And for the excellent radar sim that this already is, I would actually much rather see the en route option added first, before any tower stuff. The interwebs are seriously lacking a good en route simulator, which can be more abstract, but VERY satisfying, the same way as building a perfectly spaced arrival stream. Plus, an en route mode would be much less of a rework than a tower cab mode.

This is very long-term stuff, though. I'm excited for whenever the day comes!

**Comment by Maverick283** [comment]
This.would.be.amazing!!!

I`ve been wanting to suggest this but never have as I can imagine what huge amount of work it would be, and with my lack of JS knowledge I would not have been able to contribute anything to it.

I'd love to see this though!

**Comment by harp71** [comment]
Certainly would be nice. in Flightsim, X-Plane for instance, there is a
world wide community with real radio ATC if you care to join, which i
didn´t. I think this would be a whole lot of work ...

2016-01-27 9:56 GMT+01:00 Maverick notifications@github.com:

**Comment by Maverick283** [comment]
There are two major ones actually, one is called IVAO and the other one VATSIM. For anyone who is interested :D

Yet traffic there is usually low and it is not as challenging as it could be with a simulator!

**Comment by erikquinn** [comment]
One of VATSIM's terminal radar clients ([vSTARS](http://vstars.metacraft.com/)) is literally a **pixel-for-pixel** look-a-like of the real FAA STARS radar system. It's truly an amazing piece of software, and the feature set is ridiculously expansive.

If you want to know what the real thing looks like (at STARS-equipped FAA facilities), it looks exactly like vSTARS. And if you want to know what the center equivalent is, look no further than Ross's other program, [vERAM](http://veram.metacraft.com/). Despite the lack of traffic for radar junkies like me, VATSIM is a really cool place.

**Comment by sixeyeco** [comment]
I'm looking forward to the day...

I close the issue to keep things uncluttered.
