### ISSUE TITLE
Visual Designs / Skins

### ISSUE THREAD

**Issue by harp71** [zlsa/atc#371]
At the end of the now closed #340 @sixeyeco and i discussed his changed visual design on his fork. As you can see on http://sixeyeco.github.io/atc/ it´s darker and ... me like very much :+1: 

I think the changes are "just" CSS (@sixeyeco?). Would it be difficult to add an option here:
![image](https://cloud.githubusercontent.com/assets/11310456/12678762/be1fd7e2-c6a0-11e5-9c21-ae91cfa3f705.png)
... for change of design/skin and just add a corresponding skin-xxx.css to the code for the changes ?

**Comment by sixeyeco** [comment]
:+1:  @harp71  Sorry, I posted on https://github.com/zlsa/atc/issues/340 using "Close and Comment" instead of just "Comment". I reopened it.

If it helps in this endeavor I already have main.css (dark radar) and strip.css (spacing, colors) for each of the seven configuration below. In addition to "classic" would be:
1. Dark Radar only
2. Dark Radar with tighter strip spacing
3. Dark Radar with full strip colors.
4. Dark Radar with tighter spacing, full colors.
5. Classic Radar with tighter strip spacing
6. Classic Radar with full strip colors.
7. Classic Radar with tighter spacing, full colors.

Also, I have an aircraft.js that spawns all new strips at the top of the rack. 

Currently on my fork is <b>[Dark radar, added right strip border, new strips spawn at the top.](sixeyeco.github.io/atc/)</del>

**Comment by MaicomMR** [comment]
I like the loading screen, but the game it seems too dark to me, i like more the option to change the background color following the player preference. #395

**Comment by erikquinn** [comment]
¿Porque no los dos? :smile: I understand where you're coming from @MaicomMR, so maybe we could do a drop-down between many different styles, and also be able to scale the overall brightness separately. Then you could use his nice theme, but brighten it up a little. It's a compromise, of course, but I don't think giving users complete control over the background color is the best idea, because they could make it pink or yellow or orange or something totally hideous. I think we could just adjust overall brightness and that would address the reason behind #395. How does that sound to you?

**Comment by sixeyeco** [comment]
I had this mockup in my hopper from a while back. I edited to include the colors suggested in https://github.com/zlsa/atc/issues/395. Ideally, any solution that's implemented would show the changes live in the background. 
![screencolors2](https://cloud.githubusercontent.com/assets/179496/13151760/7516fcbc-d620-11e5-87c8-19484f1292e8.png)

**Comment by harp71** [comment]
@sixeyeco this would be a nice one for the time being. I still think it would be nice to have a selection for different skins. Like i said, this only requires to add an additional CSS-File on selection.

**Comment by engeplabs** [comment]
I once read about CSS variables. Thes are good for making templates as you just have to change a value (for instance the base color) in the css and every attribute using this value will change its color. If we could modify this variavle via javascript we could even build a dynamic color selector!

**Comment by engeplabs** [comment]
Unfortunately this is not supported very well by current browsers. (Atm it's just FF48 and Chrome 49 Beta)

**Comment by harp71** [comment]
@patitoxd you´ll need no fancy stuff, just an additional <skinname>.css loaded after the standard CSSs.

**Comment by MaicomMR** [comment]
@erikquinn sounds good for me, I select only 3 colors from real traffic computers screens, the idea is maintain real but give to the player to select your preference.

@sixeyeco Very cool mockup, really good! :+1:

**Comment by erikquinn** [comment]
yeah @harp71 is right. It shouldn't be too hard, maybe just add a `skins` folder within `style`, and subfolders for each skin that contain the css elements that are to be changed, while it inherits the rest from the "classic" skin. This isn't my area though, so I don't know if/how this could be done easily.

**Comment by sixeyeco** [comment]
I have a [color changer in place](http://sixeyeco.github.io/atc/index2-bkcolor.html). I'm not a js guy so I can't get it in the settings menu. Though it looks horrible and it broke the game it shows how light this implementation could be. I'll try to get a drop down menu to change css sheets but don't count on me to get it right, and certainly not fast. :)  

~ Commented out:  `background-color: #354;` from main.css
~ Added: assets/style/main-bkcolor.css
~ Included: `<link rel="stylesheet" href="assets/style/main-bkcolor.css" />` in "index.html"

**Comment by sixeyeco** [comment]
I can see quite a few color changes that would be nice to add to the skins. The background color in main.css has no effect on the loading screen (loading.css) and airport selection dialog (airport.css). Not to mention all of the other menu borders, data blocks etc.  

How would we eliminate these individual color references so that they could be combined in a single css?

**Comment by harp71** [comment]
@sixeyeco i´m not exactly sure what the problem is, but as i said you load the skin.css last in line and do the changes there! Are you familiar with the hierarchy in CSS, otherwise known as "Cascading"? This is a rather complex thing, but easy to say: if you have 10 CSS-files, and in the first 9 there is some background-color defined, you can change it in the 10th CSS. There are rules to follow for it to work, but in theory there is not so much you can´t change in the last loaded CSS-file. For further reference take a look here: https://www.w3.org/TR/CSS2/cascade.html

**Comment by engeplabs** [comment]
@harp71 due to harp's comment I made a small implementation of the color changer. you can watch it here :point_right: [http://patitoxd.github.io/atc/styleOverride/](http://patitoxd.github.io/atc/styleOverride/)
It's pretty straight forward based on the explanation harp gave in the comment above.
I made sure, that the old html nodes are removed after the new one got loaded. Like this the html doesn't get messed up.
One thing remains: you may want to redo the js a bit so it uses jQuery as my example is plain JavaScript.

@sixeyeco The slider in your mockup.. is it MetroUI again? :)

**Comment by engeplabs** [comment]
@sixeyeco the problems you described may only be solved by having all rules concerning the color in a single "theme.css" or split all the files so that normal styling is defined in on file and the colors in different files with the same name but in a "theme" folder. See the illustration below:

Option 1

```
root/assets/style
 |_ airport.css // containing only style information and static colors
 |_ main.css
 |_ ...
 |_ theme-1.css //containing all template specific colors
 |_ theme-2.css
 |_ theme-3.css
```

Option 2

```
root/assets/style
 |_ airport.css // containing only style information and static colors
 |_ main.css
 |_ ...
 |_ theme-1 // folder containing the css files with the colors of the theme
      |_airport.css // containing only theme colors concerning the airport selection mask
      |_ ...
 |_ theme-2
      |_ ...
 |_ theme-3
      |_ ...
```

**Comment by headphase** [comment]
@sixeyeco any update on the progress with this color changer?  I would love to help test/refine if you need; it looks great on your fork.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
