### ISSUE TITLE
Scaling Traffic Volume

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#374]
Creating to continue a conversation from #306.

I propose to add sliders that can be used to control the amount of traffic inbound over the various arrival fixes, as well as departures, on the fly. The user can simply adjust the sliders to achieve the traffic volume _and_ flow that they want (eg. heavy over one fix, light over the others, etc).

This would really add some variety, and would give people the option to practice working just arrivals, or just departures, etc, and generally put them more in control of how they want to play.

**Comment by erikquinn** [comment]
@sixeyeco In response to your comment on the other issue (306):

I was picturing something more... simplified. I undersand there are multiple 'schedules' that define the traffic distribution, as well as airports having different numbers of radials, etc. Here's what I was thinking, in more detail:

`[airport].arrivals` is already an array that contains 'n' number of objects, typically, one for each arrival stream. So, I'm saying we would have a global slider for "arrivals" and a global slider for departures. Each of those could be expanded with a little arrow, revealing sub-sliders that allow you to specify the rate for each stream of a given airport, in case the user wants to get that specific. If not, the sub-sliders will just default to whatever is set in the `[airport].json`, and will be scaled up and down based on the global sliders. As for the 'random' vs 'cyclic' vs whatever else, I can't see that making a huge difference; I'd just leave it as it is set in the json.

I am no good with CSS or html; I'm only useful in js, python (and marginal in c++), so I do appreciate the help offer with all this. I don't want to assume, but it seems like it was very easy for you to mock up those sliders you linked to in issue 306-- when you get a chance, could you try to throw together a demo of the concept I described above? I think it would be really helpful for everybody to see it, and it would take me days (or weeks), _and_ it would look ugly because I have no taste. lol :laughing:

**Comment by sixeyeco** [comment]
Unfortunately, my experience with css and java is limited to hunt and wreck. Where I excel is taking someone else's work and screwing with it enough to make it look and function the way I want. I used [MetroUI](http://metroui.org.ua/) because of the features and because it has an MIT license.   

But I'd be happy to cobble together a working mockup of what you're describing if someone else can make it actually adjust the settings.

**Comment by erikquinn** [comment]
@sixeyeco That'd be great! I think I can cobble together the connections. I've learned a lot about that part from looking around the codebase so I think I can cover that part.

**Comment by sixeyeco** [comment]
@erikquinn  You got it. I'm happy to see this implemented. I tried to get a drop down arrow to reveal additional options but I ran into issues. I tried tabs instead and met with success. [Take a peek?](http://sixeyeco.github.io/atc/options-loader7.html)

**Comment by erikquinn** [comment]
@sixeyeco Oh yeah, that looks good! I do think getting them collapsible instead of tabs is worth some extra research, which led me to fiddle around with [this](http://jsfiddle.net/eK8X5/8774/). I tried to apply the same logic to the sliders you provided, but haven't had success yet, though I will try again later. Great work though, I'm liking where we're heading here.

**Comment by sixeyeco** [comment]
@erikquinn  Yeah, same thing here. Works awesome with text but as soon as I put some sliders in there it balks. I'll keep looking for a way to get it done. I have a few feelers out there.

**Comment by sixeyeco** [comment]
@erikquinn [Here's what I've been able to come up with](http://sixeyeco.github.io/atc/options-loader7b.html). 

[Here's the same one using an overlay](http://sixeyeco.github.io/atc/index2.html). Do you think you can work with this?

**Comment by engeplabs** [comment]
@erikquinn @sixeyeco what is the state of this issue? Also I would like to see your proposes for the sliders but the links are broken... :grin:

**Comment by erikquinn** [comment]
@patitoxd I backburnered it while I clean up some SID stuff. The concept is described above, and @sixeyeco had a really nice mockup of it... it would then just need to be hooked into `.arrivals` and `.departures` of the loaded airport with some js, and the game will change the spawn rates. Shouldn't actually be too complicated at all. You're welcome to take it over if you like?

@sixeyeco you probably just updated his branch recently and it removed the sliders. Hopefully you have them saved elsewhere somewhere? :worried:

**Comment by engeplabs** [comment]
@erikquinn Yes I really like the idea of it and will implement it. But it would be awesome to include the thougts and work (mockups) you two did for this issue.

@sixeyeco so... do you still have this stuff laying around somewhere? :grin:

**Comment by sixeyeco** [comment]
@erikquinn , @patitoxd, Sorry. I was away.  I'll get right on it!  :) 

> [Options](http://sixeyeco.github.io/atc/options-loader7b.html). 
> 
> [Options as a popup](http://sixeyeco.github.io/atc/index2.html).

Update: The links should be working. <i>Someday I gotta learn how to use Github.</i>

**Comment by erikquinn** [comment]
Thanks @sixeyeco :smile:

@patitoxd Interesting other idea that came to me-- why not base the slider values on a proportion of "real world acceptance rate" (as in the max. number of ac per hour an airport is able to accommodate)? eg. sliders go from 0% to 150%, based on that value. These properties can be added to the airport jsons:

```
  tfc_rates: {
    capacity: {arr: 60, dep: 100},
    typical: 51,
  }
```

...and then the sliders are set with 100% being at the "capacity" value, and scaled proportionally along the slider's range. When loading an airport, they would default to the "typical" value (in the above case, 85% arr and 51% dep). From there, users can go about making adjustments to the traffic if they like.

^ What do you think?

**Comment by engeplabs** [comment]
@sixeyeco @erikquinn This looks veeery sexy! (No really I love the design)
I preffer the popup option and would propose to put it into the line with all the other icons (if this isn't too much of a cluster fuck). Another option would be to insert these options into the ariport selection window. Which I like even more if I think about it...

_@erikquinn Yes this is a great idea! It may also make easier to configure. Because with this relative way of setting the amount of traffic you may even keep the settings when switching from EDDH to KJFK because this relative factor of the traffic to the normal value wouldn't change (I have no idea if this makes sence). So you are on a small airport with a challenging amount of traffic (like 3x of the normal value), you switch to a huge one and keep your settings but you don't get overrun because of the relative way you have set your amount of traffic (it's not 3x but maybe 1.5x the normal traffic)..._

_Ok.. You see, I can't explain this in words. I will do a visual explaination abut what I'm trying to say. xD But not know as I'm occupied with stuff from school. I will eventually edit this comment... I will be back! :sunglasses:_

Edit:
@erikquinn forget what i said above. I didn't fully understand your proposal and so I started to go crazy with "relative" values and stuff. I have one question concerning your solution: would you really like to have just one suggested value for arrivals and departures? I think we should use like a equal persentage of those two values e.g.

``` JavaScript
  tfc_rates: {
    capacity: {arr: 60, dep: 100},
    typical: 85, // beeing % of the capacity so 51 for arr and 85 for dep
  }
```

Also I still would like to somehow keep the level of difficulty when switching airports...

**Comment by sixeyeco** [comment]
@patitoxd Thanks! MetroUI is very sleek and slim. One thing I think needs to happen is that the css and js should be slimmed tremendously. We only need a fraction of the power that available. 

My two cents: I envision normal being something like 30%. That way there's plenty of room for the novice and the experienced alike. 

As far as making the changes global my opinion is that proficiency comes one airport at a time. We don't necessarily progress globally. If the settings were global (across all airports) then when I switch to a different one I'd have to reset the settings again. I suggest default settings be normal (30%) for all airports unless set otherwise.

**Comment by erikquinn** [comment]
@patitoxd your post literally has me cracking up over here. lol I do follow what you're saying, and had a similar difficulty expressing my suggestion, which it seems was not described adequately, as it sounds like you and @sixeyeco are thinking about something slightly different than what I was trying to describe.

I'll try to clarify by linking it to stuff you guys said:

---

> I envision normal being something like 30%. That way there's plenty of room for the novice and the experienced alike.

I agree: this is what the `typical` value would be set to. I am just suggesting it might make more sense to have the slider scale go from 0-150%, with 100% being the "real world capacity", so that leaves room for us to have either much more or much less traffic than they do. If you guys think it makes more sense to make "real world" something like 30% in order to keep the scale 0-100, I'd be alright with that, but think having 100% be exactly the real-world maximum pace is something that would make a lot of sense when we come to explaining it to the users.

---

> So you are on a small airport with a challenging amount of traffic (like 3x of the normal value), you switch to a huge one and keep your settings but you don't get overrun because of the relative way you have set your amount of traffic

With what I'm saying, this wouldn't be the case, nor would I really want it to be... Say we're doing San Diego (188,000 ops/yr) at 90%. That would mean we are working just slightly fewer than the maximum number that airport is able to keep up with (called an "airport acceptance rate"). If I am efficient, I can keep up and avoid delaying _any_ of the aircraft. If I turn it up to 100%, I have to be perfect to keep up. If I turn it up again to 110%, the rate that they spawn at is _FASTER_ than the rate that they can land, even if I put them right at the minimum required spacing.

Therefore, let's turn it back down to 90% here at KSAN. It's "very busy", and I'm working about 30acph (aircraft per hour). Now let's change airports to LAX (636,000 ops/yr). [See Note 1] With 90% traffic at LAX, I will experience **the same demand for efficiency** as I did when it was 90% at KSAN. However, here at LAX, I will be working many more airplanes (~102acph).

Therefore, at the busiest and most complex places, it will be harder to become good enough to work traffic at "80%" or higher than it will be to do it at a smaller, easier airport. And only experts will be able to stay alive at 100%, but not even for forever.

---

> proficiency comes one airport at a time. We don't necessarily progress globally. If the settings were global (across all airports) then when I switch to a different one I'd have to reset the settings again.

I agree with this completely. That is why I would want airports to always load with the "typical" traffic levels, and then I can adjust them to my liking. I would have to do so every time (which isn't a big deal). And if/when "scenarios" become a thing, the traffic levels could be written into the scenario.

---

Maybe the clearest way to explain is by saying that you WOULD NOT set it to "three times the normal traffic". The `typical` value is JUST what the default would be. The slider would show what percentage of the airport acceptance rate we are running at. This would lead to controlling usually between 60%-90%.

---

```
Note 1: At this point, I would not want it to `"keep your settings"`,
but I would want it to reset to the `typical` rate: how busy the
airport usually is in reality. 
```

**Comment by engeplabs** [comment]
@erikquinn I like the idea of the amount of traffic being able to pass the maximum amount of the actual airport. So a scale from 0% to 150% is an option I agree with. (One question though: where can we find this max acph data?)

For the initial value of the percentage: so we would have to set the initial value to a reasonable value which will be different for the different airports? This is the route I would use because as you said, I might handle 90% traffic in a small airport quite good but would just be not efficient enough for this amount of traffic on a bigger airport.

And thanks to the explaination of @erikquinn I now get why you want to use the initial value of the airport when loading it. And I agree. ^^

_One Idea:
Later, when some kind of saving mechanism is implemented, we might store the traffic settings for the individual airports? (Sorry I just want to safe some of my settings so I dont have to do the config over and over again. Time is preciousssss :wink:)_

**Comment by engeplabs** [comment]
Hey folks
I started working on this issue and read trough the documentation for the airports to understand how the number of aircrafts per hour is calculated for the different arrival types. When reading trough the documentation of the cyclic arrival type I got to some point where it doesn't makes sense:

> The **'frequency'** key is required and **specified in aircraft
> per hour** as an upper and lower bound.

But it also says:

> The 'period' key may be specified and sets how long a cycle is in minutes, if it is not set a cycle is 60 minutes long.

So shouldn't it be:

> The 'frequency' key is required and specified in aircraft
> per **cycle** as an upper and lower bound.

?

**Comment by erikquinn** [comment]
@patitoxd 

> One question though: where can we find this max acph data?

It could be inferred by the number of runways, reduced by airspace limitations, or undesirable runway arrangments (eg intersecting runways can't have a solid stream of arrivals/departures to/from both at the same time, etc). I've reached out to a guy who would set and adjust real-life airport acceptance rates about how we can calculate them. For example, avg ldg spd 130kts, 3.5nm in trail on final yields a maximum of `130nm/hr / 3.5nm =` **37** arrivals per hour for that runway alone if it is used arrivals only. Math like this could get us close, but in reality it isn't always possible to get the theoretical maximum (wake turbulence adds additional miles on final, for example). Hopefully he can provide some useful material, otherwise I can draw up some guidelines so we can just "eyeball" it.

> The 'frequency' key is required and specified in aircraft
> per cycle as an upper and lower bound.

Yes, it looks like this is probably the correct interpretation. If you change the comments, just also include that if the cycle period is not defined, it is assumed to be one hour (just for clarity).

**Comment by engeplabs** [comment]
@erikquinn Yep we could do it in a calculative way. But maybe we don't even have to add these "planes per hour" properties. We could just take the current min and max values for the arrivals and departures as they seem to be in a reasonable range for most of the airports and scale them up or down depending on the traffic settings of the user.

> Yes, it looks like this is probably the correct interpretation.

Then it should also be
"This will spawn an average of 35 aircraft per **cycle**"
instead of

> This will spawn an average of 35 aircraft per hour

?
(example for calculation is here [https://github.com/zlsa/atc/blob/gh-pages/documentation/airport-format.md](https://github.com/zlsa/atc/blob/gh-pages/documentation/airport-format.md))
And finally: does any of you guys get the thing with the 'offset'? :see_no_evil:

**Comment by erikquinn** [comment]
> We could just take the current min and max values for the arrivals and departures as they seem to be in a reasonable range

Fine by me for now. They _will_ be updated later though :wink:

> Then it should also be "this will spawn an average of 35 aircraft per cycle"

Looks that way to me.

ref the `offset`, I'm not sure. There's some comments in `zlsa.atc.ArrivalCyclic`, but I am not quite sure how they work exactly. Generally speaking, the value of `offset` is used in `wave` and `cyclic`, but not `random`, and it seems to shift the _middle_ of the "wave"/"cycle" forward that many minutes. I can't really make out what the arithmetic is doing though.

**Comment by tedrek** [comment]
@patitoxd, @erikquinn, regarding the arrivals (cyclic in particular).  The frequency is not aircraft per cycle, it is in aircraft per hour.  This means the frequency key is the same thing regardless of the arrival type.

It's probably most useful to consider to the period value when looking at a wave arrival type.  If the arrival is configured with a frequency of 30 aircraft/hour and a period of 30 minutes then it will spawn two groups of 15 aircraft in an hour or one group of 15 every 30 minutes.  The opposite could be done, with a period of 120 minutes then one group of 60 aircraft will be spawned every 2 hours.

As an airport's capacity is generally determined in aircraft/hour it's useful to target some overall aircraft/hour with the combination of arrival entries.  The `period` and `offset` can then be tweaked independently of the `frequency` to create an overall arrival rate which is always playable over time but may have many more arrivals over a short period than can be landed during that period causing a temporary increase in the number of aircraft the controller must manage.

The random arrival type essentially sends a constant stream of aircraft although with some variation between any two aircraft.  The cyclic type is a middle ground between the constant stream which is random and the all or nothing which is wave.

`offset` is exactly as @erikquinn, described.  It shifts the middle of a wave or the peak of a cycle.  By default it is 0 or no shift.  This is useful so the airport designer can have a bunch of aircraft come from say the north east and the north west at the beginning of the game and then shift it to south and south east half an hour later.  This would be accomplished by having the north east and north west arrivals have an offset of 0 meaning they start off spawning at the maximum frequency, and have the south and south east arrivals have an offset of 30 meaning they start the game spawning at minimum frequency.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
