### ISSUE TITLE
Circular or Sector-Shaped Restricted Airspace

### ISSUE THREAD

**Issue by siyuanr** [zlsa/atc#384]
This is a partial extension of the discussion in #219. Some restricted areas are defined using a center location, radius, and (if it is a circular sector), the range of degrees. Can we implement this?

In the following example, in the vicinity of `VHHH`, `VHD5` is a firing range defined by coordinates; `VHR12` is an entertainment park with a circular shape, radius 1.35NM; `VHP8` is a satellite station whose restricted airspace consists of two circular sectors with the same center.

<img width="594" alt="screen shot 2016-02-08 at 06 08 58" src="https://cloud.githubusercontent.com/assets/15655087/12878796/a4fb3554-ce2a-11e5-9c8a-51e21ca76aab.png">
(Source: ENR 5.1, AIP Hong Kong)

**Comment by sixeyeco** [comment]
It's already implemented, a few airports have airspace restrictions. On my fork, at an airport called M002 I have a single restricted circle to simulate a police closure with a 3k foot ceiling. 

I've been wanting to post a wiki page showing how to create these zones quickly using a website and an excel spreadsheet. With accurate GPS coordinates it's a snap. If "close" is "good enough" then you can get general shapes with a point and click solution. 

I found the coordinates at http://www.ais.gov.hk/HK_AIP/AIP/ENR/HK_ENR5.1.pdf. If you confirm that they are correct then I will write the code for you and detail the steps I took.

**Comment by sixeyeco** [comment]
I generated the restriction for VHR12 at VHHH. You can test it on [my fork](http://sixeyeco.github.io/atc/). 

[Here is the link to the raw airport file if you want to copy it.](https://raw.githubusercontent.com/sixeyeco/atc/gh-pages/assets/airports/vhhh.json)

**Comment by siyuanr** [comment]
@sixeyeco Excellent! Could you show me how to extrapolate the circumference coordinates based on center coordinate and radius (presumably in Excel)?

**Comment by sixeyeco** [comment]
Sure. I use [this site](http://www.gpsvisualizer.com/calculators). Enter the radius and center coordinate in the section titled "Draw range rings around a point" and click "show coordinates". That might be all you need if you have more experience at coding than I do.  

<img src="https://cloud.githubusercontent.com/assets/179496/12895469/6e1d63f0-ce51-11e5-942e-2f4689714fcc.png" alt="Jon Ross' ATC" align="right">Because I can't write code I take the coordinates and paste them into Excel and use "text to columns carve out the actual coordinates.

Then, I copy the sample "restricted" code from uudd.json and paste that it into adjacent cells in Excel and use "text to columns" (in the data ribbon) splits the code apart in to separate elements.

![image](https://cloud.githubusercontent.com/assets/179496/12895024/498c9dfa-ce4f-11e5-8acb-8b3adb8a4a58.png)

 Then I use "find and replace" and concatenate to make it look like this: `["N55.7844040", "E37.1407187"],`. 

Here's what the formula looks like when concatenating: ![image](https://cloud.githubusercontent.com/assets/179496/12895354/e78629da-ce50-11e5-95d6-a4c8eb86002c.png)

Copy and paste into the airport.json and you're done. 

So far, I can only do circles. Shapes are proving much more difficult. I am trying to do the VHD5 as we speak. I'll let you know if I have success.

**Comment by erikquinn** [comment]
@siyuanr AutoCad and use of the `dataextraction` function within autoCad is very helpful for more complex polygons. You can plot them with their real GPS locations, and then export via `dataextraction` to csv, and plop that into wherever.

And believe it or not, getting AutoCad is actually easy if you have a valid email address with a university. Just another option to keep in mind, though the above is _definitely_ easier with simple circles and shapes where there's not a lot of data. And gpsvisualizer.com is like one of my favorite internet places! Their calculators are SO helpful.

**Comment by sixeyeco** [comment]
@siyuanr I'm giving up on generating the complex area. Thanks @erikquinn for the tip!

**Comment by siyuanr** [comment]
I [dug up an algorithm](http://www.movable-type.co.uk/scripts/latlong.html) calculating the end point location given start point location, heading (bearing), and distance. To quote:

```
φ2 = asin( sin φ1 ⋅ cos δ + cos φ1 ⋅ sin δ ⋅ cos θ )
λ2 = λ1 + atan2( sin θ ⋅ sin δ ⋅ cos φ1, cos δ − sin φ1 ⋅ sin φ2 )
```

> φ is latitude, λ is longitude, θ is the bearing (clockwise from north), δ is the angular distance d/R; d being the distance travelled, R the earth’s radius.

Here's an excel screenshot of one circular sector of `VHP8`. Earth radius and distance are in miles:
<img width="675" alt="screen shot 2016-02-09 at 01 48 25" src="https://cloud.githubusercontent.com/assets/15655087/12904371/77c21d0a-cecf-11e5-8ba8-c8239e4c6d7c.png">

The excel file is attached. We can now close this issue!
[VHP8.xlsx](https://github.com/zlsa/atc/files/122436/VHP8.xlsx)

**Comment by siyuanr** [comment]
I will file the changes to `vhhh.json` under #370.
