### ISSUE TITLE
Airport importer

### ISSUE THREAD

**Issue by zlsa** [zlsa/atc#4]
An importer that reads OSM data to create an airport layout.

**Comment by ajillingworth** [comment]
And have it so that you just specify the airport code (or type the name of the airport) into the GUI and it goes and grabs the data for you. :-)

Question - where do you get the fixes from? Is that in OSM data as well?

I'm going to start working on this.

**Comment by zlsa** [comment]
I'm pretty sure that navigational fixes are just lat/lon pairs in a computer, so OSM wouldn't have them (as they only map things that are on the ground).

**Comment by ajillingworth** [comment]
OK. So autogenerate and then potentially allow the user to modify them later?

**Comment by zlsa** [comment]
I was planning on a general-purpose editor that could import OSM data to add to the current airport so you can always edit the layout after import (because OSM isn't perfect).

**Comment by lastmikoi** [comment]
You could make an IVAO-Scenery file importer, they have loads of sceneries ready to use for their online ATC software, including STARs, fixes, runways and even taxiway information - I can only hope this format is sane enough to parse.

Nice work with simulator, anyway.

**Comment by MaicomMR** [comment]
Only an idea, it would not be simpler initially create a basic software to read the coordinates of the mouse based on a scale of 80 (Km or Nm) follows two images concepts:
1st you need to crop an image background in a square shape corresponding to 80.
2. Next, you add the image in software and read the coordinates of your mouse, then just add the name and contact details on .json file.

1º - ![pass 01](https://cloud.githubusercontent.com/assets/12571488/7791356/2a49306c-0275-11e5-951a-67e845dd2c7a.jpg)
2º - ![pass 02](https://cloud.githubusercontent.com/assets/12571488/7791357/2a525818-0275-11e5-849d-260e7685de13.jpg)

I am very new to programming, I do not know if it would be possible to create a program with these resources, excuse me if I'm talking nonsense

**Comment by Maverick283** [comment]
I'm not keen on JavaScript, but I could start a java program to include airports from a database of a flightsim program... Not sure if or how much that would help, but it just might. 

Also, I think a airport editor for developers might make sense (that as well I could write with java) where you input real coordinates and convert them to the game coordinates (which I assume from the picture above and from looking into the ICAO.jason files for the airports are miles from the airport).

**Comment by zlsa** [comment]
Something like that is already implemented - you can use coordinates in the format ["N30.0", "W120.0"] if you set an airport center in latitude and longitude as well.

**Comment by Maverick283** [comment]
@ZLSA not quite sure what you mean. 
Are fixes, arrivals and departures and so on included in that implementation as well? My thinking was of a wizard kind of thing, that would guide you through creating a whole .jason file for one airport.

**Comment by tedrek** [comment]
I think zlsa was pointing out the conversion from Lat/Long to offsets is no longer necessary as the .json can have Lat/Long directly in them now (assuming a center location is defined).  As an aside, horizontal locations in the game code are specified in km not miles (but altitudes are in feet, because... reasons :wink:).

**Comment by engeplabs** [comment]
Does anybody has Navigraph files?

**Comment by erikquinn** [comment]
@patitoxd I have some old ones... I had the same thought (I'm assuming you're talking about writing a parser for a particular version of navigraph fms data). The way I saw it is that we would do that, and somehow keep the whole planet's nav data in a database, and then load only the data within ~150nm of the position of the airport being loaded. Then, all the airport json files would have to contain would be the scope settings, like video maps, etc.

A few questions came to my mind on this:
1. Does Navigraph get touchy about us reading in data we buy from them and re-arranging it? It's possible they don't allow that.
2. Does Navigraph offer a straight-up json format? (I'm not seeing one)
3. Does Navigraph have a problem with us buying nav data that will then be used for free by our users? (unfortunately, the answer is probably yes)

Honestly the ultimate answer might be Jeppsen, because I think they actually have full data for taxiway and parking locations, in addition to the runways and fixes, etc. Navigraph only has runways, fixes, and airways. If Jeppesen data was something we could get, then it could become as crazy as "do any airport on the planet". Crazy stuff! But that's probably totally insane and 100% impossible.

Anyway, long way of saying that yes, I do have a few old airacs laying around.

**Comment by engeplabs** [comment]
@erikquinn Yeah I thought of parsing those files. But I would stick to the JSON format for the moment. And also I wouldn't go that far to import/export every airport out there. We still would have to assign the airlines and their planes. But it would make the creation of the airports a lot more easier in my opinion.

About your questions:
1. I don't know what happens when we rearrange the data but it might be some where in the grey zone of what we are legally able to do and what not... but I might have a look on this if you wish.
2. Nope i don't think so and even if they would, they would not have the correct layout for our needs.
3. As they are not usable for their initial purpose this might be such a grey zone where we would have to do some investigations.

Yes it seems that Jeppsen has much more details concerning the data they provide. (I just take your word as the truth). But at this moment I think the Navigraph data is sufficient because what else do we need? And with them we still would be able to get every ariport of the world wouldn't we?

And great! So maybe we could do something with them.
Which cycle do you have (just out of curiosity :wink:)
And now I have to catch some sleep! It's almost 11pm here in Switzerland! :joy::sleeping:

**Comment by erikquinn** [comment]
@patitoxd yeah, I'm not positive, as I have no access to any of it, but I know I have seen jeppsen charts that have GPS points of all of the parking spots for some airport, and since they can generate airport diagrams, I _assume_ they also cover the taxiways. That's the only difference between them and navigraph-- when this sim gets a "Tower" mode where you control taxi as Ground Control, it would be nice to have the taxiway data already done for you, and we just make a little utility that could convert it into whatever format we're usign, and paste it right into the airport json. I'm getting ahead of myself honestly, that is a LONG way off. lol

And yes, Navigraph is close enough to 100% coverage to my knowledge. Any airport you've heard of, they've got it. I believe their data source _IS_ Jeppesen; they just probably don't pay for access to taxiways, because who cares. :laughing: 

I'm not sure, its maybe two years old. Something in the realm of cycle 1350 or so.

**Comment by engeplabs** [comment]
@erikquinn Ah now I know what you mean by "Jeppsen has more ground information"! Yes they do have the coordinates of the parking positions. But unfortunately they don't provide this data for the taxiways as far as i know. They have the data for the gates so that pilots can check if their IRS is aligned to the correct position (at least that's what i use them for :joy:).

And ok. You know, maybe if we use some old data they don't even care anymore. :wink:

And for you: I see you like the idea of ground operations a lot... ^^ maybe there is a way of extracting taxiways from the files of my fsx? But this just as a notice :smile:

**Comment by erikquinn** [comment]
@patitoxd ahhhhhhh that makes sense. Navigraph all the way then. And fsx not so much, as they are stored in bgl files( just like scenery), which are compiled binaries... Annoying right? X-Plane nav data I hear is much nicer to work with, and I think it would probably include the taxiways.

**Comment by engeplabs** [comment]
@erikquinn Ah I didn't know those were saved in binary files... :disappointed:
Soo.. do you have X-Plane? And I always thought X-Plane is only for the USA...

**Comment by engeplabs** [comment]
@erikquinn Look what I found! :smiley: [http://www.scruffyduck.org/bgl2xml/4584282773](http://www.scruffyduck.org/bgl2xml/4584282773)
Maybe FSX is back in scope :wink:

**Comment by Fechulo** [comment]
I am an X-Plane 10 user and have recently purchased 1602 data from Navigraph (not charts though, only navdata), let me know if I can assist you in any way.

**Comment by engeplabs** [comment]
Hi @Fechulo. Great to hear that. If @erikquinn was right we could maybe get the data of taxiways from the X-Plane files for ground operations after we finished the other tasks (so maybe in one year or so:joy:). And for the Navigraph data... I think we should be able to legally parse them as the modification we would do to them are so big. Isn't there any lawyer working in this repo? :smile:

**Comment by Fechulo** [comment]
@patitoxd Great, let me know when you need the data.

**Comment by Fechulo** [comment]
I was looking at the Navigraph data and I found a document which says:

> This data may be used for ground based recreational computer game
> simulation software only, and may not be recompiled, interpreted,
> or distributed for any purpose without the written consent of Navigraph.

I'm not quite sure if this means we are allowed to use their data or not. The data includes:

-A file with all navaids, their names, frequencies and coordinates*
-A file with all waypoints and their coordinates*
-A file with all airways, the waypoints and navaids in them, and their coordinates\* (useful if we ever have a center control)
-A file with all airports and their coordinates*
-A file for each airport with all of their SID's, STAR's, transitions to final approach, and coordinates*

*Coordinates are all in decimal form, e.g, 53.499389,-6.307111

**Comment by engeplabs** [comment]
So than this is a no as clear as it gets until we ask them for permission because we would clearly _interpret_ their data...

**Comment by Fechulo** [comment]
I doubt they will give us permission :(

**Comment by erikquinn** [comment]
We should keep an eye on [this thread on the navigraph support forum](http://www.navigraph.com/forum/viewtopic.php?f=54&t=3076). (Annoyingly, you need to register to view it. It's free though, as buying the data is separate from registering.)

It's of a guy who "applied for a navigraph license for [his] application". Maybe it would prove helpful. It at least indicates that there is a process that could possibly lead to them allowing us to use their data, but I agree with @Fechulo... it's not looking good. :disappointed: 

screenshot:
![image](https://cloud.githubusercontent.com/assets/5103735/13131027/e2ac9cce-d5b6-11e5-9066-54f2198fc116.png)

**Comment by Fechulo** [comment]
We could still try, we wouldn't lose anything. We contact them at info@navigraph.com

**Comment by Maverick283** [comment]
Just a heads up guys: If we were to parse all the navigraph data (which is a bunch, and by a bunch I mean like a really really big bunch!) and have planes flying from airport to airport (with a multiplayer mode, only reason why we would need all navigraph data anyways) we'd also have to implement some kind of route finder. I tried that once for my Virtual Airline, but this is the most ugly thing I have ever had to do -_- 

My point here: Even if we get permission to use the data, be aware that parsing and using it will be like programming a separate program... That needs about as much attention as this one...

But I do like the idea! :P

**Comment by Fechulo** [comment]
@Maverick283, I think the data could be used for creating new airports faster. one could just enter the ICAO and the program would generate it automatically using Navigraph data. In terms of a route finder we can always use [RouteFinder](http://rfinder.asalink.net/free/) which is free and as far as I know allows other people to embed it on their websites. I've been using it lately and the results are pretty good. The routes don't need to be generated in-game, these could be specified in the file for the area.
Let me know what you think

**Comment by rockg** [comment]
VATSIM regions have sector files to pull into VRC (a VATSIM ATC client).  For example, here is the ZNYC file ([http://www.nyartcc.org/downloads](http://www.nyartcc.org/downloads)) - ZNY VRC 1602.  I don't know what kinds of restrictions are put on this data and it is definitely more information as it contains the entire sector but maybe something to use.  [Here](http://www1.metacraft.com/VRC/docs/doc.php?page=appendix_g) is the definition of the sector file.  Taking the BWI file we have, for example, FIXES and SIDs:

```
[FIXES]
CONLE N038.41.30.260 W076.35.01.620
...

[SID]
Departures:
--CONLE3                  BOSLY BOSLY RAISN RAISN
                          RAISN RAISN STABL STABL
                          STABL STABL OHSSS OHSSS
                          KEMMP KEMMP BEWEE BEWEE
                          GAGLR GAGLR BEWEE BEWEE
                          BEWEE BEWEE OHSSS OHSSS
                          OHSSS OHSSS CONLE CONLE
                          CONLE CONLE BOOCK BOOCK
```

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
