### ISSUE TITLE
Previewing/Showing list of assigned fixes in strip

### ISSUE THREAD

**Issue by kevini15** [zlsa/atc#407]
I've seen a picture of it somewhere in the Issues section already, but the main topic of that was something else... Wouldn't that be awesome, if there was like a list of fixes the aircraft has been assigned to?

Thanks

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
