### ISSUE TITLE
FMS doesn't update SID after unexpected runway assignment

### ISSUE THREAD

**Issue by headphase** [zlsa/atc#425]
Hey guys new to github and new to contributing, I was playing around with KJFK trying to code some SIDs and came across an issue with the DEEZZ4 departure specifically.  Departing 31L/R the sid calls for aircraft to fly to SKORR, CESID, YNKEE, then vectors to DEEZZ.  But as you can see below, aircraft cut corners and don't make it all the way to the assigned fixes.  Is there anyway to program the SID to stop this behavior?

![deezz4](https://cloud.githubusercontent.com/assets/6735197/14311605/2ad7d5d4-fbb6-11e5-8988-5e51d3910807.png)

**Comment by erikquinn** [comment]
hi @headphase, and welcome... two things I'm seeing here:

> But as you can see below, aircraft cut corners

this might actually be desired (I'm not sure). Some fixes are "fly-by" (the pictured behavior), and others are "fly-over", where they must pass the fix _before_ initiating the turn. That wouldn't be too tough to add, but it's currently not super high on my list of things to get to.

>  Departing 31L/R the sid calls for aircraft to fly to SKORR, CESID, YNKEE, then vectors to DEEZZ

This is a bigger deal, however. The chart says they should pass through YNKEE on a 173 heading, and then will be vectored to DEEZZ, whereas that airplane clearly has other things in mind. :stuck_out_tongue_winking_eye: Adding the option for a step of a SID to include simply a heading (or also stuff like a heading until reaching an altitude) would be a big improvement.

So to answer your question, no, there currently isn't a way to stop it from doing this, other than maybe adding a hidden fix a few miles past YNKEE (to make it hidden, just start the name with an underscore) as a temporary workaround, but it will not fix the issue of turning northbound. We'll keep this issue open as a record of that, so hopefully it can be fixed.

**Comment by headphase** [comment]
Aha!  Thanks I wasnt aware of hidden fixes, that will work great for now.  But yes it would be excellent if we could designate fly-over fixes with a symbol, maybe a hashtag or something?  Especially since they are important on these RNAV procedures.

**Comment by headphase** [comment]
Ok added in a few hidden fixes to get the desired behavior (made visible in the screenshot), but these pilots are still ignoring them and going straight to DEEZZ 😐

In fact they are now skipping the other published fixes completely, haha...
![deezz4-rightturn](https://cloud.githubusercontent.com/assets/6735197/14343610/2e2563f4-fc70-11e5-98f5-8e7babcd8ade.png)

**Comment by erikquinn** [comment]
![image](https://cloud.githubusercontent.com/assets/5103735/14349597/bc2f47b4-fc89-11e5-929c-689741d701ed.png)
^Both a/c departed 31L. First got `caf cvs w 31L`, second got `w 31L caf cvs`.

Short answer: It's not your fault; this is a new bug you've found.
Long answer: Apparently what's happening is that the aircraft have a departure runway in mind when they spawn that is based on the wind, which is currently 180 at 6 (best aligned with the 22s). When he is told `caf` or assigned a SID with the `sid` command, he uses the runway he assumes he will be assigned. Once he is told to go to a different runway, he should update his fms to fly the different runway transition, but he doesn't. I'll need to add that in. So, good catch. :+1:

Temporary Workarounds:
- assign runway first, then assign sid or use `caf`
- Use runways best aligned with the wind (by not specifying at all, just say `w` or `taxi` instead of `w 31l` or `taxi 31l`), and then they will end up at the runway they assumed they would be assigned, and their behavior will match the expectation.

**Comment by erikquinn** [comment]
Created a new issue for the flyover fixes, to be tracked and worked separately: #427.
