### ISSUE TITLE
Local testing?

### ISSUE THREAD

**Issue by headphase** [zlsa/atc#429]
Hopefully this isn't too silly of a question, but is it possible to run the game locally?  When I try to open index.html in Windows explorer the load screen just displays "assets/airlines/paa.json" and doesn't start the game itself.

**Comment by erikquinn** [comment]
@headphase Yup! It's the way to go. We should probably have links to some material on how to set it up.

Once you've got github desktop installed, and the repository cloned onto your hard drive, you're almost there (sounds like this is where you're at). Trick is that it isn't a static webpage, and thus needs to work with a "web server". There's many ways to do that, and I am unfamiliar with most of them, as it's not my area. However...

I saw in another issue that Jon said If you're on Linux, it's as easy as running `python3 -m http.server` at the root of the atc project. I'm a windows dude, and far too dumb to know how to do this. :stuck_out_tongue_winking_eye: 

Personally, I use XAMPP because it's easy, very much just install it and point it to the directory where you downloaded the "ATC" repository from github. Only trick to get the apache web server working with github repository is to go and change the paths in apache's settings so it knows where to find the files: set that to the path of wherever you cloned your repository to (mine is at d:\src\atc for example). (This is not nearly as complicated as it sounds, check the link). Then you just go to "localhost" in the browser and the game will load. Make any changes you want, refresh the page, and test them out live. It's really pretty sweet.

[XAMPP Web Hosting Tutorial](https://youtu.be/DFmPg_qWxA8)

Correction: That video isn't what I thought it was. [THIS ONE](https://youtu.be/z_n0XzNErTc?t=163) shows how to point the server to the repository folder.

**Comment by Fechulo** [comment]
@erikquinn I also use windows and I use the "Linux method" to host it locally. It's a bit different though, in my case I need to type `py -m SimpleHTTPServer`, but I've also seen `python3 -m SimpleHTTPServer` and `python -m SimpleHTTPServer`. I've never used XAMPP, but I might give it a try.

**Comment by headphase** [comment]
xampp works great, thanks!
