### ISSUE TITLE
Aircraft taxiing to runways not approved by SID

### ISSUE THREAD

**Issue by headphase** [zlsa/atc#430]
I was reading through issue #324 and thought this was handled by the complex SIDs update, so maybe I'm coding something incorrectly but the image below should explain it; aircraft who have filed the SKORR3 departure should depart on rwy 31L/31R according to the chart (and I've omitted the other runways in the code) however pilots are still taxing to other runways when given the unspecific "taxi" clearance.  I thought that the game did not allow aircraft to use a SID if it was not available for the default runway assignment?

![skorr](https://cloud.githubusercontent.com/assets/6735197/14376429/7625f660-fd37-11e5-97ce-5c4326ce83ed.JPG)

**Comment by erikquinn** [comment]
Yeah, I think this was intended, and was somewhat lazy on my part because I didn't want to have to figure out the hard part... If they are given their IFR clearance, they should file for a SID that will be valid from the runways most likely to be active. And if ATC uses different runways, then we would tell the aircraft their route is invalid and to go talk to clearance delivery again, who would assign them a SID that works with the runways we're actually using. For that, we would have to add a rerouting command. And it should also probably alert the user upon taxi that "my filed SID is invalid from Runway XX" to guide us to reroute him.

I'm pretty sure the current behavior is this: if the SID doesn't have a "rwy" property for the runway the aircraft is using for takeoff, skip ahead and assign the "body" (if available) and "transition" (if available) sections so they at least do something reasonable.

But of course, the eventual intent was to make it so that they cannot take off in the pictures situation without some amendment, either to their SID, or perhaps just skip the assigned SID altogether by saying `BAW127 dct YNKEE fh220 takeoff`. That would be a common real world workaround too. Basically, I just never fully implemented this.
