### ISSUE TITLE
Best practices for decluttering canvas when an airport has many SIDs?  Suggestions welcome

### ISSUE THREAD

**Issue by headphase** [zlsa/atc#438]
Hey guys looking for some brainstorming help; I'm working on KBOS and it turns out there are a LOT of SID waypoints due to the extensive noise abatement procedures and obscene number of runways at an airport of its size haha 😂

So far I have coded 3 out of 9 SIDs and the canvas looks like this:

![kbos](https://cloud.githubusercontent.com/assets/6735197/14437775/db4d6d14-fff0-11e5-9336-8872f4c5b256.png)

Pretty unacceptable imho!  So what is the best way to balance player experience with detail?  So far I'm thinking of:
- Hiding the names of waypoints which are **not** shared by multiple runways.
- Eliminating the SID path markers (I don't really want to, but I'm not sure what other option there is to keep things relatively clean?

Any other ideas?

**Comment by erikquinn** [comment]
Oh please, we all know Vienna is the ultimate winner of the "beautiful nightmare" award!

![image](https://cloud.githubusercontent.com/assets/5103735/14438291/f0b69276-ffea-11e5-805b-824c5694f06b.png)

:laughing: No, but seriously, we do need to figure out how to deal with this, because I agree, it's so cluttered that any possible benefit is lost. Airports with complex SIDs are usually that way because the SIDs make it EASIER on the controller, and by shoving all of them in the user's face, we're kind of doing a little of the opposite. To be honest, when real video maps look as crazy as they do (see #423), I don't really object to a big old pile of fixes. But I don't personally see a reason to have the blue lines. That said, I usually just turn them off by clicking the little taking-off-airplane in the bottom menu-- perhaps that could default to off, if a few people can come to a consensus? That could be a solution, but would make it tougher on new players to predict who is going to go where... food for thought, anyway

**Comment by Fechulo** [comment]
@erikquinn LOWW was so crowded, that I had to remove most of the already existing fixes! Regarding #423 I don't really know what any of those lines and shapes mean. If they serve the same purpose as the blue SID lines, I think we should definitely replace them. Another option is to hide the blue lines for the unused runways or we could let the player decide which ones should be displayed and which ones shouldn't.

@headphase KBOS is looking really good so far. Great job!

**Comment by erikquinn** [comment]
@Fechulo I can only imagine how much work that must have taken... there is a _lot_ going on there. :+1: 

And I don't know what all of the markings on the VMs mean either, they're usually specific to the facility and stuff the controllers need to be able to see. There are a lot of X's, which are mostly all fixes (unlabeled), and then there's like airspace lines and such-- and sometimes even a few key airways. My point was just that the visual complexity is present in the real world, but that something like a SID wouldn't be drawn out on top of one of those video maps, particularly if it were at an airport with cool, complicated SIDs like LOWW.

**Comment by headphase** [comment]
Here's a thought piggybacking off of @Fechulo 's post...

Right now the blue guidelines are defined in one lump under the "draw" section of each SID..

Would it be at all possible to move those arrays to a new part of the airport's json file (maybe "guidelines"), so instead of grouping the lines by SID, we group them by _runway_?

My thinking is that we could then build a simple panel in the UI with on/off toggle buttons for each runway.  When "13R" is selected for example, the blue lines are displayed for all SIDs departing 13R.

Here's how it currently is:

![draw1](https://cloud.githubusercontent.com/assets/6735197/14440140/9a305c40-fffc-11e5-8a59-0e9faa68e015.png)

And here's my idea:

![draw2](https://cloud.githubusercontent.com/assets/6735197/14440244/0b606bda-fffd-11e5-8acd-5085c081d953.png)

(where all starred fixes are flagged transitions)

Is this concept possible?

**Comment by Fechulo** [comment]
@headphase that's exactly what I was thinking about. My fear is that it could make the airport files very long, and some of them are already too long (EGLC has 1134 lines)

**Comment by headphase** [comment]
@Fechulo  Of course efficiency is important, but with the current 'draw' subsections deleted, net increase in file size will be pretty minimal.

Besides, there are other ways to compact file sizes; I had a look through EGLC and found that the restricted airspace was excessively detailed.  I was able to compress the file to 654 lines (21kb) with barely any perceptible change by simplifying the circular airspace geometries.

http://pastebin.com/MN0ACnNe

**Comment by Fechulo** [comment]
@headphase I always knew that the detail in the circular restricted areas was extensive, But wow! That's a lot better!

**Comment by erikquinn** [comment]
That's a good idea. What about taking it one step further, and instead of making the user select the runways to show SIDs from, we either:
- show available SIDs only valid from the runway the aircraft is currently using, on, or planning to use
- show available SIDs only valid from the runway best aligned with the wind (`airport_get().runway`)

And believe it or not, performance would actually IMPROVE from something like this, because the logic and the drawing is fully re-run each frame, so if only drawing a portion of the SIDs (the slowest part, by miles), the game would also end up running more smoothly.

**Comment by headphase** [comment]
Which files contain the code that draws the SID guidelines?

**Comment by Fechulo** [comment]
it's assets/scripts/canvas.js

**Comment by erikquinn** [comment]
Created a new issue, #553 to track work on changing how the SIDs are drawn to the canvas.

Other than that, I think we'll just have to deal with the cluttered canvas for now. Closing this.
