### ISSUE TITLE
"PROCEED" command not working

### ISSUE THREAD

**Issue by elpollodiablox** [zlsa/atc#504]
When I try to issue a "<callsign> pr <FIX>" I'm getting message "Command not understood..."

Was that command removed?

**Comment by Fechulo** [comment]
@elpollodiablox The proceed command was recently removed, due to the introduction of the new route (r) and reroute(rr) commands.

Example usage of reroute command in EGLL: let's assume the aircraft is on the ground and were assigned CPT departure, but you want them to proceed to KENET and MIMBI after CPT. the command would be like this:
'rr EGLL.CPT..KENET..MIMBI'

There's 2 main things you should know:
1.When the aircraft must follow a SID or airway we use 1 dot, eg, rr EGLL.CPT
2.When the aircraft must follow a series of fixes we use 2 dots, eg, rr CPT..KENET

Hopefully you understand, as these new commands are much more realistic and will become very helpful if/when we have en route control mode. I'd recommend closing this issue.

**Comment by erikquinn** [comment]
@elpollodiablox Yeah, sorry-- the documentation isn't quite in sync with how it currently works. It's going to be updated tomorrow hopefully. And @Fechulo is right on, that's exactly how you would achieve what you're looking to do.

**Comment by elpollodiablox** [comment]
Excellent.  Thank you guys!
