### ISSUE TITLE
Adding approach directions to airport settings, not aircraft

### ISSUE THREAD

**Issue by psycho202** [zlsa/atc#51]
[Feature] Wouldn't it be more logical to add the possible approach directions (on aircraft spawn) as setting to the airport itself, instead of adding it as a setting to the arrivals themselves?

A list of a couple, either randomised or looked up from the official approach directions, out of which a newly spawning aircraft could be assigned one, with a balanced amount from each direction (possibly a property as well, frequency?)

**Comment by zlsa** [comment]
The arrival settings are part of the airport settings; currently, each arrival direction has its own airline settings and frequency. (See [Airport format description](https://github.com/zlsa/atc/wiki/Airport-format-description)). I put airline settings into each direction so that you can have, say, British Airways only come from the south.

**Comment by psycho202** [comment]
Aah okay, that was a little bit unclear from the code itself. The wiki page explains a lot. Thanks!
