### ISSUE TITLE
sid with 360 degree looping - crashes game

### ISSUE THREAD

**Issue by ghariman** [zlsa/atc#512]
As I am trying to make a new airport I found this issue/question:

At KSJC (San Jose International) the real airport, one of the SID is called LOUPE where departing aircraft need to do a 360 degree loop climbing up. This is done to gain altitude before crossing over a STAR of KSFO.

However upon trying to implement this, it appears that the game crashes as it is not able to figure out to follow the sid looping as it wants to directly go to the end point.
Two symptoms appear:
1) the plane dissappears and the game gets hanged
2) or the plane is able to takeoff and then goes to FAITH but then directly turns left to BMRNG and does not follow the looping sid.

Any comments?

If you are interested to see the airport (still very early stages work in progress) go to:
ghariman.github.io/atctest/ and select KSJC.

![loupe_plan](https://cloud.githubusercontent.com/assets/17579182/15347192/08527abc-1c74-11e6-9c35-47c4eb43fa9a.jpg)

![planwest](https://cloud.githubusercontent.com/assets/17579182/15347213/4bec651c-1c74-11e6-977f-8ccfe786555a.jpg)

**Comment by erikquinn** [comment]
Maybe try putting a speed restriction on each fix in the loop of 210 or less? I guess it's possible the loop is too tight at 250, and it freaks out because it doesn't have enough time to make the turns. It definitely shouldn't be hanging though, that's something that'll have to be looked at....

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
