### ISSUE TITLE
Disappearing extended centerlines

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#515]
In most airports, the extended centerlines of one or more runways are not being drawn. The most clear example is KDCA:
![kdca](https://cloud.githubusercontent.com/assets/13125311/15408250/21d984b4-1e07-11e6-96c5-112321c96e0f.PNG)

**Comment by erikquinn** [comment]
This _was_ actually intended... the centerlines are only drawn for runways that have `ils` flags of true. In my experience, ILS equipped runways are the only ones with extended centerlines drawn. Else, the depicted RNAV fixes would provide the guidance.

And actually, they'll still "capture the ILS", as seen in this screenshot... which is probably bad, because it should say "visual apch" instead of "on ILS", but I don't feel like fixing that right now lol

![image](https://cloud.githubusercontent.com/assets/5103735/15409168/3b0e5064-1dd9-11e6-8592-9a2443856ee0.png)
PS: Pay no attention to my blaitant disregard for actually separating these aircraft.

**Comment by Fechulo** [comment]
Ahh, I thought it was a bug! This makes much more sense.
