### ISSUE TITLE
Illogical choice of runway

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#525]
If you have 3 runways:
- runway 09-27
- runway 10-28
- runway 11-29

And you have the wind at: 090 degrees, 4 knots, you would expect the aircraft to taxi to runway 09 (in the case you don't specify a runway). In-game, it seems to want to choose the other two (ie. 10 and 11) instead of 09. Shouldn't the game default to using 09? It's quite unreasonable to use the other 2 runways, unless the game is intelligent enough to go about retrieving maintenance info etc.

The game choosing to opt into using a different runway becomes quite annoying when you wish to clear an aircraft for a departure, which is not valid for the runway that the game has chosen, without taxiing them to the runway of choice.

**Comment by erikquinn** [comment]
The logic seems to use a randomized component, choosing the runway not based on the wind, but based on an imaginary wind of (real wind +/- 10 degrees). I guess the purpose is to add some variation (which would be a good thing), but I agree that this random component might not be the way to go. Anybody have thoughts on changing this?

![image](https://cloud.githubusercontent.com/assets/5103735/15625365/9ee88bcc-2469-11e6-8db5-eadba6cf125b.png)

**Comment by erikquinn** [comment]
Encountered an even _weirder_ instance of this.... in this screenshot, using `taxi` with no runway specified caused the aircraft to taxi to opposite ends of the same runway...

![image](https://cloud.githubusercontent.com/assets/5103735/16141351/43b8dd1c-3420-11e6-882a-7652b70da564.png)

**Comment by eliuuk** [comment]
I've got no idea, apart from the wind heading directly in the centre of each runway, as I always configure it like that to test it. ie, 130 is 90 degrees perpendicular to both runways

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
