### ISSUE TITLE
Departures re-entering airspace request taxi

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#526]
If departures leave your airspace and rejoin your airspace again, they will request taxi instead of report their altitude. They continue en-route despite this, however.

http://prntscr.com/b6rqyv

**Comment by erikquinn** [comment]
It isn't ideal that they request taxi, but it doesn't really seem possible to me that the airspace could possibly be set up for this flightpath to be the case... If VIDP Approach really does own that long skinny piece of airspace the aircraft is entering in the screenshot, they would definitely own the area around it too... this is probably another instance of the need to find the associated outer area, and not just the TMA/TCA, as discussed in #511.

I agree that the airplanes are saying something odd, but really the issue lies with the probability that the airspace provided to the game is not the same airspace the ATC facility actually owns, but only the portion that is of an elevated airspace classification.

**Comment by erikquinn** [comment]
If en route mode becomes a thing, we can make a fix for this, but for now, it should suffice to just use airspace shapes that don't cause this issue. Closing :smile:
