### ISSUE TITLE
insubordinate aircraft

### ISSUE THREAD

**Issue by bolero3232** [zlsa/atc#527]
Aircraft won't go where I direct them. If they do, they redirect themselves elsewhere.

**Comment by erikquinn** [comment]
@bolero3232 I'm not seeing any such problem. Could you describe it further? What commands are they not listening to? Is it _all_ aircraft, or just some? Does it start happening suddendly, or does it happen the entire time? Do they ever start listening again? Where do they "redirect themselves" to?

Some more detail will be needed to investigate it.

**Comment by bolero3232** [comment]
I think I've figured it out. I think the aircraft want to finish the STAR. Once it's complete and the aircraft shows a bearing instead of a fix, it behaves normally.   On 05/23/16, Erik Quinnnotifications@github.com wrote: @bolero3232 I'm not seeing any such problem. Could you describe it further? What commands are they not listening to? Is it all aircraft, or just some? Does it start happening suddendly, or does it happen the entire time? Do they ever start listening again? Where do they "redirect themselves" to?Some more detail will be needed to investigate it.—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by erikquinn** [comment]
Is this happening when you use the `fix` command on aircraft that are on a STAR?

**Comment by bolero3232** [comment]
Yes with the Fix command. The revert eventually to their original STAR, without even reaching the fix I gave them.

**Comment by erikquinn** [comment]
@bolero3232 Okay, understood. What you're describing is actually the behavior that is _intended_, by design. And from what I can see having played around with it just now, it _does_ go to the fixes for me.

---

The relevant [section of the wiki](https://github.com/zlsa/atc/wiki#fix):
![image](https://cloud.githubusercontent.com/assets/5103735/15590504/d11325b0-235d-11e6-89be-bde339b540e4.png)

---

[More about `route` and `reroute` commands:](https://github.com/zlsa/atc/wiki#reroute)
![image](https://cloud.githubusercontent.com/assets/5103735/15590756/dacf5a46-235e-11e6-9f4e-d3b82acca29e.png)

**Comment by erikquinn** [comment]
This seems to be resolved. If you have any further issues, please reopen this or write up a new one. Thank you!
