### ISSUE TITLE
Creating terrain GeoJSON Files

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#547]
Creating this issue to track the efforts to create a tutorial on creating terrain files.

You will need [qGIS](http://www.qgis.org/en/site/forusers/download.html). Much of the data acquisition can be done via [gpsvisualizer.com](http://gpsvisualizer.com).

I have been able to get to this point pictured below. Issue is that the contours do not wrap around the outside of the circle. I am not familiar with qGIS, and it seems to be just about impossible to take this 99% finished result and get it finished, so anybody who would know how to do this, please let us know.
![image](https://cloud.githubusercontent.com/assets/5103735/15602636/19723e64-23bc-11e6-956b-734426de1b03.png)

Efforts will continue, but if those who actually know what they're doing can provide a little guidance, that would greatly be appreciated. :pray:

**Comment by erikquinn** [comment]
Another full day of work on this, and I think I've finally found a way to do it. There are a number of reasons what I came up with isn't _ideal_, but it does get the job done, and can be done in about an hour to an hour and a half per airport.

Recorded a tutorial today, and I'll put it on youtube and link to it when the video finishes rendering and then completes upload to youtube. Just a heads up that it is forthcoming, since I knew @Fechulo you were looking to make terrain for TNCM.

EQ

**Comment by erikquinn** [comment]
Tutorial on the method I came up with for generating terrain geoJSON files:

[https://youtu.be/tWky-8QWFWo](https://youtu.be/tWky-8QWFWo)

Feedback and improvements welcome! There are _definitely_ better ways to do it. If you know how, let us know :)

**Comment by Fechulo** [comment]
Thank you very much!

**Comment by Fechulo** [comment]
After many hours of thinking and googling, I finally found a solution. (cue the drum roll) It's Points2One, a plugin for QGIS which allows us to clip the terrain to the polygonal airspace. I've been working on SAME, an airport beside the Andes Mountains in Argentina and I am happy to say that it works perfectly:
![terrain](https://cloud.githubusercontent.com/assets/13125311/16288172/1f856c92-38e1-11e6-856f-0442575e1276.PNG)
I uploaded a [video](https://www.youtube.com/watch?v=3TFZx8nOCz8) that shows how to download and install Points2One.

**Comment by Fechulo** [comment]
This also brings a new problem. As you can see in the picture, the airport is located inside an area of 2000ft, this is because the airport elevation is 2310ft. This causes problems, because whenever an aircraft takes-off or descends on the ILS, it collides with the terrain. This was also mentioned in #558 . The only solution I can think of, is adding the airport elevation to the airport file.

**Comment by Alpi-no** [comment]
@Fechulo I strongly agree! 

> The only solution I can think of, is adding the airport elevation to the airport file.

Should we update this, we could also start to distinguish between ft and Fl

**Comment by Fechulo** [comment]
I spent a few hours recording a tutorial, but I forgot to press record. So instead of a video, I'll try to explain it here.

To do this, you must follow all steps covered by @erikquinn in his [video](https://youtu.be/tWky-8QWFWo) up to second 35:56 (the point where the lines are converted to polygons). From there we must take the coordinates of the polygonal airspace and modify them so that QGIS can read them (same format as the delimited text layer from earlier). In QGIS, go to: Layer-->Add Layer-->Add Delimited Text Layer and the input file will be the new file with the airspace coordinates. Then, using Points2One, select the input file as the coordinates file and save the result in a new file. **(Make sure to select 'Add Result to Canvas')**

You should now have a polygon with the shape of your airspace. You can now follow the same steps as @erikquinn takes in his [video](https://youtu.be/tWky-8QWFWo), but instead of clipping the contour polygons to the ring, you must clip them to the airspace polygon.

**Comment by erikquinn** [comment]
Added a wiki page for this, since we now have a working method for this. I'm not sure if non-collaborators can edit it (?), but if not, just throw up a new issue with further details or new methods and I'll get them updated on the wiki.

[Wiki page](https://github.com/zlsa/atc/wiki/Generating-terrain-GeoJSON-files)

Closing, as the need has been resolved. :smile:
