### ISSUE TITLE
Arrivals disappearing at EDDH

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#548]
For some reason, arriving aircraft disappear and never enter the airspace. They do spawn according to the log, but they vanish immediately after. There are no errors in the log and the code seems fine too. This appears to only be happening at EDDH.

**Comment by erikquinn** [comment]
Found it. Comes from `aircraft.js:3402`:

```
if((!aircraft_visible(aircraft,2) && !aircraft.inside_ctr) && !aircraft.fms.following.star){
      if(aircraft.category == "arrival") {
        remove = true;
      }
```

The aircraft are to be removed if they are not within 2x the airport's `ctr_radius`. You'll notice aircraft following STARs are not affected by this; it's only because they are on a list of fixes that they have this issue. This was used to differentiate between arrivals that haven't yet entered the airspace, and those who have wandered out and need to be removed. The better way to do this is not to check if they are on a star, but rather to check that they are NOT on "heading" navmode. Because any aircraft that wanders out of the airspace would be on heading mode, and thus would be scheduled for removal, while arrivals of all other methods will be allowed to continue.

**Comment by Fechulo** [comment]
In a few weeks, I might start to update the STAR's at the European airports (including EDDH), but I guess it's also a good idea to merge #552

**Comment by erikquinn** [comment]
Done!
