### ISSUE TITLE
3 digit figure is required for headings

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#556]
When giving an aircraft a heading, for example, if I wanted CPA287 to fly heading 20 degrees, you would need to give the aircraft 3 figures (ie. 020 instead of 20).
ie. CPA287 fh20
= CPA287, turn 20 degrees null

whereas:
CPA287 fh020
= CPA287, fly heading 020

**Comment by tedrek** [comment]
I am unable to duplicate this, I tried:
- BEE172 turn 2
- BEE172 turn 20
- BEE172 turn 020

I also tried left and right turns with 1 or 2 digits, this gave turns relative to the current heading but I couldn't get an output of 'turn 0 degrees null'.

To help diagnose, could you specify the exact commands which you are giving and which browser you are using?

**Comment by eliuuk** [comment]
Sure!
I'm using Google Chrome (I don't know the version off the spot)
And, the command used is: KLC1993 fh 30

**Comment by eliuuk** [comment]
Reproduced this on mobile Chrome too for iOS:
http://prntscr.com/be66vu

I instructed the Delta aircraft to fly heading 090, but instead I typed aircraft fh 90.

**Comment by erikquinn** [comment]
@indianbhaji There is no space when using 'fh'. Thus, using `callsign fh090` would give the desired result.

**Comment by eliuuk** [comment]
@erikquinn Thanks for the clarification, slightly unusual that there is no space, but it is what it is!
Closing.

**Comment by eliuuk** [comment]
Reopened due to a similar result, but with the correct command syntax.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
