### ISSUE TITLE
Airport development log

### ISSUE THREAD

**Issue by jpeterson1346** [zlsa/atc#569]
Perhaps for everyone's reference, there should be a log for expected/working/partially completed/etc. airports to prevent duplication of work. A page/post/working document would also provide non-developers insight into what airports can be expected. I'm bringing this up because there are several major airports that lack coverage within the simulation (e.g., my current WIP, KDFW) and consequently, a non-zero potential for users to put unnecessary work into already working projects. Furthermore, it introduces the possibility for developers to request and/or present feedback and other helpful information from others, particularly for developers in similar regions (i.e., people familiar with FAA/NWS practices vs. those with European services).

Another option would be an option for (a) collaboration tool(s) on airspace design, though that introduces a multitude of potential problems.

For substance, perhaps a spreadsheet with the following information might be helpful:
- airport;
- working status;
- expected working status (i.e., will you keep working on it? Is it on hold? etc.);
- complexity (of the airspace);
- estimated completion stage (subjective);
- comments.

Elaborations, suggestions, comments, the like--all welcome.

**Comment by eliuuk** [comment]
This is generally possible just through the use of a pull request, including a checklist on what you are working on in the description and update the title when needed to state the current status, since files automatically update when you push them to your own fork.

**Comment by jpeterson1346** [comment]
You are right on this however my main concern is over the duplication of work. With the amount of current contributors and potential ones, duplication of work seems like a growing possibility. Furthermore, due to the complexity and relative tediousness of this work, redundant work can be rather problematic.

**Comment by eliuuk** [comment]
Duplication is an issue, and I believe that's happened once with KMIA, however, I have no thoughts of any solution to this.

**Comment by Alpi-no** [comment]
Personally, I don't think duplication of work is that much of an issues currently, however, it would be solved by creating an issue and being assigned to it. That would also create a little forum for contributors of the same airport

**Comment by erikquinn** [comment]
@jpeterson1346 I agree it would be nice to see what people are working on, and have some way to collaborate more WHILE doing the work, check in on others' progress, see what is "next on the list", etc... 

There are things out there that can achieve this that I suppose we could consider. For example, something as simple as [slack](https://slack.com/) (common among developers) could address the collaboration portion in a simple way, and has tons of integrations for things like [appear.in](https://appear.in/) where you can have live meetings and web chats, etc.

Separately, there are free project management tools out there that are crazy powerful, but complicated. They could help us prioritize tasking, and be more transparent with the progress being made and what functionality the developers are focusing on now, and planning to work on next. In particular, I have heard great things about [Taiga](https://taiga.io/) in this respect, and tried it out briefly, and liked it a lot for what it was. It bears a lot of similarities to the way real software companies organize themselves, but adds more for people to be doing, when that time could be spent actually working on stuff instead of planning and keeping the tools up to date with what you're actually doing.

Really, I just wish github did a better job with this so it didn't have to be this way. But perhaps utilizing some external tools to fill those gaps wouldn't be such a bad idea.

**Comment by Alpi-no** [comment]
I used Trello in the past very successfully: https://trello.com/b/wfnVSw2C/atc-game. Is anyone willing to try?

**Comment by erikquinn** [comment]
Stumbled across this just now. Seems kinda perfect... thoughts?

https://waffle.io/

**Comment by eliuuk** [comment]
@erikquinn Perfect! It looks like Trello and involves Github, which is a paid feature in Trello.

**Comment by erikquinn** [comment]
Right??? I started playing around with it... it's pretty neat.

https://waffle.io/zlsa/atc

![image](https://cloud.githubusercontent.com/assets/5103735/17840943/c45506d2-67e0-11e6-8b61-7a72efb72083.png)

**Comment by eliuuk** [comment]
@erikquinn It sure does look quite neat, and the interface is well done!

**Comment by erikquinn** [comment]
Added a waffle badge to the readme to encourage people to use this tool. It is SUPER nice to interact with, and a good way for us to communicate whilst not moving completely away from github issues. This just gives a nice way to organize and coordinate. Will close this issue for now, as we finally have a decent solution! :smile:

**Comment by eliuuk** [comment]
@erikquinn Can non-contributors edit the board? Last time I tried it didn't 
let me edit. I'll try again when I am home.

**Comment by erikquinn** [comment]
Yeah, I'm pretty sure you should be able to. Are you able to drag cards around?

**Comment by eliuuk** [comment]
I'll have a look when I'm back home (if only there was an app)

**Comment by erikquinn** [comment]
If you're on your phone, you should be able to drag them around. Note that you WILL have to be logged in (via GitHub) in order to do anything other than view it.

**Comment by eliuuk** [comment]
@erikquinn " Only collaborators can update cards." << That's the message I get when trying to move a card.

**Comment by erikquinn** [comment]
Wow. That's a serious bummer... The search continues then :/

**Comment by eliuuk** [comment]
@erikquinn I don't know if either of these work, but here: https://overv.io/ and https://zube.io/

**Comment by eliuuk** [comment]
@erikquinn Here's 2 more: https://redbooth.com/ and http://gitlo.co/ (I got these from https://www.quora.com/Which-project-management-tools-are-deeply-integrated-with-GitHub)

**Comment by erikquinn** [comment]
zube.io looks like it works differently... give that one a try. Move some cards around, etc. Does that one work, or still no go?

[https://zube.io/projects/4605/kanban](https://zube.io/projects/4605/kanban)

**Comment by eliuuk** [comment]
@erikquinn 404 page not found after logging in

**Comment by eliuuk** [comment]
@erikquinn The projects tab looks interesting, although again, non-contributors can't edit it.

**Comment by n8rzz** [comment]
@erikquinn I've been using kanban for my fork and I love it!  It makes it easy to see all the issues and PRs and add them to swimlanes for easy categorization.

I like that you can create sprints and such too.  I come from an agile environment, so this is really close to the stuff we use with Jira, without all the Jira goofiness.  Their UI is really clean and it interfaces well with github.  

It doesn't replace github issues or projects, but it is a nice complement.

**Comment by erikquinn** [comment]
Yes! I haven't taken the time to have a look at how they implemented it, but at my job in Ohio, I used to use bugzilla and confluence, and (despite the ugly UI of BZ) I've been missing these sorts of planning/prioritization features, so that's promising to hear. Definitely a nice complement. And one thats well overdue, I might add! :P

**Comment by n8rzz** [comment]
whoops, that was the kanban page on _zube_.  It's zube that I've been using.

Personally, I think github provides most everything one would need to manage a project.  By adding zube to the mix, you get some nice visualizations and additional management tools.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
