### ISSUE TITLE
Commanding an aircraft to taxi to the opposite of a one-runway SID causes error

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#580]
In WMKP (which has caused a load of issues, ie. SIDS etc. #574), I have this SID called the MADUM1D. MADUM1D is only for runway 22. Then, what I then did was 'caf' 'cvs', which was successful. Instead of telling the aircraft to just 'taxi', I specified the taxi through 'taxi 04'. Here's the issue.

http://prntscr.com/bhlkox

@erikquinn, this is probably why you experienced crash issues. This issue is pretty much @erikquinn's 2nd comment on #525 and #519 combined.

**Comment by tedrek** [comment]
That's an interesting issue.

Here is what's happening, the initial `caf` causes the aircraft to automatically select a departure runway without taxiing to it.  `cvs` works because a SID and runway appear to be assigned.  Later when an actual `taxi` command is given to a different runway the SID tries to update, it removes the existing SID leg and replaces it with whatever `airport.getSID()` returns for a set of fixes.  When the runway which the aircraft ends up on doesn't have any fixes for it specifically then only the body and later transition fixes are assigned.  In the case of MADUM1D in WMKP there is only a runway section but it doesn't include 04 so an empty list of waypoints is returned, nothing catches this and the FMS ends up with no current waypoint as the first leg is empty.

@erikquinn, any ideas on how best to handle an aircraft which gets taxied to an invalid runway?  I'm thinking it may require completely de-assigning the SID and requiring a new one to be assigned.

**Comment by erikquinn** [comment]
@tedrek As far as de-assigning, i'm pretty sure that's what it does: splices that SID leg, generates a new one, and tosses it in where the old one was. Then when it fails to figure out how to deal with making a new one, that's how you end up left with zero waypoints.

Honestly, I think I just set it up poorly. In hindsight, it would have been a lot smarter to have all the route manipulation and waypoint _generation_ functions outside of the fms, and then just feed the fms the info it needs to run. Because it should be smart enough to check that the return _has_ waypoints, and if not, simply don't change anything. Instead, I tell it to remove the old, generate the new, and then add the new, where you can be left with nothing if part 2 goes awry.

**Comment by tedrek** [comment]
@erikquinn, how simple would it be to change the order: generate new, verify new, replace old with new.

**Comment by eliuuk** [comment]
Still an issue, here's the error:

```
AircraftFlightManagementSystem.js:1013 Uncaught TypeError: Cannot read property 'altitude' of null(…)
    altitudeForCurrentWaypoint @ AircraftFlightManagementSystem.js:1013
    updateTarget @ AircraftInstanceModel.js:1973
    update @ AircraftInstanceModel.js:2647
    aircraft_update @ AircraftController.js:180
    update @ App.js:334
    (anonymous function) @ App.js:331
```

**Comment by eliuuk** [comment]
The issue is just simply clearing an aircraft with a SID which is only valid for one end of the runway. In this instance, it would be the MADUM departure for runway 22. However, the winds in WMKP were configured so that both ends of the runway can be used. If you taxi it to the other end of the runway, in this instance, 04, the game freezes and starts printing a load of errors.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
