### ISSUE TITLE
More Approach Types (Visual, RNAV, GPS, LAAS, WAAS, VOR, NDB, etc)

### ISSUE THREAD

**Issue by Diastro** [zlsa/atc#59]
It is fairly popular for smaller aircraft to fly "visual". 

Maybe we could add this feature which would allow the ATC to clear and aircraft for landing in a visual manner (no using ILS/fixes). Also, Visual aircraft could fly around in an "automated" way.

**Comment by Maverick283** [comment]
VFR flying can not be simplified as much as IFR. The IFR rules are strict, thus easy to teach a PC. VFR though is quite free, thus very hard to get a PC to understand all situations.

**Comment by erikquinn** [comment]
Hijacking this issue to serve as a holder for work on adding visual approaches, and charted instrument approaches.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
