### ISSUE TITLE
A/C Category-Specific Departures

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#618]
Follow up to discussion in #610

**Comment by Alpi-no** [comment]
Why not add wake turbulence classes (as well)?

**Comment by erikquinn** [comment]
idk about other countries, but FAA does not distinguish between weight classes in terms of flying particular instrument procedures, just aircraft categories (based on performance).

We will need to come up with a way to separate into the appropriate classes, keeping in mind that different countries use different methods. In the US, it's just turboprop/piston or turbojet, which we can pull from the aircraft files directly. The question I have is will this be sufficient to differentiate between the A/B/C/D classes used in Dublin mentioned in #610? Or is it more complicated than just the type of engines?

**Comment by Alpi-no** [comment]
I know that some stars are affected by weight class in LOWW, however, I don't think this is too common, as most stars are for everything - basically

**Comment by aldent95** [comment]
How about just to start with, separating propeller and jet aircraft? I know over here in NZ we don't really care about the aircraft category so much as we just have Jet and Non-Jet SIDS

**Comment by erikquinn** [comment]
@aldent95 Agreed, same deal with FAA airports. Would be a simple enough thing to add, making some "turbojet-only" or "prop-only"

**Comment by aldent95** [comment]
@erikquinn exactly. Then if an SID or aircraft is unmarked, just ignore the constraints.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
