### ISSUE TITLE
A/C are not consistent with SID transitions

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#632]
Let's say AAL152 wants to fly the OFFSH9 departure. When I give them the 'Cleared As Filed' command, their transition is displayed. However, AAL152 doesn't seem to care about what transition they'll fly, because if I give them the 'CAF' command again, the transition changes:
![output_j3tva7](https://cloud.githubusercontent.com/assets/13125311/17423349/0d860c34-5ab2-11e6-94b5-fd5d1b930d7a.gif)
List of commands issued to create the GIF:
AAL152 CAF
AAL152 CAF
AAL152 CAF
AAL152 CAF
AAL152 CAF
AAL152 CAF
AAL152 CAF

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
