### ISSUE TITLE
Arrivals always spawn at FL100

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#633]
The title says it all... All arrival aircraft are ignoring the altitude stated in the airport file. They spawn at FL100 and climb back up to meet the necessary restrictions.

**Comment by erikquinn** [comment]
Yeah, it's actually hard coded at 10. And if you notice, it won't be ALL arrivals, just all "pre-spawned" aircraft. In other words, aircraft who spawn at the starting fix of their route, not immediately at the start of the game. Was a workaround for it being really hard to get them to look through the altitude restrictions in the STARs and find the appropriate altitude to spawn at along the descent path. It should be fixed though, just wasn't a high priority when fixing the original issue of long wait times on getting arrivals.

**Comment by Fechulo** [comment]
That makes sense. They probably don't need to spawn at an exact altitude along the glidepath (Option A), I think it's easier if they spawn at the altitude of the next restriction (Option B):
![spawning](https://cloud.githubusercontent.com/assets/13125311/17463810/c6837436-5cc6-11e6-93c7-b119367ae944.png)

**Comment by erikquinn** [comment]
Right. Honestly though, it will already have to step through each fix in the star, and find the altitudes, and it's hardly any more effort to spawn them in accordance with option A as opposed to doing option B. After all, if I have to find the next altitude, it's usually just as easy to find the previous one as well, and interpolate to an appropriate altitude.

**Comment by Fechulo** [comment]
True, I hadn't thought of that. Option A is clearly more realistic but I initially thought it would be harder to code. If you think they're pretty much the same, then I suggest going for A.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
