### ISSUE TITLE
Separate landing and approach clearances

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#645]
In real ATC, landing and approach clearances are separately issued and in the case that an aircraft is not cleared to land, the aircraft goes around.

There should be a way to separate these clearances in the game, and it could be implemented as an option (advanced & simple).

I've looked over the coding for this, and I'm unable to think of a way that this could be put in, as a go-around looks quite complicated to do if an aircraft isn't given clearance to land.

This is mentioned in #558

**Comment by Alpi-no** [comment]
maybe differentiate between cleared ILS runway xx and cleared to land

**Comment by erikquinn** [comment]
I don't remember where, but I believe this was brought up before, and the conclusion was to avoid adding it as a separate command for reasons of redundancy.

However, I definitely agree that it's goofy we act as the approach controller and yet are also giving landing clearances and taxi instructions... The way I see it, this is best addressed by introducing different _modes_ rather than adding new commands. The "Tower" mode, you would taxi airplanes around, and clear for takeoff and clear to land arrivals that are already established on final. The "TRACON" mode you would do what the game currently does, minus taxi/takeoff/landing (provide vectors/altitudes/speeds and approach clearances only). And the "Center" mode, you work overflights, and general arrival/departure traffic to various TRACONs and/or small airports directly. That way, the responsibilities are actually divided properly.

Trouble is that what I've described above would be a large undertaking, and won't be gotten to for a while. :stuck_out_tongue:

**Comment by luznicky** [comment]
In my opinion, it may be nice to cut off the tower part. The last command for arriving aircraft then could be "Contact tower, ..." issued after A/C is fully established (both on localizer and glideslope) somewhere in reasonable distance from runway.
Departing aircraft should be departed automatically and handed over to player shortly after take-off. Interesting issue with this approach can be, how to let player interact with automated tower.

**Comment by scott-j-smith** [comment]
@erikquinn  If you ever do consider a Tower Controller Mode, I'd be interested also in a Ground Controller mode, with the actual airport map including taxiways, aprons, runways, etc. instead of the TRACON view.  Although I have a strong suspicion that would almost be a completely different game.  :-)

**Comment by erikquinn** [comment]
@scott-j-smith Indeed it would be, and that's the idea. :wink: If a tower mode is added, it would be all-inclusive of tower cab responsbilities (eg clearance delivery, ground control and local control). We would not split below this level. So eventually (in my dreamland fantasy), we would have just three "modes": Tower, TRACON, Enroute. And maybe a hybrid fourth for the thrill-seekers: "TraCab" (tower/app).

**Comment by eliuuk** [comment]
Exactly how it's almost always like on VATSIM :p

**Comment by erikquinn** [comment]
@indianbhaji bingo. :laughing:

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
