### ISSUE TITLE
Issue #576 still broken for no-transition SIDs

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#649]
The fix to #576 only works for SIDs with transitions. Thanks to @erikquinn for clarifying this!

**Comment by eliuuk** [comment]
It might just be me, but it appears that I've somehow broken the fix to #576.

**Comment by erikquinn** [comment]
I noticed. It's not you, the fix works for SIDs with transitions, but not SIDs that dknt have transitions. I didn't think about this when checking the proposed fix, so it will need to be elaborated on to also work for SIDs with no transitions that overlap. Also, the idea was actually that SIDs should be implemented as a single entry, with corresponding "suffix" and "rwy" sections instead of one procedure for each. I believe the functionality of using the "suffix" property isnt built into the code and thats probably why you had to do it the way that you did. So we should probably get the suffix part working, which would make implementation of the `sids` section easier on you as well.

**Comment by eliuuk** [comment]
Yeah, the suffix part doesn't come through which is the reason why the SIDs I create are separate for each procedure.

**Comment by erikquinn** [comment]
@indianbhaji Is this still an existing issue?

**Comment by eliuuk** [comment]
I'll double check this tomorrow.

**Comment by eliuuk** [comment]
@erikquinn Yes

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
