### ISSUE TITLE
Improve VNAV glidepath calculations

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#654]
Right now, aircraft just descend to the altitude required by their next waypoint. They should be able to look further forward than just the next fix, and also calculate a smooth, constant rate descent rather than descending at full speed, leveling off, etc.

**Comment by Alpi-no** [comment]
if this included, there sort of has to be a command for plane specific restrictions like `plane don't cross waypoint below/above`

**Comment by erikquinn** [comment]
@jakobeng1303 to clarify, they would still be complying with the fix restrictions listed in the procedure. Given:

C (FL200') ----------[40nm]---------> D (11000')

_Currently_, aircraft will descend at their normal rate upon passing waypoint C, and would level out at 11000 about 10nm before waypoint D.

_I'm proposing_ to have them descend shallower, such that they reach 11000 feet as they pass waypoint D. So its like they're following a smooth glideslope between each waypoint.

**Comment by Alpi-no** [comment]
I thought so but if a plane does that on the entirety of it's flight plan, it could be handy to set manual restrictions for that flight. 

For example:

if a flight in Europe starts at Fl100 at the holding and takes into consideration the transition, it won't descent fast, however, that would not allow it to turn asap onto the glideslope due to its height. So in this case I would set a "manual" restriction to tell plane to be at eg 5000ft right before it can make that turn. 

http://charts.vacc-austria.org/LOWW/LOWW_Arrival_RNAV%20Transition%2016_26052016.pdf in this case, a plane would calculate the descent form MABOD until WW671, where it has to be leveled off at 5000 ft. But the command would allow me, to tell the plane to be level by ww678, to make a turn onto the localiser as soon as possible. Restrictions are in place but only telling the plane to stay above 6000ft.

**Comment by eliuuk** [comment]
Whilst you're at it, any chance of improving the logic for aircraft? ["example", "A60+"] in a STAR should mean a descent, as this should mean 6000ft or above, but not at extreme heights such as FL240.

**Comment by jakobeng1303** [comment]
@indianbhaji not sure if that's what @erikquinn wants to implement but if a plane would calculate its decent(rate) before spawning, that would solve your issue too, wouldn't it?

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
