### ISSUE TITLE
Holding color position

### ISSUE THREAD

**Issue by steevivo** [zlsa/atc#667]
hi,

It's possible to change the holding position with new color than red if possible ?

thx

**Comment by erikquinn** [comment]
You could change it locally on a forked version of the repo I'd you wanted. It's in the actual code somewhere. aircraft.js I think, somewhere in the update_strip() member function if I recall correctly. I can find the exact place later if you aren't able to locate it!

**Comment by erikquinn** [comment]
And if you have a suggestion for changing the color the game uses, that's also certainly up for discussion!

**Comment by Alpi-no** [comment]
@erikquinn l think blue is good!

**Comment by steevivo** [comment]
or a blink Orange, a different color for a particular state ?

**Comment by Alpi-no** [comment]
@steevivo orange could be mistaken with red (and red is already use of near misses)

Could we change the symbol of the plane form the dot to an "H"?

**Comment by steevivo** [comment]
Oh yes good idea ! why not.

**Comment by erikquinn** [comment]
@jakobeng1303 At some point, the targets ("symbol of the plane") will be improved, to show a primary and secondary return, and a "position symbol" overlaid, which will be a letter indicating the sector that is controlling the aircraft. Looks like this:

![image](https://cloud.githubusercontent.com/assets/5103735/18276927/ac444b48-741a-11e6-8b61-d35a4554f523.png)

So I wouldn't want to change the position symbol to an H only to have it changed again later. And blue would be the same as departures, so that doesn't really stick out. But something like a pale yellowish-orange might work, assuming it works decently with the color scheme we have going :smile:

**Comment by Alpi-no** [comment]
That looks promising! You are very right with the arrivals looking similar. I didn't think of that at all!

**Comment by erikquinn** [comment]
Anybody else in favor of changing the color on the strip and color of projection lines for aircraft in holding to yelloweyorange? Or want to weigh in on this in general otherwise?

**Comment by n8rzz** [comment]
just be sure the color is rgba and added to the `COLORS` constant in `CanvasController`

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
