### ISSUE TITLE
New Airport: Providence (KPVD)

### ISSUE THREAD

**Issue by Casper52250** [zlsa/atc#670]
I would like to request that my home airport, KPVD, be added to the game. Whenever you get to it is fine. If there is anything that I can do to help the process along, let me know. I'm not a programmer with only basic intros to coding, but willing to learn (within reason).

Thanks for the great game and keep up the great work!

**Comment by eliuuk** [comment]
Looks quite small, so shouldn't take too long. I haven't looked at any of the information about the airport in terms of navigation yet, so it might not as be tricky as the larger airports.

**Comment by eliuuk** [comment]
I'll have a look at starting this now.

**Comment by erikquinn** [comment]
@indianbhaji here's a video map for you as well. I put both the 5 and 23 flow maps up together.
[G90_RVM.txt](https://github.com/zlsa/atc/files/448520/G90_RVM.txt)
![image](https://cloud.githubusercontent.com/assets/5103735/18150730/236aa324-6fb7-11e6-9b92-6eafbbad38c2.png)

**Comment by eliuuk** [comment]
@erikquinn Thank you very much for that!

**Comment by Casper52250** [comment]
@erikquinn May I ask what the map shows? Is there something I should research to understand it?

**Comment by Fechulo** [comment]
@Casper52250 The video map is what controllers in real life see. It shows fixes, waypoints, sectors, extended centerlines and other airports in the area. There's no need to learn anything, it's just a more aesthetically pleasing method of showing what the controller needs to see.

**Comment by Casper52250** [comment]
I suppose it takes some getting used to, then... It seems a little tricky to pick out the names of the fixes/ waypoints among all of the other lines.

**Comment by eliuuk** [comment]
You can disable the videomap at your own discretion. There is a button at the bottom which allows for this to happen.

**Comment by erikquinn** [comment]
@casper52250 it differs greatly between facilities, but usually they will have some helpful markings depicting arrival and departure corridors, plus the important fixes and airspace boundaries. Not knowing all the sectors the facility is split up into can make it seem like there's lines all over the place, and it's just because we don't know what they're for. But we can sometimes find some documentation that explains the sectorization and markings.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
