### ISSUE TITLE
Documentation & Charts

### ISSUE THREAD

**Issue by erikquinn** [zlsa/atc#672]
Here's an idea: Why don't we use a shared dropbox folder or something where we can store charts and documentation we find specific to each airport? That will make the constant searching for stuff like that easy when subsequent changes and improvements are implemented to our airports.

Plus, if/when an interface is made available to the user to get acquainted with the procedures of the specific airport they are using, having all the documentation at hand would make it easy for somebody to put together an airspace orientation tutorial of sorts.

[https://www.dropbox.com/sh/5qwr1c80ejzs0k7/AADVD9wExkFOWhX5JWGqeY3ua?dl=0](https://www.dropbox.com/sh/5qwr1c80ejzs0k7/AADVD9wExkFOWhX5JWGqeY3ua?dl=0)

**Comment by eliuuk** [comment]
I'd recommend just leaving links, since as the AIRACs advance, they change.

**Comment by eliuuk** [comment]
@erikquinn Is it possible to make dropbox public?

**Comment by ghost** [comment]
How about maybe a separate GitHub repo containing it? That way, we can verify the information being inputted, and make sure (if public write access was given on DropBox) that someone couldn't come by and just delete all the files in the folder.

**Comment by MikePapaSierra** [comment]
Hi,

I think that the easiest way will be to require [ICAO_CODE].md file in documentation section. I prepared that file for EPWA airport and it's contains most important information about that airport and its development process:
- short description about airport with links to Wikipedia and official website of the airport
- assumptions like:
  - wind calculations
  - preferred runway configurations
  - information about data sources with links to them
- TODO section with info what can be done in the future and improvements that can be made

Of course that's only proposition how to maintain documentation for all airports included in project. I don't think that duplicating airport charts and other files that was used to create airport in yet another localization is the best solutions, because someone should take care about updates. When we place links  to that website all airport data will be up to date.

**Comment by doofus** [comment]
@kamikazestar I have a branch addressing #682 where I'm going through and updating all the aircraft info. I'm doing something similar to this.   In the `documentation` folder I have created a file called `aircraft-data-notes.md`. In this file I've specified all my data sources (or derivations) for aircraft parameters used in each JSON file for the aircraft types.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
