### ISSUE TITLE
Easier way to create airports?

### ISSUE THREAD

**Issue by ghost** [zlsa/atc#675]
So I was interested in contributing some airports to the game. That was, until I realized how much work goes into each of them and how much confusi data you'd need. That sparked an idea. What if there was a guided bash script or website that asked you all of the airport's information in a more user-friendly way and then exported a json file from the information you typed? I think it'd be easier in a way and less confusing for more noob people like myself.

**Comment by eliuuk** [comment]
You would still need to find all the waypoints and add the coordinates. In 
my opinion, it is easier to copy and paste into an actual file rather than 
pasting every single waypoint into a command line.
Additionally, SIDs and STARs are not as easy as you think - you'd still 
need to somehow add speed and altitude restrictions, add transitions and 
all that giz.
Also, you'd have to also create a different script for creating airlines 
and creating aircraft. It'd be significantly easier just to edit a file, 
for, there is not much yuck you can do in an airline or aircraft file.
If you were also to create a videomap, it would be pointless as you would 
still be required to enter the file.
In my opinion, I do not see what is difficult about getting another airport 
and editing the values? As long as you do not mess up the template, you 
should be good to go.

**Comment by ghost** [comment]
Ah, okay. After reading that it makes much more sense. Closing issue...
