### ISSUE TITLE
Traffic percentage

### ISSUE THREAD

**Issue by Alpi-no** [zlsa/atc#677]
I have just played EDDF and I felt a little disappointed :/ the reason being the amount of traffic. I can play EDDF on full speed without any problems (some minor clashes on parallel lineup might have happened :D). I was wondering if it was too easy or me being too good and settled for second :D I thought we could create some sort of percentage value for traffic. Basically you choose your hardness and get some percentage of the traffic. 100% could be (for example) twice the traffic right now!

Is that possible?

 Ps whoever merges requests, please have a look at my EDDF transition addition :D

**Comment by eliuuk** [comment]
I'd rather like to have it so that 100% is the traffic specified in the document, so you can decrease the traffic at your own wishes. This way, it should be easier to script as 200% would be twice the amount and so on. Maybe this should be added as a command?

**Comment by Fechulo** [comment]
I agree with @indianbhaji, I think 100% should be the default traffic. This was actually discussed a long time ago on #306 and #374 . Despite that, nothing was ever added to the game as far as I know.

**Comment by Alpi-no** [comment]
Whatever the percentage is going to be, are we able to do so? I agree with @indianbhaji that it should be a command. This would decrease the amount of work too, wouldn't it?

**Comment by nielsvdweide** [comment]
Dont we have the command "rate" for this? @Fechulo

**Comment by Fechulo** [comment]
@nielsvdweide I don't think so, but If there is, I never noticed. I'm not able to use the command 'rate' in game and I can't seem to find any code for it, so I'm guessing we don't have a command for it.

**Comment by nielsvdweide** [comment]
What i remember from the early days that if you would put Rate 0.5 you would get 50% of the traffic. I'm not sure if this works because of all the changes on the inside of the game! @Fechulo

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
