### ISSUE TITLE
SBGR Airport Feedback & New Player Stuff

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#681]
Hi all, 

I'm new to Github, and just found this ATC simulation - it's great!  I'm not a pilot or ATC but have always wanted to learn more about how it works in the real world (not like older sims).   So, I'm really a beginner.  I'm still learning a lot, and getting used to the commands, strategies, etc. I started with the easy airports first of course, and while I didn't have too much trouble with SAWH because it has STAR for inbound flights, and all inbounds only come from one direction, I'm still struggling with others.  

I'm finding SBGR particularly challenging.  It took me a while to get the hang and rhythm of it, and finally figured out that I need to line up everything coming in from the top right to Rwy 27R, and everything coming from the bottom to R 9R (from the far left side of the screen).  I have to add that the pace of this airport is HARD!  You have to be constantly adjusting routes, altitudes, speeds, etc., keep clearing landings, etc.  There are never any breaks from incoming flights, and sometimes you are dealing with 4 new flights at the same time or within a few seconds.   

There is NO TIME to take a breath, evaluate the big picture and strategize -- and if 1 plane gets out of sequence because you forget to issue a command in time, well.... good luck getting it back in line without crowding.

Thankfully there are few outbound flights once the first ones are taken care of.  Although with the sheer number of inbound flights you never really get a gap where you can safely clear an outbound flight for takeoff without getting a conflict!   I'm always in the situation where I've got rows of planes coming in from both sides and they are barely far enough apart to prevent warnings.

So, based on that, I'm wondering if this isn't a difficulty level 2 airport instead of difficulty 1?  I haven't played any level 2's yet, so maybe I'm in for a big shock!

And here is something that might be a BUG:   outbound flights with SID ROMIB cannot be cleared as filed (caf).  How do you clear them to fly to their destination then?

Feature request:  Allow beginners to slow down the action below normal time, perhaps by allowing timewarp commands to use decimals (0.5 = 50% speed, etc.)

I watched the tutorials on YouTube from Fechulo and Chris Kurisu and they were very helpful!  I tried watching the vids where they are doing no teaching, but just showing how they manage a certain airport, but honestly I could NOT follow it because it was time lapse and the commands were being entered faster than I could follow.  If anyone would be willing to do a normal time tutorial for SBGR so I can see if my strategy is completely wrong I'd appreciate it. :-)

Thanks for listening. 

Scott

**Comment by Fechulo** [comment]
@scott-j-smith 
Hey Scott, I'm glad you're enjoying the game!

I think the problem you're facing with SBGR is that its difficulty is underestimated. SBGR should probably be difficulty 2 as you pointed out, or maybe even 3. The issue is that there isn't really a standard for the difficulty of airports. The symbols you see in the game represent the developer's thoughts regarding how hard that airport is. At the time SBGR was made, it might have been one of the easiest airports in the game, but now there's much easier ones SBGR is a very difficult airport to play in for a beginner. I'd recommend ignoring the difficulty symbols, as they are probably inaccurate.

The ROMIB departure in SBGR is only applicable to aircraft departing from runways 27L and 27R. In the game, the winds at SBGR are 50 degrees 10 knots, so the logical runway choice would be 09L/09R (Remember: aircraft always want to takeoff/land with a headwind). So basically, the game assumes that aircraft will use the 09's and so the ROMIB SID can't be used. If you tell an aircraft to taxi to the 27's and then give them the 'caf' command it will work.

"timewarp 0.5" would probably be useful for beginners, I'll open up an issue to discuss the idea.

I'm glad to hear people are watching my videos and actually find them somewhat useful! I've actually recorded a few versions of a normal play through, but I just wasn't happy enough with them to upload them. I've uploaded one of these versions as an [unlisted video](https://youtu.be/cOlpIpX-mdM) so you can watch it. and now that you've asked for it I'll probably do a tutorial video on SBGR. (Although not this week, I'm pretty busy 😄)

Thanks a lot for the feedback
Fechulo

**Comment by scott-j-smith** [comment]
Thanks for the reply!   And for the link to the video, I watched it and it was good for me.  Left you a comment there too, because you said in the video it makes you happy.  :-)    

Looking forward to seeing SBGR when you get time to make it!

**Comment by Fechulo** [comment]
@scott-j-smith thanks for the comment. For some reason YouTube isn't letting me comment on my own video so I'll leave the answer here:

I'm glad you liked it, but it's just not up to my own standards. (I guess I'm very strict with myself, but I suppose it means that most of my videos will be high quality). using vectors is my preferred method of controlling. I'm not sure why, but I feel like I have more control over the aircraft if I'm giving them vectors. for the SBGR video I'll probably try to use fixes only and I might re-record this video using vectors only, so that people can look at the advantages and disadvantages of both methods and decide which one they prefer.

Something I always like to keep in my document is the preferred runway system which you can find in the SOP's (Standard Operating Procedures). For example in KORD, RWY 32L is used for departures to the north and north-east, RWY 28R is used for departures to the west and RWY 22L is used for departures to the south and south-east. This helps me distribute the load of aircraft so that I don't get a huge line of aircraft waiting to depart from a single runway.

I'm uploading the time lapse of KORD in real time to help you out, as the time lapse is too fast to see anything. Unfortunately there's no sound and it's very long, but hopefully you'll find it useful. There's a few things to note about KORD:
1. There's only one SID or Standard Instrumental Departure (ORD1) and it's vector-based, meaning that controllers must give aircraft vectors to their departure fixes.
2. RWY's 32L, 28R and 22L are used for departures only
3. RWY's 27R, 27L, 28C and 28L are used for arrivals only. (RWY 28L is only used if there's a **LOT** of traffic)

The video is very long, so it'll take a while until YouTube processes it, but it will (eventually) be up here: https://youtu.be/KRlFby1XYQ8

**Edit: YouTube has allowed me to comment on the video, so this response can be found there as well**

**Comment by scott-j-smith** [comment]
Thank you!

**Comment by scott-j-smith** [comment]
Closed
