### ISSUE TITLE
Localizer interception via fixes & false-positive penalties

### ISSUE THREAD

**Issue by Shirtail** [zlsa/atc#685]
A/C cleared for an ILS Approach will sometimes lock on & proceed to land while others will fly pass the A/P, never lock on to ILS , will not continue descent & will  go on there merry way. Had any comments on this? Only problem I've ever had . Quite an ATC program.

**Comment by Alpi-no** [comment]
Have you tried it at different heights? If the plane is too high (or at least thinks so), it won't line up

**Comment by kaitsu71** [comment]
Yes, I have noticed that sometimes when you first say for example: "f dumba sfo" and then wait for the airplane to align with the extended runway heading line and then say: "l 28l" the airplane won't always get the ILS lock. I suspect that when the airplane is flying towards the airport it does not cross the runway line and that is needed to get an ILS lock. When the airplane's route crosses the extended runway heading line and land command is given ILS lock seems to work every time.

**Comment by doofus** [comment]
Yes.  I've noticed this as well.  When an aircraft has turned on final and is on course parallel (or very close to parallel) to the runway centerline it will not get the ILS lock.  I have to issue a command for the aircraft to turn slightly for the course to intersect the runway centerline and then re-issue the landing command.  Then it gets an ILS lock.  Sometimes, I have the aircraft dead on the centerline, then issue the landing command and it successfully gets as ILS lock, but then I also get a warning message that the ILS intercept was greater than 30 degrees???  It doesn't get any more perfect than dead on the centerline.

**Comment by scott-j-smith** [comment]
doofus,

I've noticed I get the penalty for greater than 30 degrees all the time too, when they are perfectly lined up with the runway heading before giving the clearance to land, and I know they are at the correct height.  It's only avoided by having them off the runway center line, and giving a heading 10-20 degrees across it with the land command that they lock on with no penalties.

Scott

**Comment by eliuuk** [comment]
You rarely have aircraft intercepting dead straight on with the centre-line. Normally, aircraft should approach from an angle!

**Comment by doofus** [comment]
@scott-j-smith Yes.  That is the behaviour that I have seen as well.  I have to do the same work-around to get an ILS lock as well sometimes.

**Comment by erikquinn** [comment]
Logic needs to be updated to handle this. What it's actually doing is as simple as checking the last heading assigned to the aircraft, and whether or not that heading is within 30 of the runway heading. If you're forcing them on the localizer via fixes, it tries to find the difference between the runway heading and an undefined heading. Unsurprisingly, it gets confused, and says you've done something wrong.

There will need to be two blocks of logic, one for when the waypoint's `navmode` is `fix` and one for when it is `heading` to differentiate between the two situations, because the assigned heading should be used when giving vectors, and the heading from the previous waypoint to the next waypoint should be used when they are being placed on the localizer via fixes.

**Comment by n8rzz** [comment]
Adding this here for visibility : this is being addressed in PR #679 under the https://github.com/n8rzz/atc/issues/2 issue.  @erikquinn has a [WIP] PR https://github.com/n8rzz/atc/pull/15 open and is actively working on it now.

**Comment by erikquinn** [comment]
> Have you tried it at different heights? If the plane is too high (or at least thinks so), it won't line up - @jakobeng1303 

This is no longer the case. Since joining the localizer is independent of the glideslope, they should be able to join it, and if they're above glideslope height we should just penalize the heck out of the player since that is a fairly significant no-no in approach control world. 

> Yes, I have noticed that sometimes when you first say for example: "f dumba sfo" and then wait for the airplane to align with the extended runway heading line and then say: "l 28l" the airplane won't always get the ILS lock. I suspect that when the airplane is flying towards the airport it does not cross the runway line and that is needed to get an ILS lock. When the airplane's route crosses the extended runway heading line and land command is given ILS lock seems to work every time. - @kaitsu71 

As of the merge of #702, interception via fixes instead of radar vectors will yield a successful intercept.

> I've noticed I get the penalty for greater than 30 degrees all the time too, when they are perfectly lined up with the runway heading before giving the clearance to land, and I know they are at the correct height. It's only avoided by having them off the runway center line, and giving a heading 10-20 degrees across it with the land command that they lock on with no penalties. - @scott-j-smith 

This has also been fixed as of #702.

---

Resolved by #702.
