### ISSUE TITLE
Offline Playing

### ISSUE THREAD

**Issue by mchlp** [zlsa/atc#694]
Hi,

I'm wondering if there is a way to play this game offline? For example, is it possible to download the HTML file and run it offline?

Thanks!

**Comment by avdg** [comment]
#674 provides some functionality. Though I didn't got through the research to make it work using the new offline spec. Also no reviews yet on that pr.

**Comment by n8rzz** [comment]
#679 adds a local web server.  So once you go through the process called out in https://github.com/n8rzz/atc/tree/gh-pages/tools, you will then be able to play without an internet connection by running the `npm run start` command in a terminal and then navigating to `localhost:3003` in your web browser.

Hmm, looks like that readme needs some updates before this gets merged.  This is a newer command and it looks like I don't have it documented yet.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.

**Comment by pedriglieri** [comment]
Im a big fan of the simulator. Please add the airport of santo domingo MDSD.

all the charts and information are in     http://aip.idac.gov.do/
