### ISSUE TITLE
Airport Request Online possible?

### ISSUE THREAD

**Issue by joespeed52** [zlsa/atc#701]
```
                                          *Airport Request*
```

I was wondering if there was a possibility of getting a new airport on the online in browser version of the game. KMDT? KPHL? CYVR? KMDW? I don't know how to code, so I wouldn't know how to input these anyway. MDT is my home airport, and i'd think it to be very cool if I could control there, plus, there is restricted airspace that planes need to fly around at MUI, (Muir Army Airfield). If possible, that would be awesome, if not, that's okay, I'd just like a local USA easy airport to control at with interesting terrain and 1 or 2 runways with not a whole lot of traffic. (like you'd need to timewarp to see a bunch.) MDT is an international airport, and has flights to ORD, CLT, and other cool places. 
Thanks,
- joespeed52

**Comment by eliuuk** [comment]
I'll have a look at a later date, I'm currently working on 2 other requests
so we'll see!

**Comment by joespeed52** [comment]
@indianbhaji Thanks for the reply, good to hear.
-joe

**Comment by Alpi-no** [comment]
@joespeed52 believe me, you don't need any knowledge of coding to do this! You may however spend a little amount of time looking at the wiki and existing airports! Maybe someone could set up the base page and you add all the detail. I'm afraid I can't, as my knowledge of this game and coding doesn't go that far

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
