### ISSUE TITLE
Intersection departures

### ISSUE THREAD

**Issue by jpeterson1346** [zlsa/atc#707]
Just want to put this idea out there. Don't have a clue how this could be implemented but it could be useful (well, at least at JFK it would). This way, I could do 31L departures from KE instead of full length, allowing a better ADR (airport departure rate) utilizing 4L.
![jfk intersections](https://cloud.githubusercontent.com/assets/9057104/20041134/9e16936a-a42a-11e6-98ec-050f845cc13a.png)

Comments, suggestions, critiques?

**Comment by Alpi-no** [comment]
Possibly by telling to taxi to a certain intersection

**Comment by erikquinn** [comment]
Due to the complexity of the implementation, I don't think this will come to fruition until proper tower and ground modes are added. I agree though, it does make the flow of the airport (this one in particular) a bit difficult and unrealistic. Hopefully it's not too long until those sorts of things can begin to be added!

**Comment by Alpi-no** [comment]
Theoretically you could add in a new runway that is not shown (maybe the name of the intersection), and tell a plane to taxi to that runway e.g. K31L at KJFK 31L Kilo intersection. It might be a little annoying to add an du may need some tweeting in terms of length and position but could work

**Comment by jpeterson1346** [comment]
@jakobeng1303 That's what I was thinking but then you have extra complications (landing issues, etc.)

**Comment by erikquinn** [comment]
We can bring this back up in the future in great detail when we have the ability to control aircraft's taxi. Closing.
