### ISSUE TITLE
V3 Debugging (5 very minor bugs)

### ISSUE THREAD

**Issue by Fechulo** [zlsa/atc#711]
As requested by @erikquinn, I set out to find as many bugs as I could and I found 5 **very** minor ones. Since I didn't want to spend much time typing up a report with screenshots and other things, I decided to just record a quick [video](https://www.youtube.com/watch?v=Jy83qJGG2Bo&) (4:45)

**TL;DW:**
-Range rings are too bright
-A/C type is lower case on the flight strips
-Readback given after A/C are cleared for T/O is buggy
-Callsigns of GA A/C are broken (e.g. CESSNA376HO instead of N376HO)
-A/C struggle to join the localizer (This is probably the only bug in the list that should be fixed before release)

**Comment by n8rzz** [comment]
Every bug is a bug and I take each one seriously.  By all means, be ruthless!  My goal with this refactor has been for the normal user to not notice any difference (aside from some performance improvements).

I've gone ahead and added each issue to my fork (for easier tracking) for each of the items you've called out and also included some screen grabs from your video.  That video turned out to be very helpful, so thank you very much for that.

As you find more, if you find more (hopefully), please call them out.

**Comment by Fechulo** [comment]
@n8rzz I certainly will! 😄

**Comment by n8rzz** [comment]
@Fechulo you will see we've merged in bugfixes for all but one of the issues you reported and am pushing out a new build now.  When you have a chance, could you take a look and verify that the ones that are marked as fixed are in fact fixed?

Strike that, there are still _two_ issues open. n8rzz#64 will be merged here soon.

**Comment by n8rzz** [comment]
@Fechulo n8rzz#64 has now been merged and deployed.

**Comment by erikquinn** [comment]
## Reference the following issues brought up above:

> -Range rings are too bright

Resoved by #702.

> -A/C type is lower case on the flight strips

Resoved by #702.

> -Readback given after A/C are cleared for T/O is buggy

Resoved by #702.

> -Callsigns of GA A/C are broken (e.g. CESSNA376HO instead of N376HO)

Resoved by #702.

> -A/C struggle to join the localizer (This is probably the only bug in the list that should be fixed before release)

Created a fresh issue in this repo (#717) as a catch-all with the appropriate references, rendering this a duplicate. Can now be closed.
