### ISSUE TITLE
Making new airports offline

### ISSUE THREAD

**Issue by RedRelic** [zlsa/atc#712]
Hi all. I've been paying this game for a while and I've decided I want to make some airports that are more local to me (Australian and New Zealand etc) Most, if not all of the coding in the json files seem pretty self explanitory. I reckon I should have no issues with making new airports.

I have started to make Brisbane airport (YBBN) as I haven't seen anybody mention it yet in here. I've got about half way through so far. I am using the XAMPP method that indianbhaji suggested on #669 to have a working offline version, mainly so I could test my new airport a bit before I put it up on github, I'm paranoid that it's gonna be way wrong lol.

So I used the ebbr.json as my template. I renamed it ybbn.json and am using Notepad++ with the json plugin to edit it and save it.
The file is in the same folder as all the other airports but when I run XAMPP to run the game, my airport does not show up in the list. I'm going to assume I'm missing something obvious here.

Your help is appreciated. If I can figure this all out I'd be happy to make a bunch of new airports for the south pacific region.

**Comment by eliuuk** [comment]
You'll also need to add the airport so the game recognises that it is there. Go into the file airport.js and scroll to the bottom and add your airport in.

**Comment by RedRelic** [comment]
Oh right. Yes I see that now. Thank you very much indianbhaji. I'll try that out when I get home and report back.

Also I hope I'm not breaching any kind of copyright or anything like that with using an already existing airport as a base template?

**Comment by eliuuk** [comment]
Nope! That's fine, it's an open-source project with a MIT license.

**Comment by RedRelic** [comment]
I thought so. Just double checking, wouldn't want to do the wrong thing. Thanks again.

**Comment by n8rzz** [comment]
Also be aware that v3 will change they way airports are loaded.  Instead of adding the airport info directly into a function call, you will now include that same information in the `airportLoadList.js` file: https://github.com/n8rzz/atc/blob/release/3.0.0/src/assets/scripts/airport/airportLoadList.js.

v3 also provides a builtin web server (after you install node and npm).  all thats required is running `npm run start` in a terminal window then opening your web browser to `http://localhost:3003` and you'll be up and running.

**Comment by RedRelic** [comment]
Well, just adding the airport into airport.js didn't bring it up in game for me. Not sure why.

> Also be aware that v3 will change they way airports are loaded. Instead of adding the airport info directly into a function call, you will now include that same information in the airportLoadList.js file: https://github.com/n8rzz/atc/blob/release/3.0.0/src/assets/scripts/airport/airportLoadList.js.

I understand that. Seems simple enough.

> v3 also provides a builtin web server (after you install node and npm). all thats required is running npm run start in a terminal window then opening your web browser to http://localhost:3003 and you'll be up and running.

Not a clue what any of that means to be honest. I'm not really a programmer and know very little of web based languages. If that's even what you're talking about.

Editing all the fields in an airport.json file seems easy enough as I understand what the values are (coords, fixes, sis & stars, etc), even the airlines.json are quite self explanitory.

I just want to make airports, but my knowledge and abilities may not be enough. Am I in way over my head here?

**Comment by n8rzz** [comment]
We all start somewhere.  If you feel over your head, that's fine.  That's normal.  Ask questions, search the interwebs, try, fail, repeat.  Some of the smartest programmers I know do this every day.  It's how we all improve; try, fail, try, fail, try succeed, scratch head while figuring out why.

Don't worry about the web server stuff, if you have something thats working for you stick with that.

When you feel you're ready, you should push your repo to github so we can help you debug. 
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/github-glossary/
http://stackoverflow.com/questions/10573957/pushing-from-local-repository-to-github-hosted-remote

**Comment by RedRelic** [comment]
Thanks for that. It's a different realm than I'm used to. I develop for flightsim mostly, and that took years to get right.

Ok. I'll get some more work done on it, then I'll push it and we'll take it from there. Thanks for those links. They look quite helpful.

**Comment by eliuuk** [comment]
When inserting your airport entry, ensure that yours looks exactly the same as the others. The semicolon on the end is also crucial. If you still cannot see your airport on the loaf screen, try a hard refresh (CTRL + F5) or run in incognito mode.

**Comment by RedRelic** [comment]
I'm pretty confident my entry is spot on. I've tested just editing other entries already there too to see if the changes are seen but they're not.

I will have another look tonight and try the hard refresh and incognito mode too. In the meantime I'm gaining more knowledge from those links n8rzz posted.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
