### ISSUE TITLE
EIDW bugs in 2.1.8

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#714]
Hi All,

I don't know if these bugs are reported previously (didn't come up when I searched for EIDW), or if they are being fixed in 3.0.0, but I noticed 2 things that are incorrect:

1. Inbound flights arriving from the southwest, following the OSGAR..DIRUM.. arrival route are by default flying through restricted airspace, but the restriction is they need to be above FL240, and they arrive at FL100, so they will always be in violation.  This does not appear to be a point penalty at least.

2. Inbound flights from the south (whether through OSGAR..DIRUM.. or VATRY..SORIN..) eventually follow a route that takes them back outside the control area by default (..SUGAD..DW704..DW705..), and there is a 20 point penalty for this.

Thanks,
Scott

**Comment by eliuuk** [comment]
3.0.0 does not fix anything to do with any of the airports, but probably what's going on here are 2 things:
- @Fechulo mentioned that one of the updates which allowed for aircraft to spawn closer to the airspace only spawns the aircraft at FL100, this probably hasn't been fixed
- The airspace needs to be expanded to prevent this.

**Comment by Fechulo** [comment]
@scott-j-smith I've been meaning to fix these issues and others at EIDW for a while, but I'm waiting for v3 to be released before making any changes. These are the things I'd like to change/improve:
- [x] - Remove the OSGAR1L Arrival and replace it for the SUTEX1L Arrival to avoid flying through restricted airspace
- [x] - Update all the STAR's to the new format
- [x] - Add fixes which extend outside of the airspace to simulate airways
- [x] - Update the traffic
- [x] - Add CAT A/B SID's
- [x] - Fix LIFFY5A and DEXEN1A Departures
- [x] - Extend airspace to prevent aircraft from leaving and re-entering the airspace 
- [x] - Add terrain

**Comment by n8rzz** [comment]
FWIW, there is no need to wait for v3 to make these changes.  v3 leaves all the json files and [most] of the logic for rendering untouched.  Any changes made to the _data_ in the json files should carry over just fine to v3.

The only exception is, as I've called out a few times and will document once v3 is merged, is how airports are loaded.  But that is a relatively minor change and should have little affect.

**Comment by n8rzz** [comment]
And for the FL010 spawning altitude, I believe that is still a thing, however, I have added a placeholder issue in my fork so I will remember to revisit it.  In the v3.1 code (yes, I'm already hard at work on that stuff too) I have drastically simplified how aircraft spawn.  So this _may_ be mostly painless to implement in the future.

**Comment by Fechulo** [comment]
This should be fixed once #732 is merged.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
