### ISSUE TITLE
Command parser insensitive to context

### ISSUE THREAD

**Issue by eliuuk** [zlsa/atc#729]
The command `taxi` on its own is to instruct an aircraft to taxi to the start of the runway that is chosen by the game.

`taxi ###` with `###` being a runway designator instructs an aircraft to taxi to that particular runway.

However, if you bundle `taxi` with another command like `caf`, it tells you that 'There is no runway CAF'. It's obvious what the game is doing when you type in `taxi caf`, as it's expecting `caf` to be a runway, whereas it's a command.

This seemed to work before 3.0 though!

**Comment by erikquinn** [comment]
it's vaguely possible it worked a long time ago (before #601), but I'm pretty confident nothing in v3 would have brought this issue to light. It would be nice if it would natively recognize what you mean by `taxi caf`, but it would take a bit of work, and seeing that the workaround of `caf taxi` is available, it won't get much priority. We'll keep the issue here though in case we ever feel the need to fix it.

**Comment by erikquinn** [comment]
This was resolved by n8rzz/atc#179, which was merged as part of v3.2.0 via PR #755.

Closing.
