### ISSUE TITLE
UUDD with SID WT on Rwy 32R Violates Airspace Restriction

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#749]
Hi all,

A flight using SID WT at UUDD from Rwy 32R only gets to FL100 when it enters the restricted airspace to the NE of the airport, which is restricted from FL270 and below.  

Is this a problem with the airport description file, or is the player supposed to be aware of this and control the flight to prevent this violation?

Thanks,
Scott
![image](https://cloud.githubusercontent.com/assets/22403776/20768283/54beff88-b70b-11e6-955d-b5b6f69357a5.png)

**Comment by erikquinn** [comment]
My assumption is that this would be part of the route. After Kartino (WT), they would presumably be filed or assigned the airways that take them around the restricted area. Since they currently only do a route of `airport.departureprocedure.exitpoint`, they kinda leave the SID on their present heading, as seen in your screenshot.

![image](https://cloud.githubusercontent.com/assets/5103735/21028161/e064f572-bd61-11e6-9245-f862cc24f634.png)

The solution is that we need to amend the way departures are listed in the airport files. Created #752 for this.

**Comment by erikquinn** [comment]
@scott-j-smith So for now, maybe it's best to reroute everybody around the restricted area before clearing them for takeoff, eg `RR UUDD.WT.WT..GEKLA..RUGEL..BESTA` or something like that. We can close this issue now that the feature request is documented in the other issue. Thanks for pointing it out. :smile:

**Comment by scott-j-smith** [comment]
Erik,

Will do, once the reroute command is working again.  LOL!   Thanks though!

Scott
