### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by panther2** [zlsa/atc#757]
Just a small cosmetic issue:
What about a favicon showing in the browser tab when launching https://zlsa.github.io/atc/ ?

**Comment by n8rzz** [comment]
@panther2 what browser are you using?

in chrome:
<img width="128" alt="screen shot 2016-12-13 at 6 29 45 am" src="https://cloud.githubusercontent.com/assets/3325985/21140430/9bb75a06-c0fd-11e6-8c08-ca82c33388e9.png">

**Comment by panther2** [comment]
Interesting. This is what it looks like here:

![fav](https://cloud.githubusercontent.com/assets/20812775/21142744/e751b132-c143-11e6-8d66-8ed0c9da9c4a.png)

I am using Chrome on Windows and on two Chromebooks. All oft them at the latest stable version.

**Comment by n8rzz** [comment]
I blame Windows.  I'm on Osx.  What happens if you do a hard refresh?  Sometimes the favicon fails to load on the first try (for whatever reason).  Check your console for that error and reload.

Fun fact: It looks like we don't actually have a favicon in the project, though.  So, I'm guessing, the favicon being displayed is coming from github somewhere.

We should add a favicon to the project to alleviate these kinds of issues.

**Comment by panther2** [comment]
Yes, it does not load a Favicon because indeed there is none:

![fav_cons](https://cloud.githubusercontent.com/assets/20812775/21144785/2ed4b0a6-c14c-11e6-8612-9c099cda4b7c.png)

> We should add a favicon to the project to alleviate these kinds of issues.

Yes, I would appreciate that. Thanks.

**Comment by zlsa** [comment]
This is my bad. I updated my website recently (which is hosted at zlsa.github.io with GitHub pages) and I forgot to add back the favicon. This should be fixed now, but it'll take a while to see (browsers love caching favicons).

**Comment by panther2** [comment]
It already works with me, thanks a lot!
