### ISSUE TITLE
No sound on Chromebooks

### ISSUE THREAD

**Issue by panther2** [zlsa/atc#758]
Sound is not working on my two Chromebooks while it runs fine on my Windows7 using Chrome.

**Comment by erikquinn** [comment]
It's run off some sort of google speech synthesis api or something. Perhaps that does not work on a chromebook? But that doesn't sound likely, as everything is done externally via google, and then the sound is sent back (I assume).

More investigation is needed here.

**Comment by ghost** [comment]
@erikquinn Not sure if http://prntscr.com/dri7aj means anything, but as it says Google Speech API is only partially supported for safari.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
