### ISSUE TITLE
ILS greater than 30 degrees even when im exactly on center line

### ISSUE THREAD

**Issue by ghost** [zlsa/atc#759]
Im playing EDDH at the moment, guide my planes according the way points, so I end up on the extended center line. 
Example route DH655 DH656 HOS
When the airplane is flying this course i enter ils 23 to clear it for landing, and i always get the message that the interception angle was bigger than 30 degree!
Why? Has somebody a similar issue?

Cant wait till the new version is out! Great game/sim

**Comment by limaunion** [comment]
I'm quite a newbie, but yes, I've experienced the same a couple of times (not always) while almost on center line. I mainly use the SAEZ airport.

**Comment by ghost** [comment]
Yes it seems non consistant, some times i get it some times not, sometimes when the aircraft is flying the right heading a clear them for landing it makes a U Turn, some times it locks to ILS...

EDIT:
I think it has to do with the way the plane changes the heading, like in the mathematics behind it in the code.
Lets assume RWY is on 360 degree, your plane willl cross the ILS with an 10 degree angle that means you fly heading 010 or 350. Enter the command for ILS. The computer now calculates the code now and corrects the heading, but not in small steps so you would glide on the heading 360. It will be corrected very aggressive ->"massive" turn until at the perfect ILS line, then again massive turn, if you are unlucky the turn will result in an difference more than 30 degree..

**Comment by scott-j-smith** [comment]
I was just playing SAME today and this bug was no longer present.   I think this can be closed?

**Comment by erikquinn** [comment]
@scott-j-smith I haven't checked since v3.2.1, but I'm pretty sure it is still in issue in a few cases. If you follow the steps in the initial comment above, and *do not* encounter the issue, then maybe it is fixed. But we haven't really changed anything related to localizer interception, so it is most likely still broken for this use case.

**Comment by siqing-wang** [comment]
I got this issue again.

f wesla nepic faith
i 28l

![image](https://cloud.githubusercontent.com/assets/4623358/22186201/aa993a08-e0a6-11e6-9a0c-6fe70f1a9327.png)

**Comment by erikquinn** [comment]
@siqing-wang `WESLA` to `NEPIC` to `FAITH` wouldn't really make sense as a way to get them on the ILS for 28R. If that is the command you used, then the intercept angle warning would be correct. 

Am I right to assume you meant `fix faith nepic wesla i 28r`?

**Comment by siqing-wang** [comment]
When I type "fix welsa nepic faith", it will go to faith first, then nepic, then wesla.

**Comment by erikquinn** [comment]
@siqing-wang I see. Well that's not how that command should be working, so I added a new issue for that (openscope/openscope#153).

As for this issue, thanks for the additional example, I have added that to the issue for localizer interception (openscope/openscope#51).

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
