### ISSUE TITLE
Suggestion: Preload some arrivals?

### ISSUE THREAD

**Issue by soundings** [zlsa/atc#772]
To balance arrivals and departures sooner would it be possible to provide an option to run at timewarp 100 with new departures disabled until the first time an arrival switches to our frequency.

**Comment by eliuuk** [comment]
I don't see how this would exactly work with the 'offset' aspect of arrivals. This would mean that some offsets would need to be edited in order to resolve a few issues with arrivals.

**Comment by erikquinn** [comment]
This *would* be awesome, but with all the different airports, knowing how long to allow it to simulate into the future isn't really practical. Since the sim has no ability to intelligently deal with the aircraft that are moving before the game would "start", they could end up splattered all over the place, and the player would *have* airplanes to play with immediately, but they'd kind of be cleaning up the mess. At this stage, I don't think this is something that will get added. Maybe way downstream when we have automated controllers working the traffic outside our airspace, but that's probably years away. :wink: 

Closing.

**Comment by soundings** [comment]
The program need only timewarp - as suggested - until the first time an arrival switches to our frequency.

Arrivals would be in exactly the same position as if the game had been started without timewarp.

I'm not going to play the tagging game with you but I would ask you to consider reopening.

**Comment by erikquinn** [comment]
@soundings Oh! I must apologize. Full disclosure, I didn't fully re-read the original write-up when looking at this just now. :grimacing: Sorry about that.....

What you're saying is *not* that we should skip ahead until a bunch of aircraft are in the airspace, you're just saying we should **fast forward until the first one enters**.

That's a *very* reasonable and straightforward request, that we can and should absolutely implement. Reopening.

PS: thanks for following up. :+1:

**Comment by panther2** [comment]
How would that affect the clock in the upper left corner? This "real-time"-feature would be negated then - or would the time be set at the moment the first arrival occurs?

**Comment by erikquinn** [comment]
That is a good thing to point out. We can make sure that happens.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
