### ISSUE TITLE
Dangerous approach outside the command area

### ISSUE THREAD

**Issue by panther2** [zlsa/atc#774]
Experienced on EDDH today:
![1](https://cloud.githubusercontent.com/assets/20812775/21568800/cdd2d656-ceb7-11e6-86c8-cbb2100c3793.gif)

**Comment by eliuuk** [comment]
How often are you seeing these?

**Comment by panther2** [comment]
I noticed it the first time today... did not play for long, though...

**Comment by eliuuk** [comment]
In that case, it can be fixed through airport design by adding an offset -
isn't particularly major though, so I'll fix that some time in the first
weeks of 2017.

**Comment by scott-j-smith** [comment]
I think I've seen this at other airports since 3.2.0 was merged too (possibly EDDF?) - might have affected the airport arrivals algorithm?  If I see it anywhere I'll post the details here.

**Comment by erikquinn** [comment]
The most likely cause is the way the arrivals are arranged in the airport file. A few things to point out to that end: 
 - any arrival streams that "join" a common route will not be automatically separated from each other
    - if this attachment is absolutely necessary, perhaps you could make both spawn patterns "cyclic" and apply an "offset" that fixes the issue. This isn't very realistic though.
 - setting a `speed` in a given arrival that is very high can cause successive arrivals to clump up when the first one slows down dramatically due to speed restrictions in the STAR. Consider spawning at the speed of the first speed restriction to resolve that. 
    - setting a speed that is above the capabilities of some aircraft that could be spawned based on the specified airlines means though they will SPAWN with adequate separation, they probably won't have adequate separation by the time they get to the airspace boundary

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
