### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by willfrd** [zlsa/atc#781]
I have various questions about the coding and logic:

1. How do I specify multiple departures for different SID's.
You see, in the update I have in mind for GCRR, my plans are to send the regional traffic i.e. ATR's east because in real life they join the canary islands and in the case of Lanzarote they depart eastwards, the problem is that as I have the code right now regional traffic departs northwards... I thought on modifying the departures section and making it similar to the arrivals:
```
  "departures": [
	{
    "airlines": [
	  ["ryr", 7],
	  ["cnf", 4],
	  ["vlg", 3],
	  ["gmi", 3],
	  ["exs", 3],
	  ["tcx", 3],
	  ["tom", 3],
	  ["cfg", 3],
	  ["tui", 3],
	  ["mon", 3],
	  ["ezy", 3],
	  ["sxd", 3],
	  ["tra", 2],
	  ["aea", 2],
	  ["ber", 2],
	  ["ein", 2],
	  ["ibs", 2],
	  ["nax", 2],
	  ["ent", 2],
	  ["sas", 2],
	  ["tvs", 1],
	  ["baw", 1],
	  ["lightga", 1]
    ],
    "destinations": [
      "SAMAR", "VASTO", "SOTAD", "LORPO", "LARYS"
    ],
    "type": "random",
    "frequency": 26
	},
	{
    "airlines": [
	  ["ibb", 6],
    ],
    "destinations": [
      "KORAL"
    ],
    "type": "random",
    "frequency": 26
	}
  ],
```
But it didn't work, so if someone could help me with that please.

2. Why don´t stars appear drawn on the map?
In GCRR 4 STAR´s are defined with their respective "draw" function, one example could be:
```
"RASE2P": {
      "icao": "RASE2P",
      "name": "Rasep Two Papa",
      "body": ["RASEP", ["GDV71", "S220"], ["MAPED", "A100|S200"], ["LTE15", "A70|S200"], ["254LT", "A60|S180"], ["242LT", "A45|S180"], ["230LT", "A35|S180"], ["233LT", "A31|S180"], ["221LT", "A23|S180"], "GOLFY", "LTE01"],
      "draw": [["RASEP", "GDV71", "MAPED", "LTE15", "254LT", "242LT", "230LT", "233LT", "221LT", "GOLFY", "LTE01"]]
    } 
```
I was wondering if its an error I've made or if they shouldn't be drawn...

3. Taxi times
I have realised many of the airports available here have an extremely short taxi time, I was asking myself if it would be worth for my update and future projects to have a rather more realistic taxi time.

4. Arrivald for different runways
Is it planed in a near future to have arrivals by different runways?

Thanks very much and please tell me if I didn't made myself explanatory.

**Comment by eliuuk** [comment]
I'll answer a few, or in fact 2 of them:

1. You can't at the moment, but @n8rzz has written this lovely article
about what is going to happen in v3.3.0:
https://github.com/n8rzz/atc/blob/feature/ATC-243/src/assets/scripts/client/trafficGenerator/spawnPatternReadme.md

2. STARs don't appear because I believe it hasn't been programmed into the
game yet.

**Comment by willfrd** [comment]
Thanks @indianbhaji ! :D

**Comment by n8rzz** [comment]
Correct and Correct!  Adding STARs visually is on my wish list, though I have not created an issue for it.  Someday that will be a thing, but not in the immediate future.

**Comment by willfrd** [comment]
Cool, @n8rzz , it would be very useful visually, maybe even adding the lines of the STAR's with another colour, red?, anyways, thanks for considering it :-)

**Comment by willfrd** [comment]
BTW, maybe until it gets implemented we shoud consider removing it from the wiki...

**Comment by n8rzz** [comment]
@willfrd Its in the wiki?  Where?

**Comment by willfrd** [comment]
@n8rzz On the Airport format description page of the wiki:

![star](https://cloud.githubusercontent.com/assets/20045335/22055207/f3a7c064-dd51-11e6-8eda-5fd3659a8c17.jpg)

**Comment by eliuuk** [comment]
I would not get rid of it yet because it is something that will probably be dealt with in the future - it is nice to future-proof!

**Comment by erikquinn** [comment]
I agree that they should stay in place in the airport files even though they aren't added into the game yet. With the ever growing list of airports, it can be very time consuming to go through each one and make changes needed for a particular upgrade like this. But if the draw sections are already in there, it's a pretty quick process. :smiley:

Also, about your other questions :
3. Yes and no. It's unrealistic that we are working a radar position and ground control at the same time. And since we don't display (or have) taxiways and such, the taxi delay would be just about as weird as there being no taxi delay. The real solution here is to add taxiways and a proper ground control mode. That's coming, but it's pretty far off. 

4. I'm not sure I understand this question... You can take them to any runway you choose, even if it's one with a tailwind. Could you clarify what you meant here?

**Comment by willfrd** [comment]
Ok so I will keep addind the draw attribute for the stars.

3. Therefore for the taxi times I suppose I will keep adding times which are not zero and too much, and then will update whed the big update happens. :)

4. Forget about this one its OK.

Thanks guys! Hope I have my project up as fast as possible (presumably after the 3.3.0 update)

BTW, would it be worth to add a request about the visually drawing the STAR´s?

**Comment by eliuuk** [comment]
@willfrd I believe that the issue should be in openscope/openscope instead of here, so I've opened it as openscope/openscope#111.

**Comment by willfrd** [comment]
Ok, Thanks again for all your answers, closing.
