### ISSUE TITLE
Game crashes after issuing "Hold" command

### ISSUE THREAD

**Issue by scott-j-smith** [zlsa/atc#782]
I was playing on SAME today for over an hour, and everything was great until I issued a "Hold" command and the game crashed.

On another note - I noticed a lot of bugs have been fixed, but the console says it is still 3.2.0.  Might want to update that?

![image](https://cloud.githubusercontent.com/assets/22403776/22161037/829a7ba2-df16-11e6-848f-a6043aad5f7e.png)

**Comment by erikquinn** [comment]
Well that's no good! We'll get the `hold` command working.

As for the version number, that's my fault for rushing. Nonetheless, `v4.0.0` will be the new number at the conclusion of the `3.3.0` sprint very soon here, and we'll be sure to update it there; so in this case, we'll just let my mistake slide. 😉

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
