### ISSUE TITLE
Reroute command countermands altitude command

### ISSUE THREAD

**Issue by dutchdavey** [zlsa/atc#785]
In the last couple of days I've noticed that an 'a 30' command (e.g.) is cancelled by a 'rr'.

?

**Comment by dutchdavey** [comment]
and the fix command also cancels the altitude command

Waddawe do now? Clear the skies?

**Comment by dutchdavey** [comment]
If you issue the 'a xxx' command to an aircraft it begins its descent. If you then issue a fix or rr, the aircraft stops its descent and holds its current altitude, 

Workaround: Alwasy issue the 'a xxx' command as last in the line, and reissue it in the same fashion, following any fix or reroute.

**Comment by erikquinn** [comment]
Created openscope/openscope#197 for this.

**Comment by erikquinn** [comment]
The ATC repository is being migrated to it's new home at [https://github.com/openscope/openscope](https://github.com/openscope/openscope), 
and thus, all issues are being closed. If this is still an issue with the latest version of the sim 
(accessible at [http://www.openscope.co](http://www.openscope.co)), or is a feature you still think we are lacking, 
please reopen the issue at the new repo.

*Please note that the vast majority of these issues have been copied to the new repository, or else are covered by other issues created there. See the below screenshot for what it looks like when your issue is known in the new repo:*

![image](https://cloud.githubusercontent.com/assets/5103735/22630816/5a32d794-ebce-11e6-9c46-d61a262e2b23.png)


 Thank you!


Closing this issue.
