### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sixeyeco** [zlsa/atc#92]
<h5>Select preset scenarios</h5>

Sometimes I reload twenty times or more to get a good one (17 strips at KMSP seems to be the max). Would it be possible to select specific preset scenarios? I would like to have the ability to pick a scenario with the most strips. 

<h5>More flight progress strips</h5>

More strips would be great. I can see that as it is now there is insufficient space to have more than 17 or so. How about giving up some radar real estate so that strips are displayed side by side? We can always zoom out to see everything. 

<h5>Greater zoom levels</h5>

When lining up craft for approach I often position them so close that there are several white circles in a very small space. I need to see more detail to effectively manage these tight approaches. Would a higher zoom level would also address the issue about tags obscuring other craft? I'd like to see two additional zoom levels. 

<h5>A Leaderboard</h5>

In playing this great game I am filled with a desire to compete and to further challenge my burgeoning skills. How about a leaderboard? I'd love to see how I stack up against others. Maybe a preset scenario with a timer? In the interest of fairness the pause button should be disabled.  

![atc-leaderboard-and-more-strips](https://cloud.githubusercontent.com/assets/179496/6397821/5a2355e2-bd9c-11e4-8cd2-e0838611cda9.gif)

I thoroughly enjoy this game and and very grateful for the work you have all put in to it. As a web designer I know how difficult and time consuming even minor changes can be.

Sorry if this is in the wrong section, I couldn't find a way to label my post as a question.

**Comment by zlsa** [comment]
Sorry about the delay; I hadn't noticed the new issues yet.

**Select preset scenarios**

Do you mean a way to save and restore the state of the simulation? I've been thinking about a way to do this cleanly for a while now but I haven't really seen the need.

**More flight progress strips**
Would you like this to be separate departure and arrival columns or to just make it twice as wide? (In the latter case, the strips would just go back and forth without any real order, but then the "one column is full and the other is empty" issue is avoided.)

**Greater zoom levels**
You can pan and zoom right now with the mouse scroll wheel and dragging.

**A leaderboard**
This is difficult to implement (and easy to cheat, unfortunately). It means that I have to have a webserver somewhere that's recording client scores as well as a way to verify that clients aren't cheating. Since ATC is very easy to manipulate (via tricks such as creating your own airport that has all airplanes lined up for approach from the start), I don't see this being implemented in the near future.

No problem, but in the future it would be more convienent to open a new issue for each question you have (so they can be closed and worked out independently).

**Comment by sixeyeco** [comment]
Thank you, will do. I didn't want to bombard you with multiples. But I will do so in the future. I'll close this one and resubmit the ones that I think are still valid. Thanks again for an awesome game.
